import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "npm:@supabase/supabase-js@2.57.4";
import { createRemoteJWKSet, importPKCS8, jwtVerify, SignJWT } from "npm:jose@5.10.0";

const FIREBASE_PROJECT_ID = "mic-rhema";
const FIREBASE_ISSUER = `https://securetoken.google.com/${FIREBASE_PROJECT_ID}`;
const FIREBASE_JWKS = createRemoteJWKSet(new URL("https://www.googleapis.com/service_accounts/v1/jwk/securetoken@system.gserviceaccount.com"));
const GOOGLE_TOKEN_URL = "https://oauth2.googleapis.com/token";
const LEVEL_8_PLUS = new Set(["semente_da_fe","caminho_da_promessa","escudo_da_fe","aguas_vivas","videira_verdadeira","luz_do_mundo","armadura_de_deus","leao_de_juda","chama_do_espirito","coroa_da_vida","asas_da_promessa","tabernaculo","arca_da_alianca","nova_jerusalem","gloria_eterna"]);

type ServiceAccount={project_id?:string;client_email?:string;private_key?:string};
class HttpError extends Error{constructor(public status:number,message:string){super(message)}}
const cors={"access-control-allow-origin":"*","access-control-allow-headers":"authorization, content-type","access-control-allow-methods":"POST, OPTIONS","content-type":"application/json; charset=utf-8","cache-control":"no-store"};
const json=(body:Record<string,unknown>,status=200)=>new Response(JSON.stringify(body),{status,headers:cors});
const clean=(v:unknown,max=500)=>String(v??"").trim().slice(0,max);
function decode(v:any):any{if(!v)return undefined;if("stringValue"in v)return v.stringValue;if("booleanValue"in v)return v.booleanValue;if("integerValue"in v)return Number(v.integerValue);if("doubleValue"in v)return Number(v.doubleValue);if("arrayValue"in v)return(v.arrayValue?.values||[]).map(decode);if("mapValue"in v)return Object.fromEntries(Object.entries(v.mapValue?.fields||{}).map(([k,x])=>[k,decode(x)]));return undefined}
function fields(doc:any){return Object.fromEntries(Object.entries(doc?.fields||{}).map(([k,v])=>[k,decode(v)]))as Record<string,any>}
const list=(v:unknown)=>Array.isArray(v)?v.map(String).filter(Boolean):[];
function activityMap(v:unknown):Record<string,string[]>{if(!v||typeof v!=="object"||Array.isArray(v))return{};return Object.fromEntries(Object.entries(v as Record<string,unknown>).map(([k,x])=>[k,list(x)]))}
function legacyXp(data:Record<string,any>){return[...new Set(activityMap(data.badgeActivityIds).journey_xp_awards||[])].reduce((sum,e)=>{const n=Number(String(e).slice(String(e).lastIndexOf("=")+1));return sum+(Number.isFinite(n)&&n>0?Math.floor(n):0)},0)}
async function firebaseUid(request:Request){const token=(request.headers.get("authorization")||"").match(/^Bearer\s+(.+)$/i)?.[1];if(!token)throw new HttpError(401,"Sessão ausente.");try{const r=await jwtVerify(token,FIREBASE_JWKS,{issuer:FIREBASE_ISSUER,audience:FIREBASE_PROJECT_ID,algorithms:["RS256"]});if(!r.payload.sub)throw 0;return String(r.payload.sub)}catch{throw new HttpError(401,"Sessão Firebase inválida.")}}
async function googleToken(account:ServiceAccount){if(!account.client_email||!account.private_key)throw new HttpError(500,"Credencial Firebase incompleta.");const now=Math.floor(Date.now()/1000);const assertion=await new SignJWT({iss:account.client_email,scope:"https://www.googleapis.com/auth/datastore",aud:GOOGLE_TOKEN_URL}).setProtectedHeader({alg:"RS256",typ:"JWT"}).setIssuedAt(now).setExpirationTime(now+3600).sign(await importPKCS8(account.private_key.replace(/\\n/g,"\n"),"RS256"));const r=await fetch(GOOGLE_TOKEN_URL,{method:"POST",headers:{"content-type":"application/x-www-form-urlencoded"},body:new URLSearchParams({grant_type:"urn:ietf:params:oauth2:grant-type:jwt-bearer",assertion})});const p=await r.json();if(!r.ok||!p.access_token)throw new HttpError(500,"Falha ao autenticar no Firebase.");return String(p.access_token)}
function base(projectId:string){return`https://firestore.googleapis.com/v1/projects/${projectId}/databases/(default)/documents`}
async function read(projectId:string,token:string,path:string){const r=await fetch(`${base(projectId)}/${path}`,{headers:{authorization:`Bearer ${token}`}});if(r.status===404)return null;if(!r.ok)throw new HttpError(502,"Falha ao consultar conteúdo.");return await r.json()}

Deno.serve(async(request)=>{if(request.method==="OPTIONS")return new Response("ok",{headers:cors});if(request.method!=="POST")return json({error:"Método não permitido."},405);try{
 const memberId=await firebaseUid(request);const input=await request.json()as Record<string,unknown>;const contentId=clean(input.contentId,180);const elapsedMs=Math.max(0,Math.min(60000,Math.floor(Number(input.elapsedMs)||0)));const fraction=Math.max(0,Math.min(1,Number(input.fraction)||0));if(!contentId)throw new HttpError(400,"Devocional inválido.");
 const service=JSON.parse(Deno.env.get("FIREBASE_SERVICE_ACCOUNT_JSON")||"{}")as ServiceAccount;const projectId=service.project_id||FIREBASE_PROJECT_ID;const token=await googleToken(service);const accessDoc=await read(projectId,token,`acessos_pendentes/${encodeURIComponent(memberId)}`);if(!accessDoc)throw new HttpError(404,"Perfil não encontrado.");const access=fields(accessDoc);if(access.isApproved!==true&&access.isAdmin!==true)throw new HttpError(403,"Perfil ainda não aprovado.");const devotional=await read(projectId,token,`devocionais/${encodeURIComponent(contentId)}`);if(!devotional)throw new HttpError(400,"Devocional não pertence ao catálogo oficial.");const d=fields(devotional);if(d.approved===false||d.isApproved===false)throw new HttpError(400,"Devocional não está aprovado para XP.");
 const url=Deno.env.get("SUPABASE_URL")||"",role=Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")||"";if(!url||!role)throw new HttpError(500,"Ledger XP não configurado.");const sb=createClient(url,role,{auth:{persistSession:false,autoRefreshToken:false}});const{data:ensured,error:ee}=await sb.rpc("xp_ensure_account",{p_member_id:memberId,p_legacy_xp:legacyXp(access)});if(ee)throw ee;const account=Array.isArray(ensured)?ensured[0]:ensured;const unlocked=list(access.unlockedBadgeIds).some(id=>LEVEL_8_PLUS.has(id));if(!unlocked)return json({ok:true,unlocked:false,granted:0,qualified:false,account});
 if(elapsedMs<15000||fraction<0.8)return json({ok:true,unlocked:true,granted:0,qualified:false,account});
 const{data,error}=await sb.rpc("xp_award",{p_member_id:memberId,p_activity:"devotional",p_content_id:contentId,p_variant:"",p_receipt_id:`devotional:${contentId}`,p_amount:5,p_description:"Devocional concluído",p_daily_cap:0});if(error)throw error;const row=Array.isArray(data)?data[0]:data;return json({ok:true,unlocked:true,qualified:true,granted:Number(row?.granted??0),duplicate:Boolean(row?.duplicate),account:{member_id:memberId,total_earned:Number(row?.total_earned??account?.total_earned??0),total_spent:Number(row?.total_spent??account?.total_spent??0),balance:Number(row?.balance??account?.balance??0)}});
}catch(error){if(error instanceof HttpError)return json({error:error.message},error.status);console.error("pwa-xp-devotional",error);return json({error:"Não foi possível validar o devocional agora."},500)}});