import { createRemoteJWKSet, errors as joseErrors, jwtVerify, importPKCS8, SignJWT } from "npm:jose@5.10.0";

const PROJECT="mic-rhema";const ISSUER=`https://securetoken.google.com/${PROJECT}`;const JWKS=createRemoteJWKSet(new URL("https://www.googleapis.com/service_accounts/v1/jwk/securetoken@system.gserviceaccount.com"));const TOKEN_URL="https://oauth2.googleapis.com/token";
const allowedKeys=new Set(["plans","plan_themes","books","videos","bible_chapters","bible_news","devotionals","audios","active_minutes"]);
const cors={"access-control-allow-origin":"*","access-control-allow-headers":"authorization, content-type","access-control-allow-methods":"POST, OPTIONS","content-type":"application/json; charset=utf-8","cache-control":"no-store"};
type Account={project_id?:string;client_email?:string;private_key?:string};
class HttpError extends Error{constructor(public status:number,message:string){super(message)}}
const json=(body:Record<string,unknown>,status=200)=>new Response(JSON.stringify(body),{status,headers:cors});
function bearer(req:Request){const m=(req.headers.get("authorization")||"").match(/^Bearer\s+(.+)$/i);if(!m)throw new HttpError(401,"Sessão ausente.");return m[1]}
async function verify(token:string){try{const r=await jwtVerify(token,JWKS,{issuer:ISSUER,audience:PROJECT,algorithms:["RS256"]});if(!r.payload.sub)throw new HttpError(401,"Sessão inválida.");return String(r.payload.sub)}catch(e){if(e instanceof HttpError)throw e;if(e instanceof joseErrors.JWTExpired)throw new HttpError(401,"Sessão expirada.");throw new HttpError(401,"Sessão inválida.")}}
async function access(account:Account){if(!account.client_email||!account.private_key)throw new HttpError(500,"Credencial Firebase incompleta.");const now=Math.floor(Date.now()/1000);const assertion=await new SignJWT({iss:account.client_email,scope:"https://www.googleapis.com/auth/datastore",aud:TOKEN_URL}).setProtectedHeader({alg:"RS256",typ:"JWT"}).setIssuedAt(now).setExpirationTime(now+3600).sign(await importPKCS8(account.private_key.replace(/\\n/g,"\n"),"RS256"));const r=await fetch(TOKEN_URL,{method:"POST",headers:{"content-type":"application/x-www-form-urlencoded"},body:new URLSearchParams({grant_type:"urn:ietf:params:oauth:grant-type:jwt-bearer",assertion})});const p=await r.json();if(!r.ok||!p.access_token)throw new HttpError(500,"Falha ao sincronizar progresso.");return String(p.access_token)}
function decode(v:any):any{if(!v)return undefined;if("stringValue"in v)return v.stringValue;if("booleanValue"in v)return v.booleanValue;if("integerValue"in v)return Number(v.integerValue);if("doubleValue"in v)return Number(v.doubleValue);if("arrayValue"in v)return(v.arrayValue?.values||[]).map(decode);if("mapValue"in v)return Object.fromEntries(Object.entries(v.mapValue?.fields||{}).map(([k,x])=>[k,decode(x)]));return undefined}
function encode(v:any):any{if(typeof v==="boolean")return{booleanValue:v};if(typeof v==="number")return Number.isInteger(v)?{integerValue:String(v)}:{doubleValue:v};if(Array.isArray(v))return{arrayValue:{values:v.map(encode)}};if(v&&typeof v==="object")return{mapValue:{fields:Object.fromEntries(Object.entries(v).map(([k,x])=>[k,encode(x)]))}};return{stringValue:String(v??"")}}
const base=(project:string)=>`https://firestore.googleapis.com/v1/projects/${project}/databases/(default)/documents`;
async function getDoc(project:string,token:string,path:string){const r=await fetch(`${base(project)}/${path}`,{headers:{authorization:`Bearer ${token}`}});if(r.status===404)return null;if(!r.ok)throw new HttpError(502,"Não foi possível ler o progresso.");return await r.json() as any}
async function listDocs(project:string,token:string,path:string){const r=await fetch(`${base(project)}/${path}?pageSize=500`,{headers:{authorization:`Bearer ${token}`}});if(!r.ok)return[];const p=await r.json() as any;return p.documents||[]}
async function patch(project:string,token:string,path:string,data:Record<string,unknown>){const mask=Object.keys(data).map(k=>`updateMask.fieldPaths=${encodeURIComponent(k)}`).join("&");const r=await fetch(`${base(project)}/${path}?${mask}`,{method:"PATCH",headers:{authorization:`Bearer ${token}`,"content-type":"application/json"},body:JSON.stringify({fields:Object.fromEntries(Object.entries(data).map(([k,v])=>[k,encode(v)]))})});if(!r.ok)throw new HttpError(502,"Não foi possível salvar o progresso.")}
function fields(doc:any){return Object.fromEntries(Object.entries(doc?.fields||{}).map(([k,v])=>[k,decode(v)])) as Record<string,any>}
function count(map:Record<string,string[]>,key:string){return new Set((map[key]||[]).map(String)).size}
function calculate(existing:string[],map:Record<string,string[]>,completedCourses:number){const unlocked=new Set(existing.length?existing:["caminhante"]);const counts={plans:count(map,"plans"),plan_themes:count(map,"plan_themes"),books:count(map,"books"),videos:count(map,"videos"),bible_chapters:count(map,"bible_chapters"),bible_news:count(map,"bible_news"),devotionals:count(map,"devotionals"),audios:count(map,"audios")};const active=count(map,"active_minutes");if(counts.devotionals>=3&&counts.plan_themes>=1)unlocked.add("semeador");if(counts.plans>=1&&counts.plan_themes>=3&&counts.bible_chapters>=3)unlocked.add("discipulo");if(active>=60&&Object.values(counts).reduce((a,b)=>a+b,0)>=10)unlocked.add("perseverante");if(counts.books>=3&&counts.videos>=3&&counts.audios>=2)unlocked.add("estudante_rhema");if(completedCourses>=1&&counts.bible_news>=3&&counts.bible_chapters>=10)unlocked.add("mestre_da_palavra");if(unlocked.has("mestre_da_palavra")&&Object.values(counts).every(v=>v>=1)&&active>=180)unlocked.add("guardiao_da_fe");return[...unlocked]}
async function completedCourses(project:string,token:string,uid:string){const courses=(await listDocs(project,token,"ibr_courses")).map(fields);const progress=(await listDocs(project,token,`users/${encodeURIComponent(uid)}/ibrProgress`)).map(fields);return courses.filter((course:any)=>Array.isArray(course.chapters)&&course.chapters.length>0&&course.chapters.every((chapter:any)=>progress.some((p:any)=>String(p.courseId)===String(course.id||course._id||"")&&String(p.chapterId)===String(chapter.id)&&p.isCompleted===true))).length}
Deno.serve(async(req:Request)=>{if(req.method==="OPTIONS")return new Response("ok",{headers:cors});if(req.method!=="POST")return json({error:"Método não permitido."},405);try{const uid=await verify(bearer(req));const input=await req.json() as {activity?:unknown;itemId?:unknown};const activity=String(input.activity||"").trim();const itemId=String(input.itemId||"").trim().slice(0,180);if(!allowedKeys.has(activity)||!itemId)return json({error:"Atividade inválida."},400);const account=JSON.parse(Deno.env.get("FIREBASE_SERVICE_ACCOUNT_JSON")||"{}") as Account;const project=account.project_id||PROJECT;const token=await access(account);const member=await getDoc(project,token,`acessos_pendentes/${encodeURIComponent(uid)}`);if(!member)throw new HttpError(404,"Perfil não encontrado.");const data=fields(member);if(data.isApproved!==true&&data.isAdmin!==true)throw new HttpError(403,"Perfil ainda não aprovado.");const map=(data.badgeActivityIds&&typeof data.badgeActivityIds==="object"?data.badgeActivityIds:{}) as Record<string,string[]>;const current=Array.isArray(map[activity])?map[activity].map(String):[];if(!current.includes(itemId))map[activity]=[...current,itemId].slice(-6000);const before=Array.isArray(data.unlockedBadgeIds)?data.unlockedBadgeIds.map(String):[];const courses=await completedCourses(project,token,uid);const unlocked=calculate(before,map,courses);const patchData={badgeActivityIds:map,unlockedBadgeIds:unlocked,updatedAt:Date.now()};await patch(project,token,`acessos_pendentes/${encodeURIComponent(uid)}`,patchData);await patch(project,token,`users/${encodeURIComponent(uid)}`,patchData).catch(()=>undefined);return json({ok:true,unlockedBadgeIds:unlocked,newlyUnlocked:unlocked.filter(id=>!before.includes(id))});}catch(e){if(e instanceof HttpError)return json({error:e.message},e.status);console.error("pwa-badge-activity",e);return json({error:"Não foi possível registrar o progresso agora."},500)}});
