package com.aistudio.micrhema

private fun quizQuestion(
    id: String,
    difficulty: BibleQuizDifficulty,
    prompt: String,
    options: List<String>,
    correct: Int,
    hardHint: String,
    easyHint: String,
    reference: String,
    explanation: String,
    book: String,
    chapter: Int,
    verse: Int? = null,
    endVerse: Int? = null
) = BibleQuizQuestion(
    id = id,
    prompt = prompt,
    options = options,
    correctOptionIndex = correct,
    difficulty = difficulty,
    hardHint = hardHint,
    easyHint = easyHint,
    bibleReference = reference,
    explanation = explanation,
    book = book,
    chapter = chapter,
    verse = verse,
    endVerse = endVerse
)

/** Banco inicial oficial: 40 fáceis, 40 médias e 40 difíceis. */
object BibleQuizCatalog {
    val questions: List<BibleQuizQuestion> = listOf(
        // FÁCIL 01-40
        quizQuestion("easy_001", BibleQuizDifficulty.EASY, "Quem construiu a arca antes do dilúvio?", listOf("Abraão", "Noé", "Moisés", "Davi"), 1, "Deus orientou um homem justo a construir uma grande embarcação.", "Seu nome começa com N.", "Gênesis 6:13–22", "Noé recebeu de Deus as instruções para construir a arca.", "Gênesis", 6, 13, 22),
        quizQuestion("easy_002", BibleQuizDifficulty.EASY, "Quem derrotou Golias?", listOf("Saul", "Jônatas", "Davi", "Samuel"), 2, "Era um jovem pastor que confiou em Deus.", "Ele se tornou rei de Israel.", "1 Samuel 17:45–50", "Davi venceu Golias usando uma funda e uma pedra.", "1 Samuel", 17, 45, 50),
        quizQuestion("easy_003", BibleQuizDifficulty.EASY, "Quem liderou os israelitas para fora do Egito?", listOf("Moisés", "Josué", "Arão", "José"), 0, "Deus falou com ele junto a uma sarça ardente.", "Ele recebeu os Dez Mandamentos.", "Êxodo 3:7–10", "Moisés foi chamado por Deus para libertar Israel do Egito.", "Êxodo", 3, 7, 10),
        quizQuestion("easy_004", BibleQuizDifficulty.EASY, "Em qual cidade Jesus nasceu?", listOf("Nazaré", "Jerusalém", "Belém", "Cafarnaum"), 2, "A cidade estava ligada à linhagem de Davi.", "Miquéias havia profetizado esse lugar.", "Lucas 2:4–7", "Jesus nasceu em Belém, cidade de Davi.", "Lucas", 2, 4, 7),
        quizQuestion("easy_005", BibleQuizDifficulty.EASY, "Quem foi a mãe de Jesus?", listOf("Marta", "Maria", "Isabel", "Ana"), 1, "Um anjo anunciou a ela que conceberia pelo Espírito Santo.", "Seu nome aparece na anunciação feita por Gabriel.", "Lucas 1:26–31", "Maria recebeu o anúncio de que daria à luz Jesus.", "Lucas", 1, 26, 31),
        quizQuestion("easy_006", BibleQuizDifficulty.EASY, "Quem foi o primeiro homem?", listOf("Adão", "Abel", "Noé", "Sete"), 0, "Deus o formou do pó da terra.", "Seu nome aparece no jardim do Éden.", "Gênesis 2:7", "Adão foi formado por Deus do pó da terra.", "Gênesis", 2, 7),
        quizQuestion("easy_007", BibleQuizDifficulty.EASY, "Quem foi a primeira mulher?", listOf("Sara", "Rebeca", "Eva", "Raquel"), 2, "Ela foi criada para ser companheira de Adão.", "Seu nome está ligado ao início da humanidade.", "Gênesis 2:21–23", "Eva foi criada por Deus e apresentada a Adão.", "Gênesis", 2, 21, 23),
        quizQuestion("easy_008", BibleQuizDifficulty.EASY, "Qual profeta foi engolido por um grande peixe?", listOf("Jonas", "Amós", "Elias", "Isaías"), 0, "Ele tentou fugir da missão de ir a Nínive.", "Seu livro tem o mesmo nome dele.", "Jonas 1:15–17", "Jonas foi lançado ao mar e um grande peixe o engoliu.", "Jonas", 1, 15, 17),
        quizQuestion("easy_009", BibleQuizDifficulty.EASY, "No casamento em Caná, Jesus transformou água em quê?", listOf("Azeite", "Mel", "Vinho", "Leite"), 2, "Foi o primeiro sinal narrado no Evangelho de João.", "A festa havia ficado sem essa bebida.", "João 2:7–11", "Jesus transformou água em vinho em Caná da Galileia.", "João", 2, 7, 11),
        quizQuestion("easy_010", BibleQuizDifficulty.EASY, "Quantos apóstolos Jesus escolheu para formar o grupo dos Doze?", listOf("7", "10", "12", "14"), 2, "O próprio nome do grupo dá uma pista.", "Foram chamados de os Doze.", "Lucas 6:13–16", "Jesus escolheu doze discípulos e os chamou apóstolos.", "Lucas", 6, 13, 16),
        quizQuestion("easy_011", BibleQuizDifficulty.EASY, "Quem batizou Jesus no rio Jordão?", listOf("Pedro", "João Batista", "Tiago", "André"), 1, "Ele pregava arrependimento no deserto.", "Era conhecido justamente por batizar pessoas.", "Mateus 3:13–17", "João Batista batizou Jesus no Jordão.", "Mateus", 3, 13, 17),
        quizQuestion("easy_012", BibleQuizDifficulty.EASY, "Quem traiu Jesus por moedas de prata?", listOf("Judas Iscariotes", "Tomé", "Filipe", "Bartolomeu"), 0, "Ele fazia parte dos Doze.", "Seu primeiro nome é Judas.", "Mateus 26:14–16", "Judas Iscariotes combinou entregar Jesus em troca de trinta moedas de prata.", "Mateus", 26, 14, 16),
        quizQuestion("easy_013", BibleQuizDifficulty.EASY, "Qual discípulo negou Jesus três vezes?", listOf("João", "Pedro", "Mateus", "André"), 1, "Jesus havia avisado que isso aconteceria antes do galo cantar.", "Ele também era chamado Simão.", "Mateus 26:69–75", "Pedro negou conhecer Jesus três vezes e depois se lembrou da palavra do Senhor.", "Mateus", 26, 69, 75),
        quizQuestion("easy_014", BibleQuizDifficulty.EASY, "Em qual monte Moisés recebeu a lei de Deus?", listOf("Carmelo", "Sinai", "Oliveiras", "Tabor"), 1, "Israel acampou diante desse monte no deserto.", "É o monte associado aos Dez Mandamentos.", "Êxodo 19:18–20", "Moisés subiu ao monte Sinai para encontrar-se com Deus.", "Êxodo", 19, 18, 20),
        quizQuestion("easy_015", BibleQuizDifficulty.EASY, "Quem chorou diante do túmulo de Lázaro?", listOf("Jesus", "Pedro", "Tomé", "Zaqueu"), 0, "Ele amava Lázaro e suas irmãs.", "Logo depois, chamou Lázaro para fora do túmulo.", "João 11:33–44", "Jesus se comoveu diante do túmulo de Lázaro e depois o ressuscitou.", "João", 11, 33, 44),
        quizQuestion("easy_016", BibleQuizDifficulty.EASY, "Quem Jesus ressuscitou em Betânia depois de quatro dias no túmulo?", listOf("Estêvão", "Lázaro", "Jairo", "Barnabé"), 1, "Era irmão de Marta e Maria.", "Jesus o chamou para fora do túmulo.", "João 11:38–44", "Lázaro foi chamado para fora do túmulo por Jesus.", "João", 11, 38, 44),
        quizQuestion("easy_017", BibleQuizDifficulty.EASY, "Quem interpretou os sonhos do faraó no Egito?", listOf("José", "Benjamim", "Jacó", "Arão"), 0, "Ele havia sido vendido por seus irmãos.", "Tornou-se governador no Egito.", "Gênesis 41:14–32", "José explicou que os sonhos anunciavam anos de fartura e fome.", "Gênesis", 41, 14, 32),
        quizQuestion("easy_018", BibleQuizDifficulty.EASY, "Quem foi lançado na cova dos leões?", listOf("Daniel", "Jeremias", "Ezequiel", "Esdras"), 0, "Ele continuou orando a Deus apesar do decreto real.", "Seu livro relata a cova dos leões.", "Daniel 6:16–23", "Daniel foi preservado por Deus na cova dos leões.", "Daniel", 6, 16, 23),
        quizQuestion("easy_019", BibleQuizDifficulty.EASY, "Qual rainha arriscou a vida para defender o povo judeu?", listOf("Jezabel", "Ester", "Bate-Seba", "Vasti"), 1, "Ela se apresentou ao rei sem ser chamada.", "Seu nome dá título a um livro bíblico.", "Ester 4:13–16", "Ester decidiu comparecer diante do rei em favor de seu povo.", "Ester", 4, 13, 16),
        quizQuestion("easy_020", BibleQuizDifficulty.EASY, "Qual homem conhecido por sua força teve o cabelo cortado?", listOf("Sansão", "Gideão", "Saul", "Absalão"), 0, "Dalila descobriu o segredo ligado ao seu voto.", "Ele foi juiz de Israel.", "Juízes 16:17–20", "Sansão perdeu sua força depois que seu cabelo foi cortado.", "Juízes", 16, 17, 20),
        quizQuestion("easy_021", BibleQuizDifficulty.EASY, "Qual rei construiu o primeiro templo em Jerusalém?", listOf("Saul", "Davi", "Salomão", "Ezequias"), 2, "Seu pai desejou construir o templo, mas o filho realizou a obra.", "Era filho do rei Davi.", "1 Reis 6:1", "Salomão iniciou a construção do templo em Jerusalém.", "1 Reis", 6, 1),
        quizQuestion("easy_022", BibleQuizDifficulty.EASY, "Quem recebeu de Deus a promessa de que teria muitos descendentes e saiu de sua terra pela fé?", listOf("Abraão", "Ló", "Ismael", "Esaú"), 0, "Ele deixou sua terra em direção ao lugar que Deus mostraria.", "É chamado pai de uma grande descendência.", "Gênesis 12:1–3", "Abraão obedeceu ao chamado e recebeu promessas de Deus.", "Gênesis", 12, 1, 3),
        quizQuestion("easy_023", BibleQuizDifficulty.EASY, "Qual filho de Jacó foi vendido por seus irmãos e levado ao Egito?", listOf("Judá", "José", "Levi", "Rúben"), 1, "Ele havia recebido uma túnica especial de seu pai.", "Mais tarde interpretou os sonhos do faraó.", "Gênesis 37:23–28", "José foi vendido por seus irmãos e levado ao Egito.", "Gênesis", 37, 23, 28),
        quizQuestion("easy_024", BibleQuizDifficulty.EASY, "Quem foi o primeiro rei de Israel?", listOf("Davi", "Saul", "Salomão", "Samuel"), 1, "Samuel o ungiu por ordem de Deus.", "Ele reinou antes de Davi.", "1 Samuel 10:1", "Saul foi ungido por Samuel como rei.", "1 Samuel", 10, 1),
        quizQuestion("easy_025", BibleQuizDifficulty.EASY, "Quem é apresentado como autor do Salmo 23?", listOf("Davi", "Salomão", "Moisés", "Asafe"), 0, "Antes de ser rei, ele cuidava de ovelhas.", "O salmo começa com a imagem do Senhor como pastor.", "Salmos 23:1", "O Salmo 23 é identificado como salmo de Davi.", "Salmos", 23, 1),
        quizQuestion("easy_026", BibleQuizDifficulty.EASY, "Quem subiu numa árvore para ver Jesus passar?", listOf("Nicodemos", "Zaqueu", "Bartimeu", "Jairo"), 1, "Ele era cobrador de impostos e de baixa estatura.", "Subiu numa figueira brava ou sicômoro.", "Lucas 19:1–6", "Zaqueu subiu numa árvore para conseguir ver Jesus.", "Lucas", 19, 1, 6),
        quizQuestion("easy_027", BibleQuizDifficulty.EASY, "Qual discípulo caminhou sobre as águas em direção a Jesus?", listOf("Pedro", "João", "Tiago", "Tomé"), 0, "Ele pediu que Jesus o mandasse ir até ele sobre as águas.", "Seu nome também era Simão.", "Mateus 14:28–31", "Pedro saiu do barco e caminhou sobre as águas até começar a afundar.", "Mateus", 14, 28, 31),
        quizQuestion("easy_028", BibleQuizDifficulty.EASY, "Na multiplicação narrada em João 6, quantos pães havia no início?", listOf("3", "5", "7", "12"), 1, "Também havia dois peixes.", "O número de pães era menor que o de cestos que sobraram.", "João 6:8–13", "Um menino tinha cinco pães de cevada e dois peixes.", "João", 6, 8, 13),
        quizQuestion("easy_029", BibleQuizDifficulty.EASY, "Segundo o anúncio apostólico, Jesus ressuscitou em qual dia?", listOf("No mesmo dia", "No segundo dia", "No terceiro dia", "No sétimo dia"), 2, "Paulo resume esse ensino em 1 Coríntios 15.", "A expressão tradicional é 'ao terceiro dia'.", "1 Coríntios 15:3–4", "Paulo afirma que Cristo ressuscitou ao terceiro dia.", "1 Coríntios", 15, 3, 4),
        quizQuestion("easy_030", BibleQuizDifficulty.EASY, "Em qual cidade Paulo e Silas estavam presos quando houve um terremoto?", listOf("Roma", "Filipos", "Corinto", "Éfeso"), 1, "Lídia também foi encontrada nessa região durante a viagem missionária.", "A prisão e o carcereiro aparecem em Atos 16.", "Atos 16:22–34", "Paulo e Silas estavam presos em Filipos quando um terremoto abriu as portas.", "Atos", 16, 22, 34),
        quizQuestion("easy_031", BibleQuizDifficulty.EASY, "Quem escreveu muitas das cartas do Novo Testamento?", listOf("Paulo", "Pilatos", "Herodes", "Caifás"), 0, "Ele antes perseguia os cristãos.", "Converteu-se após uma experiência no caminho de Damasco.", "Atos 9:1–6", "Paulo tornou-se apóstolo e autor de várias cartas do Novo Testamento.", "Atos", 9, 1, 6),
        quizQuestion("easy_032", BibleQuizDifficulty.EASY, "Qual discípulo disse que precisava ver as marcas de Jesus para crer na ressurreição?", listOf("Tomé", "André", "Filipe", "Mateus"), 0, "Ele não estava com os outros quando Jesus apareceu primeiro.", "Ficou conhecido pela dúvida registrada em João 20.", "João 20:24–29", "Tomé declarou que precisava ver e tocar as marcas antes de crer.", "João", 20, 24, 29),
        quizQuestion("easy_033", BibleQuizDifficulty.EASY, "Quem recebeu as tábuas do testemunho no monte?", listOf("Josué", "Moisés", "Arão", "Calebe"), 1, "Ele ficou quarenta dias no monte com Deus.", "Também liderou o êxodo do Egito.", "Êxodo 31:18", "Deus entregou a Moisés as tábuas de pedra.", "Êxodo", 31, 18),
        quizQuestion("easy_034", BibleQuizDifficulty.EASY, "Qual sinal Deus colocou nas nuvens depois do dilúvio?", listOf("Uma estrela", "Um arco-íris", "Uma coluna de fogo", "Uma pomba"), 1, "Era um sinal da aliança com a terra.", "Aparece no céu depois da chuva.", "Gênesis 9:12–17", "O arco nas nuvens foi dado como sinal da aliança após o dilúvio.", "Gênesis", 9, 12, 17),
        quizQuestion("easy_035", BibleQuizDifficulty.EASY, "Qual cidade teve seus muros derrubados depois que Israel marchou ao redor dela?", listOf("Jericó", "Belém", "Nínive", "Samaria"), 0, "Josué liderava o povo.", "Os sacerdotes tocaram trombetas antes da queda dos muros.", "Josué 6:15–20", "Os muros de Jericó caíram após a obediência às instruções de Deus.", "Josué", 6, 15, 20),
        quizQuestion("easy_036", BibleQuizDifficulty.EASY, "Qual profeta enfrentou os profetas de Baal no monte Carmelo?", listOf("Elias", "Eliseu", "Jeremias", "Oséias"), 0, "Ele orou e fogo caiu sobre o altar.", "Seu sucessor foi Eliseu.", "1 Reis 18:20–39", "Elias confrontou os profetas de Baal e Deus respondeu com fogo.", "1 Reis", 18, 20, 39),
        quizQuestion("easy_037", BibleQuizDifficulty.EASY, "Quem ungiu Davi quando ele ainda era jovem?", listOf("Samuel", "Natã", "Saul", "Jônatas"), 0, "Era profeta e juiz em Israel.", "Também havia ungido Saul anteriormente.", "1 Samuel 16:11–13", "Samuel ungiu Davi no meio de seus irmãos.", "1 Samuel", 16, 11, 13),
        quizQuestion("easy_038", BibleQuizDifficulty.EASY, "Qual livro vem logo depois de Gênesis na Bíblia?", listOf("Levítico", "Êxodo", "Josué", "Salmos"), 1, "É o segundo livro do Pentateuco.", "Narra a saída de Israel do Egito.", "Êxodo 1:1", "Êxodo é o segundo livro da Bíblia, logo depois de Gênesis.", "Êxodo", 1, 1),
        quizQuestion("easy_039", BibleQuizDifficulty.EASY, "Qual é o último livro do Novo Testamento?", listOf("Judas", "Hebreus", "Apocalipse", "Atos"), 2, "É um livro de visões recebidas por João.", "Seu nome também é associado à revelação.", "Apocalipse 1:1", "Apocalipse encerra o cânon do Novo Testamento.", "Apocalipse", 1, 1),
        quizQuestion("easy_040", BibleQuizDifficulty.EASY, "Qual é o primeiro livro do Novo Testamento?", listOf("Marcos", "Lucas", "Mateus", "João"), 2, "É um dos quatro Evangelhos.", "Começa com uma genealogia de Jesus.", "Mateus 1:1", "Mateus aparece como o primeiro livro do Novo Testamento.", "Mateus", 1, 1),

        // MÉDIO 41-80
        quizQuestion("medium_001", BibleQuizDifficulty.MEDIUM, "Qual foi o filho da promessa que nasceu de Abraão e Sara?", listOf("Ismael", "Isaque", "Esaú", "Jacó"), 1, "Seu nascimento ocorreu quando seus pais já eram idosos.", "Era o filho que Sara deu à luz.", "Gênesis 21:1–5", "Isaque nasceu conforme a promessa feita por Deus a Abraão e Sara.", "Gênesis", 21, 1, 5),
        quizQuestion("medium_002", BibleQuizDifficulty.MEDIUM, "Qual novo nome Jacó recebeu depois de lutar durante a noite?", listOf("Judá", "Israel", "Efraim", "José"), 1, "O nome passou a identificar também seus descendentes.", "As doze tribos seriam chamadas por esse nome.", "Gênesis 32:27–28", "Jacó recebeu o nome Israel após o encontro em Peniel.", "Gênesis", 32, 27, 28),
        quizQuestion("medium_003", BibleQuizDifficulty.MEDIUM, "Quantas tribos formaram Israel a partir dos filhos de Jacó?", listOf("10", "11", "12", "13"), 2, "Pense nos filhos de Jacó e na organização do povo.", "É o mesmo número associado aos apóstolos de Jesus.", "Gênesis 49:28", "As famílias dos filhos de Jacó deram origem às doze tribos de Israel.", "Gênesis", 49, 28),
        quizQuestion("medium_004", BibleQuizDifficulty.MEDIUM, "Quem sucedeu Moisés na liderança de Israel?", listOf("Calebe", "Josué", "Arão", "Gideão"), 1, "Ele havia sido um dos doze espias.", "Seu nome dá título ao livro que narra a entrada em Canaã.", "Josué 1:1–6", "Josué foi comissionado por Deus para conduzir o povo após a morte de Moisés.", "Josué", 1, 1, 6),
        quizQuestion("medium_005", BibleQuizDifficulty.MEDIUM, "Qual mulher foi juíza e profetisa em Israel?", listOf("Débora", "Rute", "Miriã", "Abigail"), 0, "Ela chamou Baraque para liderar uma batalha.", "Sua história está em Juízes 4 e 5.", "Juízes 4:4–9", "Débora julgava Israel e transmitiu a Baraque a orientação do Senhor.", "Juízes", 4, 4, 9),
        quizQuestion("medium_006", BibleQuizDifficulty.MEDIUM, "Quem foi a mãe do profeta Samuel?", listOf("Ana", "Mical", "Raquel", "Noemi"), 0, "Ela orou intensamente por um filho no santuário.", "Depois dedicou Samuel ao serviço do Senhor.", "1 Samuel 1:20–28", "Ana recebeu Samuel como resposta à oração e o dedicou ao Senhor.", "1 Samuel", 1, 20, 28),
        quizQuestion("medium_007", BibleQuizDifficulty.MEDIUM, "Quem era o pai de Jônatas, amigo de Davi?", listOf("Samuel", "Saul", "Jessé", "Abner"), 1, "Ele era o rei de Israel naquele período.", "Jônatas era filho do rei que perseguiu Davi.", "1 Samuel 14:49", "Jônatas era filho do rei Saul.", "1 Samuel", 14, 49),
        quizQuestion("medium_008", BibleQuizDifficulty.MEDIUM, "Qual filho de Davi reinou depois dele e ficou conhecido por sua sabedoria?", listOf("Absalão", "Salomão", "Amnom", "Adonias"), 1, "Ele pediu a Deus entendimento para governar.", "Também construiu o templo em Jerusalém.", "1 Reis 3:5–12", "Salomão pediu sabedoria a Deus e reinou após Davi.", "1 Reis", 3, 5, 12),
        quizQuestion("medium_009", BibleQuizDifficulty.MEDIUM, "Qual profeta confrontou Davi depois de seu pecado envolvendo Bate-Seba e Urias?", listOf("Natã", "Elias", "Eliseu", "Isaías"), 0, "Ele contou ao rei uma parábola sobre uma cordeirinha.", "Seu nome aparece em 2 Samuel 12.", "2 Samuel 12:1–7", "Natã confrontou Davi e o levou a reconhecer seu pecado.", "2 Samuel", 12, 1, 7),
        quizQuestion("medium_010", BibleQuizDifficulty.MEDIUM, "Quem sucedeu Elias como profeta e recebeu seu manto?", listOf("Eliseu", "Amós", "Miquéias", "Jeremias"), 0, "Ele pediu porção dobrada do espírito de Elias.", "Seu nome é muito parecido com o de Elias.", "2 Reis 2:9–15", "Eliseu recebeu o manto de Elias e continuou seu ministério profético.", "2 Reis", 2, 9, 15),
        quizQuestion("medium_011", BibleQuizDifficulty.MEDIUM, "Em qual rio Naamã mergulhou para ser curado da lepra?", listOf("Nilo", "Jordão", "Eufrates", "Quisom"), 1, "Eliseu mandou que ele mergulhasse sete vezes.", "É o mesmo rio ligado ao batismo de Jesus.", "2 Reis 5:10–14", "Naamã mergulhou sete vezes no Jordão e foi purificado.", "2 Reis", 5, 10, 14),
        quizQuestion("medium_012", BibleQuizDifficulty.MEDIUM, "Qual rei promoveu reformas depois que o Livro da Lei foi encontrado no templo?", listOf("Acabe", "Josias", "Roboão", "Manassés"), 1, "Ele começou a reinar ainda jovem.", "Hilquias encontrou o Livro da Lei em seu reinado.", "2 Reis 22:8–13", "Josias reagiu com temor ao ouvir o Livro da Lei e promoveu reformas.", "2 Reis", 22, 8, 13),
        quizQuestion("medium_013", BibleQuizDifficulty.MEDIUM, "Quem liderou a reconstrução dos muros de Jerusalém após o exílio?", listOf("Neemias", "Esdras", "Zorobabel", "Mardoqueu"), 0, "Ele servia como copeiro do rei antes de viajar.", "Seu livro relata a reconstrução em meio à oposição.", "Neemias 2:17–20", "Neemias organizou o povo para reconstruir os muros de Jerusalém.", "Neemias", 2, 17, 20),
        quizQuestion("medium_014", BibleQuizDifficulty.MEDIUM, "Quantos amigos vieram inicialmente consolar Jó ao saber de suas aflições?", listOf("2", "3", "4", "7"), 1, "Seus nomes eram Elifaz, Bildade e Zofar.", "Foram três homens que se assentaram com Jó em silêncio.", "Jó 2:11–13", "Três amigos de Jó vieram lamentar e consolá-lo.", "Jó", 2, 11, 13),
        quizQuestion("medium_015", BibleQuizDifficulty.MEDIUM, "Qual é o grande tema repetido ao longo do Salmo 119?", listOf("A construção do templo", "A Palavra e a lei de Deus", "As guerras de Davi", "A genealogia de Israel"), 1, "O salmo usa termos como lei, estatutos, mandamentos e palavra.", "É o salmo mais longo e celebra a instrução divina.", "Salmos 119:9–16", "O Salmo 119 celebra a Palavra, os mandamentos e os caminhos de Deus.", "Salmos", 119, 9, 16),
        quizQuestion("medium_016", BibleQuizDifficulty.MEDIUM, "Em qual livro aparece a expressão 'vaidade de vaidades' logo no início?", listOf("Provérbios", "Eclesiastes", "Jó", "Cânticos"), 1, "O livro reflete sobre o sentido da vida debaixo do sol.", "É atribuído ao Pregador ou Mestre.", "Eclesiastes 1:1–2", "Eclesiastes começa apresentando a transitoriedade das coisas humanas.", "Eclesiastes", 1, 1, 2),
        quizQuestion("medium_017", BibleQuizDifficulty.MEDIUM, "Qual profeta teve a visão de um vale cheio de ossos secos?", listOf("Ezequiel", "Isaías", "Daniel", "Jeremias"), 0, "A visão representa restauração e vida dada por Deus.", "Está no capítulo 37 do livro desse profeta.", "Ezequiel 37:1–10", "Ezequiel viu os ossos receberem vida pela palavra e pelo Espírito de Deus.", "Ezequiel", 37, 1, 10),
        quizQuestion("medium_018", BibleQuizDifficulty.MEDIUM, "Quais três homens foram lançados na fornalha ardente em Daniel 3?", listOf("Sadraque, Mesaque e Abede-Nego", "Daniel, Esdras e Neemias", "Pedro, Tiago e João", "Corá, Datã e Abirão"), 0, "Eles se recusaram a adorar a estátua de ouro.", "Seus nomes babilônicos aparecem juntos várias vezes em Daniel.", "Daniel 3:16–27", "Sadraque, Mesaque e Abede-Nego foram preservados na fornalha.", "Daniel", 3, 16, 27),
        quizQuestion("medium_019", BibleQuizDifficulty.MEDIUM, "Qual profeta se casou com Gômer como parte de uma mensagem simbólica a Israel?", listOf("Oséias", "Joel", "Naum", "Habacuque"), 0, "Seu casamento ilustrava a infidelidade de Israel.", "O nome de Gômer aparece no primeiro capítulo de seu livro.", "Oséias 1:2–3", "Oséias recebeu a ordem de se casar com Gômer como sinal profético.", "Oséias", 1, 2, 3),
        quizQuestion("medium_020", BibleQuizDifficulty.MEDIUM, "Qual profeta anunciou que um governante sairia de Belém?", listOf("Miquéias", "Amós", "Ageu", "Malaquias"), 0, "A profecia é citada no relato dos magos.", "Está em Miquéias 5.", "Miquéias 5:2", "Miquéias apontou Belém como lugar ligado ao futuro governante de Israel.", "Miquéias", 5, 2),
        quizQuestion("medium_021", BibleQuizDifficulty.MEDIUM, "Qual anjo anunciou a Zacarias o nascimento de João Batista?", listOf("Miguel", "Gabriel", "Rafael", "Uriel"), 1, "O mesmo anjo mais tarde foi enviado a Maria.", "Ele se identifica pelo nome em Lucas 1:19.", "Lucas 1:11–20", "Gabriel anunciou a Zacarias que Isabel teria um filho chamado João.", "Lucas", 1, 11, 20),
        quizQuestion("medium_022", BibleQuizDifficulty.MEDIUM, "Quantos dias Jesus jejuou no deserto antes das tentações?", listOf("7", "21", "30", "40"), 3, "O número lembra períodos de prova no Antigo Testamento.", "Foram quarenta dias e quarenta noites.", "Mateus 4:1–2", "Jesus jejuou quarenta dias e quarenta noites.", "Mateus", 4, 1, 2),
        quizQuestion("medium_023", BibleQuizDifficulty.MEDIUM, "Qual foi o primeiro sinal de Jesus registrado no Evangelho de João?", listOf("A cura do paralítico", "A multiplicação dos pães", "Água transformada em vinho", "A ressurreição de Lázaro"), 2, "Aconteceu numa festa de casamento.", "Foi em Caná da Galileia.", "João 2:1–11", "João identifica a transformação da água em vinho como o primeiro sinal de Jesus.", "João", 2, 1, 11),
        quizQuestion("medium_024", BibleQuizDifficulty.MEDIUM, "Quem procurou Jesus de noite para conversar sobre nascer de novo?", listOf("Nicodemos", "Zaqueu", "José de Arimateia", "Gamaliel"), 0, "Era fariseu e líder entre os judeus.", "Seu encontro está em João 3.", "João 3:1–5", "Nicodemos procurou Jesus à noite e ouviu sobre o novo nascimento.", "João", 3, 1, 5),
        quizQuestion("medium_025", BibleQuizDifficulty.MEDIUM, "Em qual capítulo de Lucas aparece a parábola do filho pródigo?", listOf("Lucas 10", "Lucas 12", "Lucas 15", "Lucas 18"), 2, "Ela aparece ao lado das parábolas da ovelha e da moeda perdidas.", "O número do capítulo é 15.", "Lucas 15:11–32", "A parábola do filho pródigo está em Lucas 15.", "Lucas", 15, 11, 32),
        quizQuestion("medium_026", BibleQuizDifficulty.MEDIUM, "Na parábola do bom samaritano, quem finalmente cuidou do homem ferido?", listOf("Um sacerdote", "Um levita", "Um samaritano", "Um soldado"), 2, "Os dois primeiros passaram adiante.", "O personagem que ajuda dá nome à parábola.", "Lucas 10:30–37", "O samaritano se compadeceu, tratou as feridas e providenciou hospedagem.", "Lucas", 10, 30, 37),
        quizQuestion("medium_027", BibleQuizDifficulty.MEDIUM, "Quais discípulos acompanharam Jesus na transfiguração?", listOf("Pedro, Tiago e João", "André, Filipe e Tomé", "Mateus, Simão e Judas", "Pedro, André e Mateus"), 0, "Eram três discípulos do círculo mais próximo.", "Pedro, Tiago e João aparecem juntos em momentos especiais.", "Mateus 17:1–8", "Jesus levou Pedro, Tiago e João ao monte onde foi transfigurado.", "Mateus", 17, 1, 8),
        quizQuestion("medium_028", BibleQuizDifficulty.MEDIUM, "Quais eram as irmãs de Lázaro?", listOf("Maria e Marta", "Ana e Isabel", "Priscila e Lídia", "Raquel e Lia"), 0, "Uma delas recebeu Jesus em casa e a outra se assentou aos seus pés em outro episódio.", "Seus nomes começam com M.", "João 11:1–5", "Lázaro era irmão de Marta e Maria.", "João", 11, 1, 5),
        quizQuestion("medium_029", BibleQuizDifficulty.MEDIUM, "Em qual jardim Jesus orou antes de ser preso?", listOf("Éden", "Getsêmani", "Carmelo", "Cedrom"), 1, "Ficava próximo ao monte das Oliveiras.", "O nome começa com G.", "Mateus 26:36–46", "Jesus foi ao Getsêmani com os discípulos e ali orou antes da prisão.", "Mateus", 26, 36, 46),
        quizQuestion("medium_030", BibleQuizDifficulty.MEDIUM, "Qual era o nome do servo do sumo sacerdote cuja orelha Pedro cortou?", listOf("Malco", "Anás", "Bartimeu", "Cornélio"), 0, "João é o Evangelho que registra seu nome.", "Seu nome começa com M.", "João 18:10", "Pedro feriu Malco, servo do sumo sacerdote.", "João", 18, 10),
        quizQuestion("medium_031", BibleQuizDifficulty.MEDIUM, "Quem foi escolhido para ocupar o lugar de Judas entre os apóstolos?", listOf("Barnabé", "Matias", "Silas", "Marcos"), 1, "A escolha ocorreu antes de Pentecostes.", "Seu nome aparece no fim de Atos 1.", "Atos 1:23–26", "Matias foi contado com os onze apóstolos.", "Atos", 1, 23, 26),
        quizQuestion("medium_032", BibleQuizDifficulty.MEDIUM, "Em qual capítulo de Atos ocorre o derramamento do Espírito Santo em Pentecostes?", listOf("Atos 1", "Atos 2", "Atos 7", "Atos 10"), 1, "Acontece logo após a ascensão e a escolha de Matias.", "É o segundo capítulo de Atos.", "Atos 2:1–4", "Pentecostes é narrado em Atos 2.", "Atos", 2, 1, 4),
        quizQuestion("medium_033", BibleQuizDifficulty.MEDIUM, "Quem é tradicionalmente reconhecido como o primeiro mártir cristão em Atos?", listOf("Estêvão", "Tiago", "Barnabé", "Filipe"), 0, "Ele fez um longo discurso antes de ser apedrejado.", "Saulo estava presente em sua morte.", "Atos 7:54–60", "Estêvão foi apedrejado após testemunhar diante do conselho.", "Atos", 7, 54, 60),
        quizQuestion("medium_034", BibleQuizDifficulty.MEDIUM, "Quem batizou o eunuco etíope no caminho de Gaza?", listOf("Pedro", "Filipe", "Paulo", "Barnabé"), 1, "O Espírito o direcionou ao carro do viajante.", "Ele também pregou em Samaria.", "Atos 8:26–39", "Filipe explicou as Escrituras ao eunuco e depois o batizou.", "Atos", 8, 26, 39),
        quizQuestion("medium_035", BibleQuizDifficulty.MEDIUM, "Para qual cidade Saulo viajava quando teve a experiência que marcou sua conversão?", listOf("Damasco", "Antioquia", "Éfeso", "Roma"), 0, "Ele levava cartas para prender seguidores de Jesus.", "A expressão conhecida é 'caminho de Damasco'.", "Atos 9:1–6", "Saulo estava a caminho de Damasco quando uma luz do céu o cercou.", "Atos", 9, 1, 6),
        quizQuestion("medium_036", BibleQuizDifficulty.MEDIUM, "Em qual cidade Pedro estava quando teve a visão do lençol com animais?", listOf("Jerusalém", "Jope", "Cesareia", "Lida"), 1, "Ele estava hospedado na casa de Simão, curtidor.", "A cidade também é chamada Jope ou Jafa.", "Atos 10:9–16", "Pedro teve a visão em Jope antes de receber os mensageiros de Cornélio.", "Atos", 10, 9, 16),
        quizQuestion("medium_037", BibleQuizDifficulty.MEDIUM, "Quem acompanhou Paulo como parceiro principal no início da primeira viagem missionária?", listOf("Barnabé", "Timóteo", "Lucas", "Apolo"), 0, "A igreja de Antioquia separou dois homens para essa missão.", "Seu nome significa filho da consolação ou encorajamento.", "Atos 13:1–4", "Barnabé e Saulo foram enviados pela igreja de Antioquia.", "Atos", 13, 1, 4),
        quizQuestion("medium_038", BibleQuizDifficulty.MEDIUM, "Qual mulher de Tiatira, vendedora de púrpura, ouviu Paulo em Filipos?", listOf("Lídia", "Priscila", "Dorcas", "Febe"), 0, "Ela abriu sua casa aos missionários.", "Seu nome aparece em Atos 16.", "Atos 16:13–15", "Lídia ouviu a mensagem e foi batizada com sua casa.", "Atos", 16, 13, 15),
        quizQuestion("medium_039", BibleQuizDifficulty.MEDIUM, "O que aconteceu enquanto Paulo e Silas oravam e cantavam na prisão?", listOf("Uma tempestade", "Um terremoto", "Um incêndio", "Uma inundação"), 1, "As portas se abriram e as correntes se soltaram.", "O chão da prisão foi abalado.", "Atos 16:25–26", "Um forte terremoto abalou os alicerces da prisão.", "Atos", 16, 25, 26),
        quizQuestion("medium_040", BibleQuizDifficulty.MEDIUM, "A quem o Evangelho de Lucas é dirigido em sua introdução?", listOf("Teófilo", "Timóteo", "Tito", "Filemom"), 0, "Atos também é dirigido à mesma pessoa.", "O nome significa amigo de Deus.", "Lucas 1:1–4", "Lucas dedica seu relato ordenado a Teófilo.", "Lucas", 1, 1, 4),

        // DIFÍCIL 81-120
        quizQuestion("hard_001", BibleQuizDifficulty.HARD, "Quantos anos Abraão tinha quando Isaque nasceu?", listOf("75", "90", "99", "100"), 3, "A idade é registrada diretamente após o nascimento.", "Ele tinha um século de vida.", "Gênesis 21:5", "Abraão tinha cem anos quando Isaque nasceu.", "Gênesis", 21, 5),
        quizQuestion("hard_002", BibleQuizDifficulty.HARD, "Segundo Gênesis 17:17, qual idade Sara teria quando desse à luz Isaque?", listOf("70", "80", "90", "100"), 2, "Abraão menciona a idade dela ao reagir à promessa.", "Era dez anos mais nova que Abraão na comparação do texto.", "Gênesis 17:17", "Abraão menciona Sara com noventa anos ao ouvir a promessa.", "Gênesis", 17, 17),
        quizQuestion("hard_003", BibleQuizDifficulty.HARD, "Que nome Jacó deu ao lugar onde disse ter visto Deus face a face?", listOf("Betel", "Peniel", "Siquém", "Moriá"), 1, "O nome foi dado após a luta durante a noite.", "Começa com P e está em Gênesis 32.", "Gênesis 32:30", "Jacó chamou o lugar Peniel após seu encontro marcante.", "Gênesis", 32, 30),
        quizQuestion("hard_004", BibleQuizDifficulty.HARD, "Qual foi o filho mais novo de Jacó?", listOf("José", "Benjamim", "Judá", "Dã"), 1, "Raquel morreu durante o parto desse filho.", "Era irmão mais novo de José.", "Gênesis 35:16–18", "Benjamim nasceu por último entre os filhos de Jacó.", "Gênesis", 35, 16, 18),
        quizQuestion("hard_005", BibleQuizDifficulty.HARD, "Qual era o nome do sogro de Moisés mencionado em Êxodo 3:1?", listOf("Jetro", "Labão", "Quis", "Elcana"), 0, "Era sacerdote de Midiã.", "Seu nome começa com J.", "Êxodo 3:1", "Moisés pastoreava o rebanho de Jetro, seu sogro.", "Êxodo", 3, 1),
        quizQuestion("hard_006", BibleQuizDifficulty.HARD, "Quais artesãos foram especialmente chamados para o trabalho do tabernáculo?", listOf("Bezalel e Aoliabe", "Nadabe e Abiú", "Josué e Calebe", "Corá e Datã"), 0, "Um era da tribo de Judá e o outro da tribo de Dã.", "Seus nomes aparecem juntos em Êxodo 31.", "Êxodo 31:1–6", "Bezalel e Aoliabe foram capacitados para as obras do tabernáculo.", "Êxodo", 31, 1, 6),
        quizQuestion("hard_007", BibleQuizDifficulty.HARD, "Quantos homens foram enviados para espiar Canaã em Números 13?", listOf("10", "12", "40", "70"), 1, "Foi escolhido um líder de cada tribo.", "O número corresponde às tribos de Israel.", "Números 13:1–3", "Moisés enviou doze homens, um de cada tribo.", "Números", 13, 1, 3),
        quizQuestion("hard_008", BibleQuizDifficulty.HARD, "Quais dois espias permaneceram confiantes de que Israel poderia entrar na terra prometida?", listOf("Josué e Calebe", "Moisés e Arão", "Corá e Datã", "Eldade e Medade"), 0, "Eles rasgaram as roupas diante da incredulidade do povo.", "Um deles sucederia Moisés.", "Números 14:6–9", "Josué e Calebe confiaram que Deus daria a terra a Israel.", "Números", 14, 6, 9),
        quizQuestion("hard_009", BibleQuizDifficulty.HARD, "Qual animal falou com Balaão no caminho?", listOf("Um cavalo", "Uma jumenta", "Um camelo", "Um cordeiro"), 1, "O animal viu o anjo antes do profeta.", "Era a montaria de Balaão.", "Números 22:27–30", "Deus abriu a boca da jumenta de Balaão.", "Números", 22, 27, 30),
        quizQuestion("hard_010", BibleQuizDifficulty.HARD, "Quantas cidades de refúgio foram separadas para Israel?", listOf("3", "6", "9", "12"), 1, "Metade ficava de um lado do Jordão e metade do outro.", "Três mais três.", "Números 35:6", "Seis cidades foram designadas como cidades de refúgio.", "Números", 35, 6),
        quizQuestion("hard_011", BibleQuizDifficulty.HARD, "Qual juiz canhoto matou o rei Eglom de Moabe?", listOf("Eúde", "Gideão", "Jefté", "Otniel"), 0, "Ele escondeu uma espada no lado direito do corpo.", "Seu nome aparece em Juízes 3.", "Juízes 3:15–22", "Eúde, benjamita canhoto, libertou Israel do domínio de Eglom.", "Juízes", 3, 15, 22),
        quizQuestion("hard_012", BibleQuizDifficulty.HARD, "Com quantos homens Gideão ficou antes da batalha contra os midianitas?", listOf("100", "300", "600", "1000"), 1, "Deus reduziu o exército para que a vitória não fosse atribuída à força humana.", "Foram três centenas.", "Juízes 7:5–7", "Gideão ficou com trezentos homens escolhidos no teste da água.", "Juízes", 7, 5, 7),
        quizQuestion("hard_013", BibleQuizDifficulty.HARD, "De qual tribo era a família de Sansão?", listOf("Judá", "Benjamim", "Dã", "Levi"), 2, "Manoá era de Zorá.", "O texto o chama da família dos danitas.", "Juízes 13:2", "Manoá, pai de Sansão, era da tribo de Dã.", "Juízes", 13, 2),
        quizQuestion("hard_014", BibleQuizDifficulty.HARD, "Qual era o nome da sogra de Rute?", listOf("Noemi", "Orfa", "Mara", "Raabe"), 0, "Rute decidiu acompanhá-la de Moabe até Belém.", "Ela pediu para ser chamada Mara em certo momento.", "Rute 1:16–20", "Noemi era sogra de Rute e retornou com ela a Belém.", "Rute", 1, 16, 20),
        quizQuestion("hard_015", BibleQuizDifficulty.HARD, "No voto de Ana por um filho, o que ela disse que não passaria sobre a cabeça dele?", listOf("Água", "Navalha", "Azeite", "Pó"), 1, "O voto tinha características associadas à consagração.", "Está relacionado ao cabelo de Samuel.", "1 Samuel 1:11", "Ana prometeu dedicar o filho ao Senhor e disse que navalha não passaria sobre sua cabeça.", "1 Samuel", 1, 11),
        quizQuestion("hard_016", BibleQuizDifficulty.HARD, "De quem Davi comprou a eira onde levantou um altar ao Senhor?", listOf("Araúna", "Abner", "Aitofel", "Joabe"), 0, "O episódio ocorre após o recenseamento feito por Davi.", "O nome aparece em 2 Samuel 24.", "2 Samuel 24:18–25", "Davi comprou a eira de Araúna e ali ofereceu sacrifícios.", "2 Samuel", 24, 18, 25),
        quizQuestion("hard_017", BibleQuizDifficulty.HARD, "O que Salomão pediu a Deus quando recebeu a oportunidade de pedir algo?", listOf("Longa vida", "Riqueza", "Um coração entendido para julgar", "Vitória militar"), 2, "Seu pedido estava ligado à responsabilidade de governar.", "Ele pediu discernimento e sabedoria.", "1 Reis 3:5–12", "Salomão pediu entendimento para discernir entre o bem e o mal ao governar.", "1 Reis", 3, 5, 12),
        quizQuestion("hard_018", BibleQuizDifficulty.HARD, "Qual profeta pediu uma porção dobrada do espírito de Elias?", listOf("Eliseu", "Isaías", "Jeremias", "Amós"), 0, "Ele acompanhou Elias até sua partida.", "Foi o sucessor direto de Elias.", "2 Reis 2:9–10", "Eliseu pediu a Elias uma porção dobrada de seu espírito.", "2 Reis", 2, 9, 10),
        quizQuestion("hard_019", BibleQuizDifficulty.HARD, "Qual servo de Eliseu ficou leproso depois de agir com ganância no episódio de Naamã?", listOf("Geazi", "Gehazi", "Naamã", "Joás"), 0, "Ele correu atrás de Naamã para conseguir presentes.", "Seu nome começa com G e aparece em 2 Reis 5.", "2 Reis 5:20–27", "Geazi mentiu para obter presentes e recebeu a lepra de Naamã como juízo.", "2 Reis", 5, 20, 27),
        quizQuestion("hard_020", BibleQuizDifficulty.HARD, "Qual rei ficou leproso depois de tentar queimar incenso no templo, função reservada aos sacerdotes?", listOf("Uzias", "Ezequias", "Josafá", "Acaz"), 0, "Sacerdotes o confrontaram no templo.", "Seu nome também aparece como Azarias em alguns contextos.", "2 Crônicas 26:16–21", "Uzias foi ferido com lepra após agir presunçosamente no templo.", "2 Crônicas", 26, 16, 21),
        quizQuestion("hard_021", BibleQuizDifficulty.HARD, "Quem criou Ester como filha depois da morte dos pais dela?", listOf("Mardoqueu", "Hamã", "Assuero", "Esdras"), 0, "Era parente dela e depois a orientou durante a crise.", "Seu nome aparece repetidamente ao lado de Ester.", "Ester 2:5–7", "Mardoqueu tomou Ester por filha e cuidou dela.", "Ester", 2, 5, 7),
        quizQuestion("hard_022", BibleQuizDifficulty.HARD, "Como Hamã é identificado em Ester 3:1?", listOf("O agagita", "O moabita", "O edomita", "O amonita"), 0, "A identificação aparece logo quando ele é promovido pelo rei.", "O termo começa com A e lembra Agague.", "Ester 3:1", "Hamã é chamado de agagita no texto de Ester.", "Ester", 3, 1),
        quizQuestion("hard_023", BibleQuizDifficulty.HARD, "Quais foram os nomes das três filhas de Jó após sua restauração?", listOf("Jemima, Quézia e Quéren-Hapuque", "Raquel, Lia e Diná", "Marta, Maria e Salomé", "Noemi, Rute e Orfa"), 0, "Os nomes são registrados perto do fim do livro.", "A primeira se chama Jemima.", "Jó 42:13–15", "Jó teve três filhas chamadas Jemima, Quézia e Quéren-Hapuque.", "Jó", 42, 13, 15),
        quizQuestion("hard_024", BibleQuizDifficulty.HARD, "Quantos versículos tem o Salmo 119?", listOf("150", "160", "176", "180"), 2, "O salmo é um grande acróstico organizado pelo alfabeto hebraico.", "O total é vinte e duas seções de oito versículos.", "Salmos 119:176", "O Salmo 119 possui 176 versículos.", "Salmos", 119, 176),
        quizQuestion("hard_025", BibleQuizDifficulty.HARD, "Quem é identificado como autor das palavras de Provérbios 30?", listOf("Agur", "Lemuel", "Asafe", "Etã"), 0, "O nome aparece no primeiro versículo do capítulo.", "Começa com A.", "Provérbios 30:1", "Provérbios 30 apresenta as palavras de Agur, filho de Jaque.", "Provérbios", 30, 1),
        quizQuestion("hard_026", BibleQuizDifficulty.HARD, "Em qual capítulo de Eclesiastes aparece a afirmação de que dois são melhores do que um?", listOf("Capítulo 2", "Capítulo 4", "Capítulo 7", "Capítulo 12"), 1, "O contexto fala de companheirismo e ajuda mútua.", "Está no versículo 9 de um capítulo baixo.", "Eclesiastes 4:9–12", "Eclesiastes 4 destaca o valor da companhia e da cooperação.", "Eclesiastes", 4, 9, 12),
        quizQuestion("hard_027", BibleQuizDifficulty.HARD, "Em que ocasião Isaías teve a visão do Senhor no templo descrita em Isaías 6?", listOf("No ano da morte do rei Uzias", "Na coroação de Ezequias", "Durante o exílio babilônico", "Na reconstrução do templo"), 0, "O capítulo começa situando a visão num acontecimento real.", "Está ligada à morte de Uzias.", "Isaías 6:1–8", "Isaías situa sua visão no ano da morte do rei Uzias.", "Isaías", 6, 1, 8),
        quizQuestion("hard_028", BibleQuizDifficulty.HARD, "O que Jeremias comprou em Anatote enquanto Jerusalém estava sob cerco?", listOf("Uma casa", "Um campo", "Um rebanho", "Uma vinha no Egito"), 1, "A compra serviu como sinal de esperança futura.", "Foi uma propriedade de terra.", "Jeremias 32:6–15", "Jeremias comprou um campo como sinal de que terras voltariam a ser compradas na região.", "Jeremias", 32, 6, 15),
        quizQuestion("hard_029", BibleQuizDifficulty.HARD, "O que Ezequiel recebeu para comer como parte de seu chamado profético?", listOf("Um rolo", "Um cordeiro", "Uma pedra", "Um cálice"), 0, "Estava escrito dos dois lados.", "Era um documento enrolado.", "Ezequiel 2:8–3:3", "Ezequiel comeu o rolo que Deus lhe deu antes de falar ao povo.", "Ezequiel", 3, 1, 3),
        quizQuestion("hard_030", BibleQuizDifficulty.HARD, "Para qual direção estavam abertas as janelas do quarto de Daniel quando ele orava?", listOf("Para o Egito", "Para Jerusalém", "Para a Babilônia", "Para o deserto"), 1, "Mesmo sob decreto, ele manteve seu hábito de oração.", "A direção apontava para a cidade santa.", "Daniel 6:10", "Daniel orava com as janelas abertas na direção de Jerusalém.", "Daniel", 6, 10),
        quizQuestion("hard_031", BibleQuizDifficulty.HARD, "Qual nome simbólico dado a um dos filhos de Oséias significa 'não meu povo'?", listOf("Lo-Ami", "Jezreel", "Lo-Ruama", "Efraim"), 0, "O nome expressava uma mensagem de ruptura da aliança.", "Começa com 'Lo-' e termina com 'Ami'.", "Oséias 1:8–9", "O filho recebeu o nome Lo-Ami, associado à expressão 'não meu povo'.", "Oséias", 1, 8, 9),
        quizQuestion("hard_032", BibleQuizDifficulty.HARD, "Como Amós descreveu sua ocupação quando respondeu ao sacerdote Amazias?", listOf("Pastor e cultivador de sicômoros", "Escriba e sacerdote", "Soldado e ferreiro", "Pescador e cobrador de impostos"), 0, "Ele disse que não era profeta profissional.", "Trabalhava com rebanhos e árvores.", "Amós 7:14–15", "Amós afirmou que cuidava de gado e de sicômoros antes de ser chamado por Deus.", "Amós", 7, 14, 15),
        quizQuestion("hard_033", BibleQuizDifficulty.HARD, "Depois de ser libertado do grande peixe, para qual cidade Jonas finalmente foi pregar?", listOf("Tiro", "Nínive", "Damasco", "Jerusalém"), 1, "Era a cidade para a qual Deus o havia chamado desde o início.", "A capital assíria ocupa o centro da missão de Jonas.", "Jonas 3:1–4", "Jonas obedeceu ao segundo chamado e foi a Nínive.", "Jonas", 3, 1, 4),
        quizQuestion("hard_034", BibleQuizDifficulty.HARD, "De qual divisão sacerdotal Zacarias, pai de João Batista, fazia parte?", listOf("Abias", "Levi", "Zadoque", "Corá"), 0, "Lucas informa o grupo sacerdotal logo na apresentação de Zacarias.", "O nome é Abias.", "Lucas 1:5", "Zacarias pertencia à divisão sacerdotal de Abias.", "Lucas", 1, 5),
        quizQuestion("hard_035", BibleQuizDifficulty.HARD, "Segundo Mateus 1:17, em quantos grupos de quatorze gerações a genealogia é resumida?", listOf("2 grupos", "3 grupos", "4 grupos", "7 grupos"), 1, "O versículo divide a história de Abraão até Cristo em três períodos.", "São três conjuntos.", "Mateus 1:17", "Mateus resume a genealogia em três grupos de quatorze gerações.", "Mateus", 1, 17),
        quizQuestion("hard_036", BibleQuizDifficulty.HARD, "No Sermão do Monte, se alguém obrigasse uma pessoa a caminhar uma milha, quantas Jesus ensinou que ela deveria caminhar?", listOf("Uma", "Duas", "Três", "Sete"), 1, "O ensino vai além da exigência inicial.", "A resposta dobra a primeira distância.", "Mateus 5:41", "Jesus ensinou a ir duas milhas quando alguém obrigasse a caminhar uma.", "Mateus", 5, 41),
        quizQuestion("hard_037", BibleQuizDifficulty.HARD, "Qual dos dois discípulos no caminho de Emaús é identificado pelo nome?", listOf("Cléopas", "Bartimeu", "Nicodemos", "Matias"), 0, "Seu companheiro não é nomeado no texto.", "Seu nome começa com C.", "Lucas 24:13–18", "Lucas identifica um dos discípulos de Emaús como Cléopas.", "Lucas", 24, 13, 18),
        quizQuestion("hard_038", BibleQuizDifficulty.HARD, "Qual sumo sacerdote declarou que era conveniente que um homem morresse pelo povo?", listOf("Caifás", "Anás", "Zacarias", "Abiatar"), 0, "João comenta que ele profetizou sem compreender plenamente o alcance de suas palavras.", "Era sumo sacerdote naquele ano.", "João 11:49–52", "Caifás afirmou que seria conveniente um homem morrer pelo povo.", "João", 11, 49, 52),
        quizQuestion("hard_039", BibleQuizDifficulty.HARD, "Em qual ilha Paulo naufragou a caminho de Roma?", listOf("Creta", "Chipre", "Malta", "Patmos"), 2, "Os habitantes receberam os sobreviventes com hospitalidade.", "A ilha é nomeada logo no início de Atos 28.", "Atos 28:1–2", "Após o naufrágio, os sobreviventes descobriram que a ilha se chamava Malta.", "Atos", 28, 1, 2),
        quizQuestion("hard_040", BibleQuizDifficulty.HARD, "Em qual carta Paulo fala de Onésimo, a quem chama de filho gerado nas prisões?", listOf("Filemom", "Tito", "Gálatas", "Hebreus"), 0, "É uma carta curta dirigida ao senhor de Onésimo.", "O nome do destinatário é também o nome do livro.", "Filemom 1:10–16", "Paulo intercede por Onésimo na carta a Filemom.", "Filemom", 1, 10, 16)
    )

    init {
        require(questions.size == 120) { "O catálogo oficial precisa conter 120 perguntas." }
        BibleQuizDifficulty.entries.forEach { difficulty ->
            require(questions.count { it.difficulty == difficulty } == 40) {
                "Cada dificuldade precisa conter exatamente 40 perguntas."
            }
        }
        require(questions.map { it.id }.distinct().size == questions.size) { "IDs de perguntas não podem se repetir." }
        val invalid = questions.mapNotNull { question ->
            BibleQuizEngine.validate(question).takeIf { !it.valid }?.let { question.id to it.errors }
        }
        require(invalid.isEmpty()) {
            invalid.joinToString(separator = " | ") { (id, errors) -> "$id: ${errors.joinToString()}" }
        }
    }

    fun byDifficulty(difficulty: BibleQuizDifficulty): List<BibleQuizQuestion> =
        questions.filter { it.difficulty == difficulty }

    fun byId(id: String): BibleQuizQuestion? = questions.firstOrNull { it.id == id }
}
