package com.aistudio.micrhema

/**
 * Segunda revisão editorial das 30 matérias históricas do primeiro catálogo.
 * A substituição só acontece quando o texto ainda é exatamente o legado
 * empacotado; uma edição feita pelo ADM continua tendo prioridade.
 */
object BibleNewsLegacyEditorial {
    private val revisedContent = mapOf(
        1 to "Israel havia saído do Egito, mas ficou encurralado entre o mar e o exército de Faraó. O relato de Êxodo descreve uma noite de medo, deslocamento e confiança: Moisés estendeu a mão sobre o mar, as águas se dividiram e o povo atravessou em terra seca. A notícia não é apenas sobre um espetáculo da natureza; é sobre uma comunidade que precisou avançar quando não enxergava saída. O texto bíblico apresenta a travessia como ação de Deus em favor de um povo ameaçado e como um marco de libertação que seria lembrado por gerações.",
        2 to "No monte Carmelo, Elias colocou diante do povo uma escolha entre o Senhor e Baal. O altar foi reconstruído, o sacrifício preparado e água foi derramada repetidas vezes sobre tudo. Depois da oração do profeta, o relato afirma que fogo consumiu a oferta, a lenha, as pedras e a água. O centro da narrativa não é produzir um efeito para entretenimento, mas confrontar uma lealdade dividida. A história termina com o povo reconhecendo quem é Deus, em um episódio intenso que precisa ser lido dentro do confronto religioso e político de 1 Reis 18.",
        3 to "Durante a batalha contra os amorreus, Josué pediu que o sol e a lua permanecessem até que Israel concluísse o confronto. O livro de Josué descreve o dia como extraordinário e ligado à intervenção divina em favor do povo. A matéria deve respeitar exatamente o que o texto afirma sem transformar o relato em uma explicação científica que ele não pretende oferecer. O ponto narrativo é que, no meio de uma guerra decisiva, Josué orou e o autor bíblico entendeu o resultado como uma resposta incomum de Deus naquele momento da história de Israel.",
        4 to "Golias dominava o campo de batalha pelo medo. Davi chegou sem a armadura de um soldado experiente e recusou enfrentar o adversário usando equipamentos com os quais não estava acostumado. Levou a funda que sabia usar e algumas pedras. O primeiro golpe derrubou o guerreiro filisteu e mudou a confiança dos dois exércitos. A narrativa de 1 Samuel não transforma coragem em ausência de risco: Davi sabia que estava diante de um inimigo perigoso. O contraste principal é entre aparência, experiência militar e a convicção com que o jovem decidiu agir.",
        5 to "Durante uma seca severa, Elias foi orientado a permanecer junto ao ribeiro de Querite. Ali havia água, e o relato afirma que corvos levavam pão e carne pela manhã e à tarde. O cenário é de escassez e dependência, não de abundância permanente. Quando o ribeiro secou, o profeta precisou seguir para outro lugar. A história mostra provisão dentro de uma crise, mas também movimento e adaptação quando uma etapa termina. É mais fiel falar do ribeiro e da seca do que transformar automaticamente o lugar em um deserto que o texto não identifica dessa forma.",
        6 to "Moisés estava cuidando do rebanho quando percebeu uma sarça em chamas que não era consumida pelo fogo. Ele se aproximou para entender o que via e, naquele encontro, ouviu seu nome e recebeu uma missão que mudaria sua vida: voltar ao Egito e participar da libertação dos israelitas. O episódio começa com curiosidade, mas rapidamente se torna chamado, resistência, perguntas e responsabilidade. A sarça chama atenção visualmente; o coração da história, porém, é um homem que havia construído outra rotina e precisou encarar novamente o lugar de onde tinha fugido.",
        7 to "Ananias e Safira venderam uma propriedade e decidiram entregar apenas parte do valor, o que em si não é apresentado como o problema central. A acusação de Pedro é que eles fingiram entregar o total e construíram uma imagem de generosidade baseada em mentira. Os dois morreram depois de serem confrontados, e Atos registra grande temor na comunidade. É uma passagem dura e não deve ser usada como ameaça financeira contra membros da igreja. Seu foco narrativo está na hipocrisia, na tentativa de enganar a comunidade e na seriedade atribuída à verdade dentro da igreja nascente.",
        8 to "Sansão acumulou vitórias impressionantes, mas sua história também registra impulsividade, conflitos e decisões que o tornaram vulnerável. Dalila insistiu em descobrir a origem de sua força, e Sansão acabou revelando o segredo ligado ao seu voto. Capturado e cegado pelos filisteus, foi levado ao templo de Dagom. No fim, orou por força mais uma vez e derrubou as colunas do edifício. O relato é trágico: capacidade extraordinária não impediu consequências pessoais. A história funciona melhor quando responsabilidade e escolhas recebem tanto espaço quanto a força física do personagem.",
        9 to "Saul estava cercado pela guerra e sem obter a resposta que desejava. Mesmo tendo anteriormente combatido práticas de consulta aos mortos, procurou uma médium em En-Dor e pediu que Samuel fosse chamado. O texto descreve uma aparição identificada na narrativa como Samuel e registra uma mensagem de juízo para o rei. É uma passagem teologicamente discutida e não precisa ser reduzida à expressão 'fantasma de Samuel'. O ponto claro é a contradição de Saul: desesperado por direção, ele recorreu justamente a uma prática que sabia ser proibida, em vez de encontrar paz para sua crise.",
        10 to "Durante o aniversário de Herodes, a filha de Herodias dançou diante dos convidados e agradou ao governante. Herodes fez uma promessa pública e, orientada pela mãe, a jovem pediu a cabeça de João Batista. O evangelho não precisa que a dança seja descrita como 'sedutora' para explicar a tragédia. Herodes ficou entristecido, mas preferiu sustentar o juramento e sua imagem diante dos convidados. A morte de João nasce de uma combinação de poder, ressentimento, promessa imprudente e medo de recuar publicamente. É uma história de abuso de autoridade e deve ser narrada sem explorar a violência como espetáculo.",
        11 to "O casamento de Oseias é apresentado como parte de uma mensagem profética sobre a infidelidade de Israel. O texto usa linguagem difícil ao falar de Gômer e da condição do povo, e diferentes leitores discutem detalhes de como entender essa ordem. Reduzir a mulher apenas a um rótulo perde o objetivo literário do livro. O relacionamento, a ruptura e a busca por restauração funcionam como imagem de uma aliança ferida. A matéria ganha mais fidelidade quando explica esse simbolismo e evita transformar uma pessoa em objeto de curiosidade, mantendo o foco no chamado profético de Oseias.",
        12 to "Duas mulheres chegaram diante de Salomão afirmando ser mães do mesmo bebê. Sem testemunhas capazes de resolver a disputa, o rei propôs dividir a criança. A ordem extrema não chegou a ser executada: ela provocou reações diferentes e revelou quem estava disposta a abrir mão do próprio direito para preservar a vida do menino. Salomão então entregou a criança à verdadeira mãe. O episódio é uma narrativa sobre discernimento, não sobre um bebê efetivamente cortado ao meio. O choque da proposta só faz sentido porque funciona como teste para tornar visível aquilo que as palavras das duas mulheres não conseguiam provar.",
        13 to "Eúde vivia em um período de dominação moabita sobre Israel. Como mensageiro de um tributo, conseguiu aproximar-se do rei Eglom levando uma arma escondida e, em uma reunião privada, matou o governante antes de escapar. Juízes descreve detalhes corporais fortes, próprios de uma narrativa antiga de guerra e libertação, mas não é necessário transformar o corpo do rei em piada ou chamar atenção para a violência além do que o contexto exige. O episódio faz parte de um ciclo em que opressão, revolta e novos conflitos se repetem, revelando também a instabilidade daquele período.",
        14 to "Balaão seguia viagem quando sua jumenta percebeu um anjo no caminho e tentou desviar três vezes. Sem enxergar o perigo, o profeta reagiu batendo no animal. Então, segundo Números, Deus abriu a boca da jumenta, e a conversa expôs o absurdo da situação antes que os olhos de Balaão fossem abertos para ver o anjo. A curiosidade do animal que fala é real no relato, mas existe uma ironia maior: aquele que era conhecido por enxergar e pronunciar mensagens espirituais estava menos atento do que sua própria montaria. A história confronta cegueira, pressa e obstinação.",
        15 to "Gênesis apresenta a destruição de Sodoma e Gomorra depois de uma longa narrativa de juízo, intercessão e retirada da família de Ló. Mensageiros insistiram para que eles saíssem, e o relato descreve enxofre e fogo sobre as cidades. A esposa de Ló olhou para trás e se tornou uma coluna de sal. É uma passagem severa e não precisa ser ampliada com frases como 'as cidades mais perversas da Terra', que vão além da formulação do texto. A matéria deve manter o foco no aviso, na urgência da fuga e no julgamento descrito por Gênesis, sem transformar sofrimento em entretenimento.",
        16 to "Belsazar oferecia um grande banquete quando mandou usar utensílios retirados do templo de Jerusalém. No meio da festa, apareceram dedos escrevendo na parede do palácio. O rei ficou aterrorizado porque ninguém conseguia explicar a mensagem até Daniel ser chamado. A interpretação anunciou que o governo havia sido pesado, considerado insuficiente e chegaria ao fim. Naquela mesma noite, o reino mudou de mãos. O episódio de Daniel 5 transforma uma cena misteriosa em crítica ao poder: símbolos sagrados foram usados com arrogância, e uma celebração que parecia demonstrar segurança terminou revelando a fragilidade do trono.",
        17 to "Mateus relata que Herodes, ao perceber que os magos não voltariam para informar onde estava a criança, ordenou a morte dos meninos de Belém e arredores dentro da faixa de idade que havia calculado. É uma das passagens mais dolorosas do relato da infância de Jesus e precisa ser apresentada com aviso de violência e luto. O evangelho conecta o episódio à imagem de choro e perda. A matéria não deve usar o sofrimento das famílias como elemento de choque; o centro é o medo de um governante diante da possibilidade de perder poder e as consequências terríveis de uma autoridade usada sem limites.",
        18 to "Sísera, comandante do exército de Jabim, fugiu depois da derrota de suas forças e procurou abrigo na tenda de Jael. Ela o recebeu, ofereceu bebida e o cobriu. Quando ele adormeceu, Jael o matou, cumprindo a reviravolta anunciada anteriormente na narrativa de Juízes. O episódio acontece dentro de uma guerra e contém violência explícita no texto bíblico. Por isso, a matéria deve contextualizar o conflito e evitar tratar a morte como uma curiosidade gráfica. O destaque narrativo é que o homem mais procurado da batalha acreditou ter encontrado um lugar seguro justamente onde sua fuga terminaria.",
        19 to "Êutico era um jovem que ouvia Paulo falar durante uma reunião prolongada em Trôade. Sentado em uma janela do terceiro andar e vencido pelo sono, caiu e foi encontrado sem vida. Paulo desceu, abraçou o rapaz e afirmou que havia vida nele; depois, a comunidade voltou a se reunir e o jovem foi levado vivo, trazendo grande consolo. Atos não o identifica como soldado. A história mistura um acidente real, uma longa noite de ensino e uma recuperação que o autor apresenta como extraordinária. O foco deve estar no jovem e na reação da comunidade, não em ridicularizar alguém por ter dormido.",
        20 to "Jonas recebeu uma missão para ir a Nínive, mas embarcou na direção oposta. Uma tempestade ameaçou o navio, e o profeta acabou lançado ao mar depois de reconhecer sua tentativa de fuga. O texto diz que Deus providenciou um grande peixe, no qual Jonas permaneceu três dias e três noites. De dentro daquele lugar improvável, ele orou reconhecendo sua situação e pedindo ajuda. O peixe não é o final da história, mas a interrupção de uma fuga. Depois, Jonas seria enviado novamente à cidade que não queria visitar. A narrativa combina resistência, disciplina, oração e uma segunda oportunidade de obedecer.",
        21 to "Uma multidão acompanhava Jesus, e a necessidade de alimento se tornou parte da conversa entre ele e os discípulos. André mencionou um menino que tinha cinco pães de cevada e dois peixes, mas reconheceu que aquilo parecia insuficiente. O relato de João afirma que Jesus distribuiu o alimento e a multidão comeu, restando ainda doze cestos. A história não precisa diminuir a cena chamando a oferta apenas de 'lanche'; o contraste é entre recursos pequenos e uma necessidade enorme. O menino aparece brevemente, mas sua disponibilidade se tornou parte de um sinal que o evangelho usa para revelar quem Jesus é.",
        22 to "Depois de resistir à missão, Jonas finalmente entrou em Nínive anunciando que a cidade enfrentaria juízo. O texto registra uma reação coletiva: pessoas creram, proclamaram jejum e a notícia chegou ao rei, que também adotou sinais públicos de arrependimento. O decreto incluiu até os animais no jejum, detalhe incomum da narrativa. O resultado foi que a destruição anunciada não aconteceu naquele momento. Essa parte não deve ser confundida com a história do peixe: aqui o foco é uma cidade que reage a uma advertência e um profeta que depois precisará lidar com a misericórdia concedida aos seus próprios inimigos.",
        23 to "O homem de João 9 havia nascido cego. Jesus fez lodo, colocou-o sobre os olhos dele e o orientou a lavar-se no tanque de Siloé. O homem voltou enxergando, mas o milagre abriu uma investigação: vizinhos discutiram se era a mesma pessoa, líderes religiosos questionaram o que havia acontecido e até seus pais foram chamados. A matéria fica mais completa quando não termina apenas na cura. O capítulo mostra alguém que recebe visão física e, ao mesmo tempo, precisa sustentar seu próprio testemunho diante de pessoas que preferiam discutir o procedimento a reconhecer o que tinha mudado diante delas.",
        24 to "Paulo e Silas estavam presos em Filipos depois de serem espancados e colocados sob vigilância. Perto da meia-noite, oravam e cantavam enquanto outros presos ouviam. Um terremoto abriu portas e soltou correntes, levando o carcereiro a imaginar que todos haviam fugido. Paulo o impediu de se ferir e garantiu que permaneciam ali. A conversa que veio depois alcançou também a casa do carcereiro. O ponto mais forte não é apenas a prisão que se abre, mas a escolha de não usar a liberdade repentina para abandonar alguém em desespero. A narrativa une sofrimento, louvor, responsabilidade e transformação.",
        25 to "Uma mulher sofria havia doze anos com uma hemorragia e, segundo Marcos, havia gastado seus recursos buscando tratamento sem melhorar. No meio de uma multidão, aproximou-se de Jesus acreditando que tocar sua roupa seria suficiente. O sangramento cessou, mas Jesus interrompeu o movimento da multidão e perguntou quem o havia tocado. A mulher então contou o que tinha acontecido. A matéria precisa respeitar o peso de doze anos de doença, desgaste financeiro e isolamento, não apenas o instante da cura. O encontro termina com Jesus dirigindo-se a ela publicamente e reconhecendo sua fé, devolvendo também visibilidade a alguém que tentava passar despercebida.",
        26 to "No deserto, a comunidade de Israel reclamou da falta de alimento e comparou a dificuldade presente com o que havia deixado no Egito. Pela manhã, uma substância fina apareceu sobre o chão e recebeu o nome de maná. Havia instruções sobre quanto recolher, o que guardar e como se preparar para o sábado. O relato não descreve apenas 'pão caindo do céu'; ele cria uma rotina diária de dependência e limites. Quando algumas pessoas tentaram acumular além do orientado, o resultado mostrou que provisão não significava controle ilimitado. A história fala tanto de alimento quanto de aprender confiança no percurso.",
        27 to "Pedro estava preso sob forte vigilância enquanto a igreja orava por ele. Na noite anterior ao julgamento, dormia entre soldados e preso por correntes quando, segundo Atos, um anjo apareceu, as correntes caíram e as portas foram se abrindo no caminho para fora. Pedro inicialmente pensou estar tendo uma visão. Só depois de estar na rua percebeu o que havia acontecido e procurou a casa onde os irmãos estavam reunidos. A matéria fica mais fiel quando inclui a oração da comunidade e evita afirmar detalhes que o texto não dá, como dizer simplesmente que todos os guardas estavam dormindo durante a saída.",
        28 to "Elias e Eliseu caminhavam juntos quando chegaram ao momento da despedida. O relato de 2 Reis diz que um carro e cavalos de fogo os separaram e que Elias subiu ao céu em um redemoinho. É importante manter essa distinção: o texto não afirma que a carruagem de fogo foi o veículo que o levou. Eliseu viu a partida, tomou o manto que havia caído e voltou para continuar a missão. A cena é extraordinária, mas também é uma história de sucessão. Um mestre parte, um discípulo permanece e precisa descobrir como carregar responsabilidade depois de perder sua principal referência.",
        29 to "Na narrativa tradicionalmente transmitida em João 8, líderes religiosos colocam diante de Jesus uma mulher acusada de adultério e perguntam como ele responderia à Lei. Jesus se abaixa, escreve no chão e então diz que aquele que estivesse sem pecado lançasse a primeira pedra. Um a um, os acusadores se retiram. O episódio não termina afirmando que escolhas não importam: Jesus também chama a mulher a uma vida diferente. A matéria deve equilibrar misericórdia, responsabilidade e a crítica à exposição pública usada como armadilha. O foco não precisa ser a multidão com pedras, mas a forma como o julgamento foi redirecionado para a consciência de cada acusador.",
        30 to "Mateus relata a chegada de magos do Oriente que haviam observado uma estrela e procuravam o rei dos judeus. Herodes ficou perturbado, consultou especialistas e tentou usar os visitantes para localizar a criança. A estrela os conduziu até o lugar onde Jesus estava, e o evangelho diz que entraram em uma casa, viram o menino com Maria e ofereceram presentes. O texto não os chama de reis, não informa que eram três e não coloca essa visita em uma manjedoura. A matéria ganha força justamente quando preserva esses detalhes: viajantes estrangeiros reconhecem a criança enquanto o poder local a percebe como ameaça."
    )

    fun enrich(news: BibleNews): BibleNews {
        val revised = revisedContent[news.id] ?: return news
        val original = BibleNewsData.newsList.firstOrNull { it.id == news.id }?.content ?: return news
        return if (news.content.trim() == original.trim()) news.copy(content = revised) else news
    }
}
