package com.aistudio.micrhema

data class BibleNews(
    val id: Int,
    val title: String,
    val content: String,
    val book: String,
    val chapter: Int,
    val verse: Int,
    val imageUrl: String,
    val summary: String = "",
    val category: String = "",
    val intensity: Int = 0,
    val tags: List<String> = emptyList(),
    val contentWarning: String = "",
    val publishedAt: Long = 0L,
    val featured: Boolean = false,
    val storyKey: String = ""
)

object BibleNewsData {
    val newsList = listOf(
    BibleNews(1, "Sem saída diante do mar: a noite em que um povo inteiro precisou avançar", "Um dos maiores milagres já registrados! Moisés estendeu seu cajado e o Mar Vermelho se dividiu em duas paredes de água, permitindo que os israelitas fugissem do exército do Faraó.", "Êxodo", 14, 21, "https://image.pollinations.ai/prompt/red%20sea%20parting%20moses%20israelites%20ancient%20biblical%20hyper%20realistic%20cinematic?width=600&height=400&nologo=true"),
    BibleNews(2, "Doze pedras, água por toda parte e um fogo que ninguém conseguiu explicar", "O profeta Elias desafiou 450 profetas de Baal. Ele encharcou seu altar com água três vezes. Quando orou, fogo caiu do céu e consumiu o sacrifício, a lenha, as pedras e até a água!", "1 Reis", 18, 38, "https://image.pollinations.ai/prompt/fire%20from%20sky%20elijah%20altar%20ancient%20biblical%20hyper%20realistic?width=600&height=400&nologo=true"),
    BibleNews(3, "A oração feita no meio da guerra que mudou o rumo da batalha", "Josué precisava de mais tempo para derrotar os amorreus. Ele orou e o sol parou no meio do céu, atrasando o pôr do sol por quase um dia inteiro!", "Josué", 10, 13, "https://image.pollinations.ai/prompt/sun%20standing%20still%20epic%20battle%20joshua%20ancient%20biblical%20hyper%20realistic?width=600&height=400&nologo=true"),
    BibleNews(4, "Um jovem sem armadura enfrentou o guerreiro que aterrorizava um exército", "Golias aterrorizava o exército de Israel. Um jovem pastor chamado Davi, sem armadura e armado apenas com uma funda e cinco pedras, derrubou o gigante com um único tiro na testa.", "1 Samuel", 17, 49, "https://image.pollinations.ai/prompt/david%20and%20goliath%20giant%20stone%20epic%20battle%20ancient%20biblical%20hyper%20realistic?width=600&height=400&nologo=true"),
    BibleNews(5, "Quando a crise fechou as portas, a provisão chegou por um caminho improvável", "Durante uma grande seca, Deus enviou Elias para um riacho escondido. Lá, corvos traziam pão e carne para o profeta comer, de manhã e de tarde.", "1 Reis", 17, 6, "https://image.pollinations.ai/prompt/ravens%20feeding%20elijah%20desert%20ancient%20biblical%20hyper%20realistic?width=600&height=400&nologo=true"),
    BibleNews(6, "Ele só parou para olhar o fogo — e saiu dali com uma missão impossível", "No deserto, Moisés viu um arbusto em chamas, mas o fogo não o destruía. De dentro do fogo, a voz de Deus o chamou para libertar Seu povo.", "Êxodo", 3, 2, "https://image.pollinations.ai/prompt/burning%20bush%20moses%20desert%20ancient%20biblical%20hyper%20realistic?width=600&height=400&nologo=true"),
    BibleNews(7, "A oferta parecia generosa, mas havia uma mentira escondida por trás dela", "Ananias e Safira venderam uma propriedade e reteram parte do dinheiro. Ao mentirem para Pedro, caíram mortos no mesmo instante. O terror tomou conta da igreja primitiva!", "Atos", 5, 1, "https://image.pollinations.ai/prompt/people%20falling%20dead%20ancient%20temple%20peter%20biblical%20hyper%20realistic?width=600&height=400&nologo=true"),
    BibleNews(8, "Sansão tinha força para vencer inimigos — mas não conseguiu vencer suas próprias escolhas", "Sansão matou mil homens com uma queixada de jumento, mas foi derrotado pela sedução de Dalila. Cego e escravizado, ele derrubou o templo sobre seus inimigos em seu último ato de força.", "Juízes", 16, 28, "https://image.pollinations.ai/prompt/strong%20man%20destroying%20giant%20stone%20pillars%20temple%20biblical%20hyper%20realistic?width=600&height=400&nologo=true"),
    BibleNews(9, "Desesperado por respostas, Saul procurou o caminho que Deus havia proibido", "O Rei Saul, desesperado, procurou uma bruxa em En-Dor para invocar o espírito do profeta Samuel. A profecia que ele ouviu selou sua destruição e a de seus filhos no dia seguinte.", "1 Samuel", 28, 7, "https://image.pollinations.ai/prompt/witch%20summoning%20ghost%20ancient%20cave%20biblical%20hyper%20realistic?width=600&height=400&nologo=true"),
    BibleNews(10, "Uma promessa feita no calor da festa terminou em uma decisão irreversível", "A dança sedutora da filha de Herodias custou a vida do maior dos profetas. João Batista foi decapitado na prisão e sua cabeça entregue durante o banquete de Herodes.", "Marcos", 6, 21, "https://image.pollinations.ai/prompt/ancient%20king%20banquet%20dark%20biblical%20hyper%20realistic?width=600&height=400&nologo=true"),
    BibleNews(11, "O casamento de Oseias virou o retrato vivo de uma nação que abandonou seu Deus", "Deus mandou Oseias se casar com Gômer, uma mulher de prostituições. Uma história de amor incondicional, traição repetida e o resgate chocante que ilustra o amor de Deus.", "Oséias", 1, 2, "https://image.pollinations.ai/prompt/ancient%20prophet%20and%20woman%20biblical%20hyper%20realistic?width=600&height=400&nologo=true"),
    BibleNews(12, "A sentença impossível que revelou quem era a verdadeira mãe", "Duas mulheres disputavam a mesma criança. O rei Salomão ordenou que o bebê fosse cortado ao meio! A reação desesperada da verdadeira mãe revelou a sabedoria divina do rei.", "1 Reis", 3, 16, "https://image.pollinations.ai/prompt/king%20solomon%20on%20throne%20holding%20sword%20baby%20biblical%20hyper%20realistic?width=600&height=400&nologo=true"),
    BibleNews(13, "A espada escondida que atravessou a segurança de um rei intocável", "Eúde, um juiz canhoto, cravou uma espada na barriga do rei Eglom. O rei era tão gordo que a gordura fechou sobre a lâmina, e Eúde fugiu deixando o rei trancado no quarto.", "Juízes", 3, 12, "https://image.pollinations.ai/prompt/ancient%20fat%20king%20palace%20biblical%20hyper%20realistic?width=600&height=400&nologo=true"),
    BibleNews(14, "O animal viu o perigo antes do profeta — e precisou falar para ser ouvido", "Balaão espancou sua jumenta três vezes, até que Deus abriu a boca do animal e ela reclamou! Logo depois, o profeta viu o anjo com a espada desembainhada.", "Números", 22, 28, "https://image.pollinations.ai/prompt/donkey%20on%20path%20angel%20with%20sword%20biblical%20hyper%20realistic?width=600&height=400&nologo=true"),
    BibleNews(15, "A cidade foi avisada, mas a família precisou decidir se ainda valia a pena fugir", "As cidades mais perversas da Terra foram consumidas por enxofre e fogo. A esposa de Ló olhou para trás e virou uma estátua de sal. Uma fuga desesperada pela vida!", "Gênesis", 19, 24, "https://image.pollinations.ai/prompt/ancient%20city%20burning%20fire%20from%20sky%20biblical%20hyper%20realistic?width=600&height=400&nologo=true"),
    BibleNews(16, "A festa parou quando uma mensagem apareceu na parede do palácio", "Durante um banquete profano, os dedos de uma mão humana apareceram e escreveram uma mensagem misteriosa na parede do palácio. O rei Belsazar tremeu e perdeu o reino naquela noite.", "Daniel", 5, 5, "https://image.pollinations.ai/prompt/glowing%20hand%20writing%20on%20ancient%20palace%20wall%20biblical%20hyper%20realistic?width=600&height=400&nologo=true"),
    BibleNews(17, "O medo de perder o poder fez Herodes transformar Belém em luto", "Em fúria e medo de perder o trono, o rei Herodes ordenou o assassinato de todos os meninos de Belém com menos de dois anos. Um choro de desespero ecoou em toda a região.", "Mateus", 2, 16, "https://image.pollinations.ai/prompt/ancient%20soldiers%20bethlehem%20night%20biblical%20hyper%20realistic?width=600&height=400&nologo=true"),
    BibleNews(18, "Ele achou que havia encontrado abrigo — mas a tenda escondia o fim da guerra", "Sísera fugiu e buscou refúgio na tenda de Jael. Ela lhe deu leite, e quando ele dormiu, cravou uma estaca de tenda em sua têmpora, atravessando sua cabeça até o chão!", "Juízes", 4, 17, "https://image.pollinations.ai/prompt/woman%20holding%20tent%20peg%20sleeping%20man%20biblical%20hyper%20realistic?width=600&height=400&nologo=true"),
    BibleNews(19, "Uma janela, uma pregação longa e o susto que interrompeu a reunião", "Êutico estava sentado na janela enquanto o apóstolo Paulo pregava até tarde. Ele pegou no sono, caiu do terceiro andar e morreu! Mas Paulo o abraçou e ele voltou à vida.", "Atos", 20, 9, "https://image.pollinations.ai/prompt/ancient%20house%20window%20night%20man%20falling%20biblical%20hyper%20realistic?width=600&height=400&nologo=true"),
    BibleNews(20, "Jonas tentou fugir da missão — e acabou orando no lugar mais improvável", "Jonas tentou fugir de Deus, foi atirado ao mar numa tempestade e engolido por um grande peixe. Nas entranhas do monstro, ele orou e foi vomitado na praia.", "Jonas", 1, 17, "https://image.pollinations.ai/prompt/man%20inside%20belly%20of%20giant%20whale%20fish%20dark%20biblical%20hyper%20realistic?width=600&height=400&nologo=true"),
    BibleNews(21, "Cinco pães, dois peixes e uma pergunta: o que ainda pode ser entregue?", "Apenas cinco pães e dois peixinhos! Foi tudo que um menino ofereceu, mas nas mãos de Jesus, esse pequeno lanche se multiplicou e saciou mais de cinco mil pessoas, sobrando ainda doze cestos cheios!", "João", 6, 9, "https://image.pollinations.ai/prompt/boy%20giving%20bread%20and%20fish%20to%20jesus%20crowd%20biblical%20hyper%20realistic?width=600&height=400&nologo=true"),
    BibleNews(22, "Nínive recebeu um prazo de quarenta dias — e a cidade inteira precisou reagir", "O profeta Jonas, relutantemente, caminhou pelas ruas da perversa Nínive anunciando destruição em 40 dias. O resultado? Do rei aos animais, todos jejuaram em pano de saco, e Deus poupou a cidade!", "Jonas", 3, 5, "https://image.pollinations.ai/prompt/ancient%20city%20nineveh%20people%20in%20sackcloth%20repenting%20biblical%20hyper%20realistic?width=600&height=400&nologo=true"),
    BibleNews(23, "Ele nasceu sem enxergar; depois do milagre, o problema passou a ser provar a verdade", "Jesus cuspiu no chão, fez lodo com a saliva e aplicou nos olhos de um cego de nascença. Ele o enviou ao tanque de Siloé. O homem lavou o rosto e, milagrosamente, voltou enxergando a luz do mundo!", "João", 9, 7, "https://image.pollinations.ai/prompt/blind%20man%20washing%20eyes%20pool%20of%20siloam%20biblical%20hyper%20realistic?width=600&height=400&nologo=true"),
    BibleNews(24, "O terremoto abriu as portas da prisão — mas a decisão mais importante veio depois", "Paulo e Silas cantavam louvores a Deus à meia-noite, mesmo acorrentados na prisão. De repente, um forte terremoto abalou os alicerces, as portas se abriram e as correntes caíram de todos os presos!", "Atos", 16, 26, "https://image.pollinations.ai/prompt/earthquake%20breaking%20chains%20ancient%20prison%20paul%20silas%20biblical%20hyper%20realistic?width=600&height=400&nologo=true"),
    BibleNews(25, "Doze anos invisível no meio da multidão — até que ela tocou em Jesus", "Sofrendo de hemorragia por doze anos, ela pensou: 'Se eu apenas tocar em Suas vestes, serei curada'. Ao encostar na orla do manto de Jesus no meio da multidão apertada, a cura foi instantânea!", "Marcos", 5, 27, "https://image.pollinations.ai/prompt/woman%20touching%20hem%20of%20garment%20jesus%20crowd%20biblical%20hyper%20realistic?width=600&height=400&nologo=true"),
    BibleNews(26, "A comida chegava pela manhã — mas o povo precisava aprender a confiar dia após dia", "O povo de Israel estava faminto no deserto e reclamou. Na manhã seguinte, Deus fez chover do céu uma substância branca e doce como mel: o Maná. O suprimento diário nunca falhou durante 40 anos!", "Êxodo", 16, 14, "https://image.pollinations.ai/prompt/manna%20falling%20from%20sky%20desert%20israelites%20biblical%20hyper%20realistic?width=600&height=400&nologo=true"),
    BibleNews(27, "Enquanto a igreja orava, Pedro dormia algemado — até que a cela se encheu de luz", "Pedro estava acorrentado entre dois soldados, aguardando a execução. Uma luz brilhou na cela, um anjo o acordou, as correntes caíram e eles passaram pelas guardas sem serem vistos. A porta de ferro se abriu sozinha!", "Atos", 12, 7, "https://image.pollinations.ai/prompt/angel%20freeing%20peter%20from%20prison%20sleeping%20guards%20biblical%20hyper%20realistic?width=600&height=400&nologo=true"),
    BibleNews(28, "Eliseu viu o mestre partir — e recebeu a responsabilidade de continuar a missão", "Elias e Eliseu caminhavam juntos quando de repente, um carro de fogo com cavalos de fogo os separou! Elias subiu aos céus num redemoinho, sem provar a morte, sob os olhos atônitos de seu sucessor.", "2 Reis", 2, 11, "https://image.pollinations.ai/prompt/chariot%20of%20fire%20taking%20elijah%20to%20heaven%20biblical%20hyper%20realistic?width=600&height=400&nologo=true"),
    BibleNews(29, "Todos tinham pedras nas mãos; Jesus fez cada pessoa encarar a própria consciência", "Os escribas e fariseus trouxeram uma mulher pega em adultério, exigindo que fosse apedrejada. Jesus inclinou-se e escreveu na terra, depois disse: 'Quem de vocês estiver sem pecado seja o primeiro a atirar pedra'. Um por um, todos foram embora.", "João", 8, 7, "https://image.pollinations.ai/prompt/jesus%20writing%20on%20ground%20stones%20adulterous%20woman%20biblical%20hyper%20realistic?width=600&height=400&nologo=true"),
    BibleNews(30, "Eles seguiram uma estrela por uma longa viagem — e encontraram um rei em uma casa simples", "Sábios do Oriente viram uma estrela especial no céu e viajaram milhares de quilômetros para encontrar o recém-nascido Rei dos Judeus. A estrela os guiou até a humilde casa onde O adoraram com ouro, incenso e mirra.", "Mateus", 2, 9, "https://image.pollinations.ai/prompt/magi%20following%20bright%20star%20night%20bethlehem%20biblical%20hyper%20realistic?width=600&height=400&nologo=true")
)

}
