insert into public.profile_cosmetics (id,kind,name,description,challenge,challenge_metric,challenge_target,image_ref,active,purchasable,xp_cost,emblem_ids) values
('distintivo_escudo_fe','distintivo','Escudo da Fé','Escudo dourado com cruz e esmalte azul.','Leia 2 capítulos da Bíblia.','bible_chapters',2,'https://raw.githubusercontent.com/bichocutela/Mic-RHEMA-Ia-Studio-Google/891d69e13b5ff394148b1864feac93e090ddecb2/docs/distinctives/escudo_fe.png',true,false,0,'[]'::jsonb),
('distintivo_coroa_promessa','distintivo','Coroa da Promessa','Coroa dourada com rubis, símbolo da promessa.','Leia 2 capítulos da Bíblia.','bible_chapters',2,'https://raw.githubusercontent.com/bichocutela/Mic-RHEMA-Ia-Studio-Google/891d69e13b5ff394148b1864feac93e090ddecb2/docs/distinctives/coroa_promessa.png',true,false,0,'[]'::jsonb),
('distintivo_chama_viva','distintivo','Chama Viva','Chama dourada com coração de âmbar.','Leia 2 capítulos da Bíblia.','bible_chapters',2,'https://raw.githubusercontent.com/bichocutela/Mic-RHEMA-Ia-Studio-Google/891d69e13b5ff394148b1864feac93e090ddecb2/docs/distinctives/chama_viva.png',true,false,0,'[]'::jsonb),
('distintivo_pomba_paz','distintivo','Pomba da Paz','Pomba perolada com ramo de oliveira.','Leia 2 capítulos da Bíblia.','bible_chapters',2,'https://raw.githubusercontent.com/bichocutela/Mic-RHEMA-Ia-Studio-Google/891d69e13b5ff394148b1864feac93e090ddecb2/docs/distinctives/pomba_paz.png',true,false,0,'[]'::jsonb),
('distintivo_leao_juda','distintivo','Leão de Judá','Leão dourado de expressão nobre.','Leia 2 capítulos da Bíblia.','bible_chapters',2,'https://raw.githubusercontent.com/bichocutela/Mic-RHEMA-Ia-Studio-Google/891d69e13b5ff394148b1864feac93e090ddecb2/docs/distinctives/leao_juda.png',true,false,0,'[]'::jsonb),
('distintivo_palavra_viva','distintivo','Palavra Viva','Livro aberto com cruz dourada.','Leia 2 capítulos da Bíblia.','bible_chapters',2,'https://raw.githubusercontent.com/bichocutela/Mic-RHEMA-Ia-Studio-Google/891d69e13b5ff394148b1864feac93e090ddecb2/docs/distinctives/palavra_viva.png',true,false,0,'[]'::jsonb),
('distintivo_estrela_esperanca','distintivo','Estrela da Esperança','Estrela dourada com safira central.','Leia 2 capítulos da Bíblia.','bible_chapters',2,'https://raw.githubusercontent.com/bichocutela/Mic-RHEMA-Ia-Studio-Google/891d69e13b5ff394148b1864feac93e090ddecb2/docs/distinctives/estrela_esperanca.png',true,false,0,'[]'::jsonb),
('distintivo_oliveira_paz','distintivo','Oliveira da Paz','Ramos de oliveira em ouro e jade.','Leia 2 capítulos da Bíblia.','bible_chapters',2,'https://raw.githubusercontent.com/bichocutela/Mic-RHEMA-Ia-Studio-Google/891d69e13b5ff394148b1864feac93e090ddecb2/docs/distinctives/oliveira_paz.png',true,false,0,'[]'::jsonb),
('distintivo_coracao_servo','distintivo','Coração Servo','Coração rubi acolhido por mãos douradas.','Leia 2 capítulos da Bíblia.','bible_chapters',2,'https://raw.githubusercontent.com/bichocutela/Mic-RHEMA-Ia-Studio-Google/891d69e13b5ff394148b1864feac93e090ddecb2/docs/distinctives/coracao_servo.png',true,false,0,'[]'::jsonb),
('distintivo_espada_verdade','distintivo','Espada da Verdade','Espada prateada sobre escudo azul.','Leia 2 capítulos da Bíblia.','bible_chapters',2,'https://raw.githubusercontent.com/bichocutela/Mic-RHEMA-Ia-Studio-Google/891d69e13b5ff394148b1864feac93e090ddecb2/docs/distinctives/espada_verdade.png',true,false,0,'[]'::jsonb),
('distintivo_ancora_esperanca','distintivo','Âncora da Esperança','Âncora em ouro, prata e turquesa.','Leia 2 capítulos da Bíblia.','bible_chapters',2,'https://raw.githubusercontent.com/bichocutela/Mic-RHEMA-Ia-Studio-Google/891d69e13b5ff394148b1864feac93e090ddecb2/docs/distinctives/ancora_esperanca.png',true,false,0,'[]'::jsonb),
('distintivo_calice_alianca','distintivo','Cálice da Aliança','Cálice dourado com detalhes em granada.','Leia 2 capítulos da Bíblia.','bible_chapters',2,'https://raw.githubusercontent.com/bichocutela/Mic-RHEMA-Ia-Studio-Google/891d69e13b5ff394148b1864feac93e090ddecb2/docs/distinctives/calice_alianca.png',true,false,0,'[]'::jsonb),
('distintivo_trombeta_vitoria','distintivo','Trombeta da Vitória','Trombeta dourada com fita carmesim.','Leia 2 capítulos da Bíblia.','bible_chapters',2,'https://raw.githubusercontent.com/bichocutela/Mic-RHEMA-Ia-Studio-Google/891d69e13b5ff394148b1864feac93e090ddecb2/docs/distinctives/trombeta_vitoria.png',true,false,0,'[]'::jsonb),
('distintivo_diamante_graca','distintivo','Diamante da Graça','Diamante violeta coroado em ouro.','Leia 2 capítulos da Bíblia.','bible_chapters',2,'https://raw.githubusercontent.com/bichocutela/Mic-RHEMA-Ia-Studio-Google/891d69e13b5ff394148b1864feac93e090ddecb2/docs/distinctives/diamante_graca.png',true,false,0,'[]'::jsonb)
on conflict (id) do nothing;
