import { useEffect, useMemo, useState } from "react";
import { toast } from "sonner";
import {
  ArrowLeft, BadgeCheck, BookOpen, ChevronDown, ChevronRight, CircleUserRound, FileText,
  Heart, Image, LayoutDashboard, LockKeyhole, Newspaper, Pencil, Plus, RefreshCcw, Save,
  School, Settings, Trash2, Users, Video, X,
} from "lucide-react";
import { listenToCollection, listenToDocument } from "@/lib/firebase";
import {
  createAdminDocumentId, deleteAdminDocument, forceAdminSync, replaceAdminDocument,
  saveAdminDocument, saveAdminSetting,
} from "@/lib/admin-firestore";
import "./AdminParityView.css";

type Session = { uid: string; name: string; isAdmin: boolean; isIbr?: boolean } | null;
type AnyDoc = { id: string; [key: string]: any };
type Section = "dashboard" | "devotionals" | "news" | "media" | "plans" | "ibr" | "discipulado" | "services" | "banners" | "donations" | "members" | "profiles" | "team" | "tabs" | "settings" | "about";

type Chapter = { id: string; title: string; description: string; durationMinutes: number; type: "VIDEO" | "AUDIO" | "TEXT"; videoUrl: string; audioUrl: string; textContent: string; isYoutube?: boolean; youtubeId?: string };
type PlanTheme = { title: string; content: string; verses: string[]; imageUrl: string };

function useAdminCollection(name: string) {
  const [items, setItems] = useState<AnyDoc[]>([]);
  useEffect(() => listenToCollection<AnyDoc>(name, setItems, () => setItems([])), [name]);
  return items;
}

function AdminModal({ title, children, onClose }: { title: string; children: React.ReactNode; onClose: () => void }) {
  return <div className="admin-parity-backdrop" onMouseDown={onClose}><section className="admin-parity-modal" onMouseDown={(event) => event.stopPropagation()}><header><h2>{title}</h2><button onClick={onClose}><X size={20}/></button></header>{children}</section></div>;
}

function Field({ label, value, onChange, type = "text", multiline = false, placeholder }: { label: string; value: string | number; onChange: (value: string) => void; type?: string; multiline?: boolean; placeholder?: string }) {
  return <label className="admin-field"><span>{label}</span>{multiline ? <textarea value={String(value ?? "")} onChange={(event) => onChange(event.target.value)} placeholder={placeholder}/> : <input type={type} value={String(value ?? "")} onChange={(event) => onChange(event.target.value)} placeholder={placeholder}/>}</label>;
}

function Check({ label, checked, onChange }: { label: string; checked: boolean; onChange: (checked: boolean) => void }) {
  return <label className="admin-check"><input type="checkbox" checked={checked} onChange={(event) => onChange(event.target.checked)}/><span>{label}</span></label>;
}

function Metric({ label, value, icon: Icon, onClick }: { label: string; value: number; icon: typeof Users; onClick?: () => void }) {
  return <button className="admin-metric" onClick={onClick} disabled={!onClick}><Icon size={21}/><strong>{value}</strong><span>{label}</span></button>;
}

const modules: Array<{ group: string; items: Array<{ id: Section; title: string; subtitle: string; icon: typeof Users }> }> = [
  { group: "CONTEÚDO", items: [
    { id: "devotionals", title: "Devocionais", subtitle: "Mensagens e reflexões", icon: BookOpen },
    { id: "news", title: "Notícias", subtitle: "Informativos e avisos", icon: Newspaper },
    { id: "media", title: "Mídia", subtitle: "Vídeos, áudios e livros", icon: Video },
    { id: "plans", title: "Planos Bíblicos", subtitle: "Planos e jornadas de leitura", icon: FileText },
    { id: "discipulado", title: "Discipulado", subtitle: "Biblioteca pública em PDF", icon: FileText },
  ] },
  { group: "ENSINO", items: [{ id: "ibr", title: "Instituto Bíblico Rhema", subtitle: "Cursos, módulos e aulas", icon: School }] },
  { group: "IGREJA", items: [
    { id: "services", title: "Cultos", subtitle: "Agenda e programação", icon: Heart },
    { id: "banners", title: "Destaques", subtitle: "Banners e eventos da Home", icon: Image },
    { id: "donations", title: "Dízimos e Ofertas", subtitle: "PIX e QR Code", icon: Heart },
    { id: "team", title: "Equipe", subtitle: "Líderes e ministérios", icon: Users },
  ] },
  { group: "MEMBROS", items: [
    { id: "members", title: "Membros", subtitle: "Aprovações e permissões", icon: Users },
    { id: "profiles", title: "Perfis dos Membros", subtitle: "Dados dos usuários", icon: CircleUserRound },
  ] },
  { group: "SISTEMA", items: [
    { id: "tabs", title: "Abas do Aplicativo", subtitle: "Organização e visibilidade", icon: LayoutDashboard },
    { id: "settings", title: "Configurações", subtitle: "Preferências globais", icon: Settings },
    { id: "about", title: "Sobre", subtitle: "Informações institucionais", icon: BadgeCheck },
  ] },
];

export function AdminParityView({ session }: { session: Session }) {
  const [section, setSection] = useState<Section>("dashboard");
  if (!session?.isAdmin) return <section className="parity-page"><div className="parity-empty"><LockKeyhole size={48}/><h1>Área Administrativa</h1><p>Use o login administrativo para acessar o painel.</p></div></section>;
  return <section className="admin-parity-root">{section !== "dashboard" && <button className="admin-back" onClick={() => setSection("dashboard")}><ArrowLeft size={18}/> Painel</button>}{section === "dashboard" ? <AdminDashboardView onOpen={setSection}/> : <AdminSectionView section={section}/>}</section>;
}

function AdminDashboardView({ onOpen }: { onOpen: (section: Section) => void }) {
  const members = useAdminCollection("acessos_pendentes");
  const videos = useAdminCollection("conteudos_videos");
  const audios = useAdminCollection("conteudos_audios");
  const books = useAdminCollection("conteudos_books");
  const pending = members.filter((item) => item.isApproved !== true && item.status !== "aprovado").length;
  const approved = members.filter((item) => item.isApproved === true || item.status === "aprovado").length;
  const ibr = members.filter((item) => item.isIbr === true).length;
  const [expanded, setExpanded] = useState<Record<string, boolean>>({});
  return <div className="admin-parity-dashboard">
    <header className="admin-parity-hero"><div><p>MIC RHEMA • VISÃO GERAL</p><h1>Painel Administrativo</h1><span>A mesma estrutura de gestão do Android, sincronizada pelo Firebase.</span></div><LayoutDashboard size={34}/></header>
    <h2>Resumo do ministério</h2><div className="admin-metrics"><Metric label="Pendentes" value={pending} icon={Users} onClick={() => onOpen("members")}/><Metric label="Aprovados" value={approved} icon={BadgeCheck}/><Metric label="Alunos IBR" value={ibr} icon={School} onClick={() => onOpen("ibr")}/><Metric label="Itens de mídia" value={videos.length + audios.length + books.length} icon={Video} onClick={() => onOpen("media")}/></div>
    <h2>Ações rápidas</h2><div className="admin-quick-grid"><button onClick={() => onOpen("news")}><Newspaper/>Nova notícia</button><button onClick={() => onOpen("media")}><Video/>Adicionar mídia</button><button onClick={() => onOpen("members")}><Users/>Aprovar membros</button><button onClick={() => onOpen("banners")}><Image/>Novo destaque</button><button onClick={() => onOpen("services")}><Heart/>Atualizar culto</button><button onClick={() => onOpen("ibr")}><School/>Curso IBR</button></div>
    <h2>Módulos administrativos</h2>{modules.map((group) => <section className="admin-module-group" key={group.group}><button className="admin-module-group-title" onClick={() => setExpanded((current) => ({ ...current, [group.group]: !current[group.group] }))}><span>{group.group}</span><ChevronDown className={expanded[group.group] ? "open" : ""}/></button>{expanded[group.group] && <div>{group.items.map(({ id, title, subtitle, icon: Icon }) => <button className="admin-module-row" key={id} onClick={() => onOpen(id)}><Icon size={22}/><span><strong>{title}</strong><small>{subtitle}</small></span><ChevronRight size={19}/></button>)}</div>}</section>)}
  </div>;
}

function AdminSectionView({ section }: { section: Exclude<Section, "dashboard"> }) {
  if (section === "devotionals") return <DevotionalsAdmin/>;
  if (section === "news") return <NewsAdmin/>;
  if (section === "media") return <MediaAdmin/>;
  if (section === "plans") return <PlansAdmin/>;
  if (section === "ibr") return <IbrAdmin/>;
  if (section === "discipulado") return <DiscipuladoAdmin/>;
  if (section === "services") return <ServicesAdmin/>;
  if (section === "banners") return <BannersAdmin/>;
  if (section === "donations") return <DonationsAdmin/>;
  if (section === "members" || section === "profiles") return <MembersAdmin profilesOnly={section === "profiles"}/>;
  if (section === "team") return <TeamAdmin/>;
  if (section === "tabs") return <TabsAdmin/>;
  if (section === "settings") return <GlobalSettingsAdmin/>;
  return <AboutAdmin/>;
}

function SectionHeader({ title, subtitle, onAdd, addLabel = "Novo" }: { title: string; subtitle: string; onAdd?: () => void; addLabel?: string }) {
  return <header className="admin-section-header"><div><h1>{title}</h1><p>{subtitle}</p></div>{onAdd && <button onClick={onAdd}><Plus size={18}/>{addLabel}</button>}</header>;
}

function DevotionalsAdmin() {
  const items = useAdminCollection("devocionais").sort((a,b) => Number(b.timestamp || 0) - Number(a.timestamp || 0));
  const [editing, setEditing] = useState<AnyDoc | null>(null);
  return <div className="admin-section"><SectionHeader title="Devocionais" subtitle="Alimente a fé da igreja com uma nova palavra para cada dia." onAdd={() => setEditing({ id: createAdminDocumentId("devocionais") })} addLabel="Novo devocional"/><AdminRows items={items} title={(item) => item.title || "Devocional"} subtitle={(item) => [item.date, item.verseReference].filter(Boolean).join(" · ")} onEdit={setEditing} onDelete={(item) => remove("devocionais", item)}/>{editing && <DevotionalForm item={editing} onClose={() => setEditing(null)}/>}</div>;
}
function DevotionalForm({ item, onClose }: { item: AnyDoc; onClose: () => void }) {
  const [draft, setDraft] = useState({ title: item.title || "", date: item.date || "", verse: item.verse || "", verseReference: item.verseReference || "", content: item.content || "", mediaUrl: item.mediaUrl || "" });
  const save = async () => { if (!draft.title.trim()) return toast.error("Informe o título."); await saveAdminDocument("devocionais", item.id, { ...draft, isApproved: true, approved: true, timestamp: Number(item.timestamp || Date.now()) }); toast.success("Devocional salvo."); onClose(); };
  return <AdminModal title="Devocional" onClose={onClose}><div className="admin-form"><Field label="Título" value={draft.title} onChange={(v) => setDraft({...draft,title:v})}/><Field label="Data" value={draft.date} onChange={(v) => setDraft({...draft,date:v})} placeholder="dd/mm/aaaa"/><Field label="Versículo" value={draft.verse} onChange={(v) => setDraft({...draft,verse:v})} multiline/><Field label="Referência" value={draft.verseReference} onChange={(v) => setDraft({...draft,verseReference:v})}/><Field label="Conteúdo" value={draft.content} onChange={(v) => setDraft({...draft,content:v})} multiline/><Field label="Mídia (URL opcional)" value={draft.mediaUrl} onChange={(v) => setDraft({...draft,mediaUrl:v})}/><SaveButton onClick={save}/></div></AdminModal>;
}

function NewsAdmin() {
  const items = useAdminCollection("bible_news").sort((a,b) => Number(b.publishedAt || 0) - Number(a.publishedAt || 0));
  const [editing, setEditing] = useState<AnyDoc | null>(null);
  return <div className="admin-section"><SectionHeader title="Gerenciar Avisos / Notícias" subtitle="Título, referência bíblica, categoria e destaque da Home." onAdd={() => setEditing({ id: createAdminDocumentId("bible_news") })}/><AdminRows items={items} title={(item) => item.title || "Notícia"} subtitle={(item) => `${item.book || ""}${item.chapter ? ` ${item.chapter}` : ""}${item.verse ? `:${item.verse}` : ""} · ${item.category || "Para refletir"}`} onEdit={setEditing} onDelete={(item) => remove("bible_news", item)}/>{editing && <NewsForm item={editing} onClose={() => setEditing(null)}/>}</div>;
}
function NewsForm({ item, onClose }: { item: AnyDoc; onClose: () => void }) {
  const [d,setD] = useState({ title:item.title||"", summary:item.summary||"", storyKey:item.storyKey||"", content:item.content||"", book:item.book||"", chapter:String(item.chapter||""), verse:String(item.verse||""), imageUrl:item.imageUrl||"", category:item.category||"Para refletir", intensity:String(item.intensity||1), tags:Array.isArray(item.tags)?item.tags.join(", "):"", contentWarning:item.contentWarning||"", featured:item.featured===true });
  const save = async () => { if(!d.title.trim()) return toast.error("Informe o título."); await saveAdminDocument("bible_news",item.id,{title:d.title.trim(),summary:d.summary.trim(),storyKey:d.storyKey.trim(),content:d.content,book:d.book,chapter:Number(d.chapter)||0,verse:Number(d.verse)||0,imageUrl:d.imageUrl,category:d.category||"Para refletir",intensity:Math.max(1,Math.min(4,Number(d.intensity)||1)),tags:d.tags.split(",").map(v=>v.trim()).filter(Boolean),contentWarning:d.contentWarning.trim(),featured:d.featured,publishedAt:Number(item.publishedAt||Date.now())}); toast.success("Notícia salva.");onClose(); };
  return <AdminModal title="Notícia Bíblica" onClose={onClose}><div className="admin-form"><Field label="Título" value={d.title} onChange={v=>setD({...d,title:v})}/><Field label="Resumo" value={d.summary} onChange={v=>setD({...d,summary:v})} multiline/><Field label="Chave da história" value={d.storyKey} onChange={v=>setD({...d,storyKey:v})}/><div className="admin-form-grid"><Field label="Livro" value={d.book} onChange={v=>setD({...d,book:v})}/><Field label="Capítulo" value={d.chapter} onChange={v=>setD({...d,chapter:v})}/><Field label="Versículo" value={d.verse} onChange={v=>setD({...d,verse:v})}/></div><Field label="URL da imagem" value={d.imageUrl} onChange={v=>setD({...d,imageUrl:v})}/><div className="admin-form-grid"><Field label="Categoria" value={d.category} onChange={v=>setD({...d,category:v})}/><Field label="Intensidade (1–4)" value={d.intensity} onChange={v=>setD({...d,intensity:v})}/></div><Field label="Tags" value={d.tags} onChange={v=>setD({...d,tags:v})}/><Field label="Aviso de conteúdo" value={d.contentWarning} onChange={v=>setD({...d,contentWarning:v})}/><Check label="Destacar na Home" checked={d.featured} onChange={v=>setD({...d,featured:v})}/><Field label="Conteúdo" value={d.content} onChange={v=>setD({...d,content:v})} multiline/><SaveButton onClick={save}/></div></AdminModal>;
}

function MediaAdmin() {
  const videos=useAdminCollection("conteudos_videos").map(i=>({...i,_type:"video"})); const audios=useAdminCollection("conteudos_audios").map(i=>({...i,_type:"audio"})); const books=useAdminCollection("conteudos_books").map(i=>({...i,_type:"book"}));
  const items=[...videos,...audios,...books]; const [editing,setEditing]=useState<AnyDoc|null>(null);
  return <div className="admin-section"><SectionHeader title="Mídia" subtitle="Áudios, vídeos e livros compartilhados com o aplicativo." onAdd={()=>setEditing({id:createAdminDocumentId("conteudos_videos"),_type:"video"})} addLabel="Adicionar mídia"/><AdminRows items={items} title={i=>i.title||"Mídia"} subtitle={i=>`${i._type==="video"?"Vídeo":i._type==="audio"?"Áudio":"Livro"} · ${i.artist||i.author||i.description||""}`} onEdit={setEditing} onDelete={i=>remove(mediaCollection(i._type),i)}/>{editing&&<MediaForm item={editing} onClose={()=>setEditing(null)}/>}</div>;
}
function mediaCollection(type:string){return type==="audio"?"conteudos_audios":type==="book"?"conteudos_books":"conteudos_videos";}
function MediaForm({item,onClose}:{item:AnyDoc;onClose:()=>void}){
  const [d,setD]=useState({type:item._type||"video",title:item.title||"",description:item.description||"",url:item.videoUrl||item.audioUrl||item.bookUrl||item.mediaUrl||"",cover:item.thumbnailUrl||item.coverUrl||item.imageUrl||"",credit:item.artist||item.author||""});
  const save=async()=>{if(!d.title.trim()||!d.url.trim())return toast.error("Informe título e URL.");const collectionName=mediaCollection(d.type);const payload:any={title:d.title,description:d.description,imageUrl:d.cover,isApproved:true,approved:true,publishedAt:Number(item.publishedAt||Date.now())};if(d.type==="video")Object.assign(payload,{videoUrl:d.url,thumbnailUrl:d.cover});else if(d.type==="audio")Object.assign(payload,{audioUrl:d.url,coverUrl:d.cover,artist:d.credit});else Object.assign(payload,{bookUrl:d.url,coverUrl:d.cover,author:d.credit});if(item._type&&item._type!==d.type)await deleteAdminDocument(mediaCollection(item._type),item.id);await saveAdminDocument(collectionName,item.id,payload);toast.success("Mídia salva.");onClose();};
  return <AdminModal title="Mídia" onClose={onClose}><div className="admin-form"><label className="admin-field"><span>Tipo</span><select value={d.type} onChange={e=>setD({...d,type:e.target.value})}><option value="video">Vídeo</option><option value="audio">Áudio</option><option value="book">Livro / PDF</option></select></label><Field label="Título" value={d.title} onChange={v=>setD({...d,title:v})}/><Field label="Descrição" value={d.description} onChange={v=>setD({...d,description:v})} multiline/><Field label="URL do conteúdo" value={d.url} onChange={v=>setD({...d,url:v})}/><Field label="URL da capa" value={d.cover} onChange={v=>setD({...d,cover:v})}/><Field label="Autor / artista" value={d.credit} onChange={v=>setD({...d,credit:v})}/><SaveButton onClick={save}/></div></AdminModal>;
}

function ServicesAdmin(){const items=useAdminCollection("cultos_agenda");const[editing,setEditing]=useState<AnyDoc|null>(null);return <div className="admin-section"><SectionHeader title="Gerenciar Cultos" subtitle="Agenda e programação exibidas para todos." onAdd={()=>setEditing({id:createAdminDocumentId("cultos_agenda")})} addLabel="Novo culto"/><AdminRows items={items} title={i=>i.title||"Culto"} subtitle={i=>[i.date||i.day,i.time].filter(Boolean).join(" · ")} onEdit={setEditing} onDelete={i=>remove("cultos_agenda",i)}/>{editing&&<ServiceForm item={editing} onClose={()=>setEditing(null)}/>}</div>}
function ServiceForm({item,onClose}:{item:AnyDoc;onClose:()=>void}){const[d,setD]=useState({title:item.title||"",date:item.date||"",day:item.day||"",time:item.time||"",description:item.description||"",mediaUrl:item.mediaUrl||""});const save=async()=>{if(!d.title.trim())return toast.error("Informe o título.");let day=d.day,dayShort="";if(/^\d{4}-\d{2}-\d{2}$/.test(d.date)){const date=new Date(`${d.date}T12:00:00`);day=["Domingo","Segunda-feira","Terça-feira","Quarta-feira","Quinta-feira","Sexta-feira","Sábado"][date.getDay()];dayShort=day.slice(0,3).toUpperCase();}else dayShort=day.slice(0,3).toUpperCase();await saveAdminDocument("cultos_agenda",item.id,{...d,day,dayShort,isApproved:true,type:"culto"});toast.success("Culto salvo.");onClose();};return <AdminModal title="Culto" onClose={onClose}><div className="admin-form"><Field label="Título" value={d.title} onChange={v=>setD({...d,title:v})}/><Field label="Data (yyyy-mm-dd, opcional)" value={d.date} onChange={v=>setD({...d,date:v})} type="date"/><Field label="Dia da semana (se recorrente)" value={d.day} onChange={v=>setD({...d,day:v})}/><Field label="Horário" value={d.time} onChange={v=>setD({...d,time:v})} type="time"/><Field label="Descrição" value={d.description} onChange={v=>setD({...d,description:v})} multiline/><Field label="Vídeo/URL" value={d.mediaUrl} onChange={v=>setD({...d,mediaUrl:v})}/><SaveButton onClick={save}/></div></AdminModal>}

function BannersAdmin(){const items=useAdminCollection("carousel_items");const settings=useAdminDocument("settings","app");const[editing,setEditing]=useState<AnyDoc|null>(null);const[seconds,setSeconds]=useState(6);useEffect(()=>setSeconds(Math.max(3,Math.min(12,Number(settings?.bannerRotationSeconds)||6))),[settings]);return <div className="admin-section"><SectionHeader title="Gerenciar Banners (Destaques)" subtitle="Imagens 16:9, eventos e velocidade do carrossel." onAdd={()=>setEditing({id:createAdminDocumentId("carousel_items")})} addLabel="Novo destaque"/><div className="admin-global-card"><label>Velocidade: <strong>{seconds}s</strong><input type="range" min="3" max="12" value={seconds} onChange={e=>setSeconds(Number(e.target.value))}/></label><button onClick={async()=>{await saveAdminSetting("app",{bannerRotationSeconds:seconds});toast.success("Velocidade sincronizada.")}}>Salvar velocidade</button></div><AdminRows items={items} title={i=>i.title||i.tag||"Destaque"} subtitle={i=>i.eventDate?`Evento: ${i.eventDate}`:"Banner permanente"} onEdit={setEditing} onDelete={i=>remove("carousel_items",i)}/>{editing&&<BannerForm item={editing} onClose={()=>setEditing(null)}/>}</div>}
function BannerForm({item,onClose}:{item:AnyDoc;onClose:()=>void}){const[d,setD]=useState({imageUrl:item.imageUrl||"",title:item.title||"",description:item.description||"",tag:item.tag||"",eventDate:item.eventDate||"",eventInfo:item.eventInfo||""});const save=async()=>{if(!d.imageUrl.trim())return toast.error("Informe a imagem.");await saveAdminDocument("carousel_items",item.id,d);toast.success("Destaque salvo.");onClose();};return <AdminModal title="Destaque da Home" onClose={onClose}><div className="admin-form"><Field label="URL da imagem 16:9" value={d.imageUrl} onChange={v=>setD({...d,imageUrl:v})}/><Field label="Título" value={d.title} onChange={v=>setD({...d,title:v})}/><Field label="Descrição" value={d.description} onChange={v=>setD({...d,description:v})}/><Field label="Tag" value={d.tag} onChange={v=>setD({...d,tag:v})}/><Field label="Data do evento (opcional)" value={d.eventDate} onChange={v=>setD({...d,eventDate:v})} type="date"/><Field label="Informações do evento" value={d.eventInfo} onChange={v=>setD({...d,eventInfo:v})} multiline/><SaveButton onClick={save}/></div></AdminModal>}

function DonationsAdmin(){const current=useAdminDocument("settings","donations");const[pix,setPix]=useState("");const[qr,setQr]=useState("");useEffect(()=>{setPix(current?.pixKey||"");setQr(current?.qrCodeUrl||"")},[current]);return <div className="admin-section"><SectionHeader title="Dízimos e Ofertas" subtitle="Configure a chave PIX e o QR Code exibidos no app."/><div className="admin-form standalone"><Field label="Chave PIX" value={pix} onChange={setPix}/><Field label="URL do QR Code" value={qr} onChange={setQr}/>{qr&&<img className="admin-qr-preview" src={qr} alt="QR Code"/>}<SaveButton onClick={async()=>{await saveAdminSetting("donations",{pixKey:pix,qrCodeUrl:qr});toast.success("Doações sincronizadas.")}}/></div></div>}

function TeamAdmin(){const items=useAdminCollection("equipe").sort((a,b)=>Number(a.order||0)-Number(b.order||0));const[editing,setEditing]=useState<AnyDoc|null>(null);return <div className="admin-section"><SectionHeader title="Gerenciar Equipe" subtitle="Líderes, pastores e ministérios." onAdd={()=>setEditing({id:createAdminDocumentId("equipe")})} addLabel="Adicionar membro"/><AdminRows items={items} title={i=>i.name||"Membro"} subtitle={i=>[i.role,i.category].filter(Boolean).join(" · ")} onEdit={setEditing} onDelete={i=>remove("equipe",i)}/>{editing&&<TeamForm item={editing} onClose={()=>setEditing(null)}/>}</div>}
function TeamForm({item,onClose}:{item:AnyDoc;onClose:()=>void}){const[d,setD]=useState({name:item.name||"",role:item.role||"",category:item.category||"Geral",imageUrl:item.imageUrl||"",order:String(item.order||0)});const save=async()=>{if(!d.name.trim())return toast.error("Informe o nome.");await saveAdminDocument("equipe",item.id,{name:d.name,role:d.role,category:d.category,imageUrl:d.imageUrl,order:Number(d.order)||0});toast.success("Equipe atualizada.");onClose();};return <AdminModal title="Membro da Equipe" onClose={onClose}><div className="admin-form"><Field label="Nome" value={d.name} onChange={v=>setD({...d,name:v})}/><Field label="Cargo / Função" value={d.role} onChange={v=>setD({...d,role:v})}/><Field label="Categoria" value={d.category} onChange={v=>setD({...d,category:v})}/><Field label="URL da foto" value={d.imageUrl} onChange={v=>setD({...d,imageUrl:v})}/><Field label="Ordem" value={d.order} onChange={v=>setD({...d,order:v})} type="number"/><SaveButton onClick={save}/></div></AdminModal>}

function DiscipuladoAdmin(){const items=useAdminCollection("discipulado_pdfs").sort((a,b)=>Number(a.order||0)-Number(b.order||0));const[editing,setEditing]=useState<AnyDoc|null>(null);return <div className="admin-section"><SectionHeader title="Estudos de Discipulado" subtitle="PDFs públicos disponíveis no Android e PWA." onAdd={()=>setEditing({id:createAdminDocumentId("discipulado_pdfs")})} addLabel="Novo PDF"/><AdminRows items={items} title={i=>i.title||"Estudo"} subtitle={i=>`${i.category||"Estudos bíblicos"}${i.isPublished===false?" · Oculto":""}`} onEdit={setEditing} onDelete={i=>remove("discipulado_pdfs",i)}/>{editing&&<DiscipuladoForm item={editing} onClose={()=>setEditing(null)}/>}</div>}
function DiscipuladoForm({item,onClose}:{item:AnyDoc;onClose:()=>void}){const[d,setD]=useState({title:item.title||"",subtitle:item.subtitle||"",description:item.description||"",category:item.category||"Estudos bíblicos",fileUrl:item.fileUrl||"",storagePath:item.storagePath||"",order:String(item.order||0),isPublished:item.isPublished!==false});const save=async()=>{if(!d.title.trim()||!d.fileUrl.trim())return toast.error("Informe título e URL do PDF.");await saveAdminDocument("discipulado_pdfs",item.id,{...d,order:Number(d.order)||0});toast.success("Estudo sincronizado.");onClose();};return <AdminModal title="Estudo em PDF" onClose={onClose}><div className="admin-form"><Field label="Título" value={d.title} onChange={v=>setD({...d,title:v})}/><Field label="Subtítulo" value={d.subtitle} onChange={v=>setD({...d,subtitle:v})}/><Field label="Categoria" value={d.category} onChange={v=>setD({...d,category:v})}/><Field label="Descrição" value={d.description} onChange={v=>setD({...d,description:v})} multiline/><Field label="URL do PDF" value={d.fileUrl} onChange={v=>setD({...d,fileUrl:v})}/><Field label="Storage path" value={d.storagePath} onChange={v=>setD({...d,storagePath:v})}/><Field label="Ordem" value={d.order} onChange={v=>setD({...d,order:v})}/><Check label="Publicado" checked={d.isPublished} onChange={v=>setD({...d,isPublished:v})}/><SaveButton onClick={save}/></div></AdminModal>}

function MembersAdmin({profilesOnly}:{profilesOnly:boolean}){const items=useAdminCollection("acessos_pendentes").sort((a,b)=>Number(b.createdAt||0)-Number(a.createdAt||0));const[editing,setEditing]=useState<AnyDoc|null>(null);const visible=profilesOnly?items.filter(i=>i.isApproved===true||i.status==="aprovado"):items;return <div className="admin-section"><SectionHeader title={profilesOnly?"Perfis dos Membros":"Membros"} subtitle={profilesOnly?"Dados e informações dos usuários aprovados.":"Aprovações e permissões de acesso."}/><AdminRows items={visible} title={i=>i.name||"Membro"} subtitle={i=>`${i.phone||"Sem telefone"} · ${i.isApproved||i.status==="aprovado"?"Aprovado":"Pendente"}${i.isIbr?" · IBR":""}`} onEdit={setEditing}/>{editing&&<MemberForm item={editing} onClose={()=>setEditing(null)}/>}</div>}
function MemberForm({item,onClose}:{item:AnyDoc;onClose:()=>void}){const[d,setD]=useState({name:item.name||"",phone:item.phone||"",email:item.email||"",address:item.address||"",birthDate:item.birthDate||"",isApproved:item.isApproved===true||item.status==="aprovado",isIbr:item.isIbr===true,isAdmin:item.isAdmin===true});const save=async()=>{if(!d.name.trim())return toast.error("Informe o nome.");await saveAdminDocument("acessos_pendentes",item.id,{...d,status:d.isApproved?"aprovado":"pendente",firebaseUid:item.firebaseUid||"",avatarId:item.avatarId||"davi",unlockedBadgeIds:item.unlockedBadgeIds||["caminhante"],equippedBadgeId:item.equippedBadgeId||"caminhante",badgeActivityIds:item.badgeActivityIds||{}});toast.success("Membro sincronizado.");onClose();};return <AdminModal title="Membro" onClose={onClose}><div className="admin-form"><Field label="Nome" value={d.name} onChange={v=>setD({...d,name:v})}/><Field label="Telefone" value={d.phone} onChange={v=>setD({...d,phone:v})}/><Field label="E-mail" value={d.email} onChange={v=>setD({...d,email:v})}/><Field label="Endereço" value={d.address} onChange={v=>setD({...d,address:v})}/><Field label="Nascimento" value={d.birthDate} onChange={v=>setD({...d,birthDate:v})}/><Check label="Acesso aprovado" checked={d.isApproved} onChange={v=>setD({...d,isApproved:v})}/><Check label="Aluno IBR" checked={d.isIbr} onChange={v=>setD({...d,isIbr:v})}/><Check label="Administrador" checked={d.isAdmin} onChange={v=>setD({...d,isAdmin:v})}/><SaveButton onClick={save}/></div></AdminModal>}

function PlansAdmin(){const items=useAdminCollection("bible_plans");const[editing,setEditing]=useState<AnyDoc|null>(null);return <div className="admin-section"><SectionHeader title="Gerenciar Planos" subtitle="Categorias e temas bíblicos sincronizados." onAdd={()=>setEditing({id:createAdminDocumentId("bible_plans"),themes:[]})}/><AdminRows items={items} title={i=>i.name||i.id} subtitle={i=>`${Array.isArray(i.themes)?i.themes.length:0} tema(s)`} onEdit={setEditing} onDelete={i=>remove("bible_plans",i)}/>{editing&&<PlanForm item={editing} onClose={()=>setEditing(null)}/>}</div>}
function PlanForm({item,onClose}:{item:AnyDoc;onClose:()=>void}){const[name,setName]=useState(item.name||item.id||"");const[themes,setThemes]=useState<PlanTheme[]>(Array.isArray(item.themes)?item.themes:[]);const add=()=>setThemes([...themes,{title:"",content:"",verses:[""],imageUrl:""}]);const save=async()=>{if(!name.trim())return toast.error("Informe o nome do plano.");await replaceAdminDocument("bible_plans",item.id,{name:name.trim(),color:item.color||0,themes});toast.success("Plano salvo.");onClose();};return <AdminModal title="Plano Bíblico" onClose={onClose}><div className="admin-form"><Field label="Nome do plano" value={name} onChange={setName}/><div className="admin-nested-header"><strong>Temas</strong><button onClick={add}><Plus size={16}/>Adicionar tema</button></div>{themes.map((theme,index)=><div className="admin-nested" key={index}><button className="nested-delete" onClick={()=>setThemes(themes.filter((_,i)=>i!==index))}><Trash2 size={16}/></button><Field label="Título" value={theme.title} onChange={v=>setThemes(themes.map((t,i)=>i===index?{...t,title:v}:t))}/><Field label="Versículo/ref." value={(theme.verses||[]).join(", ")} onChange={v=>setThemes(themes.map((t,i)=>i===index?{...t,verses:v.split(",").map(x=>x.trim()).filter(Boolean)}:t))}/><Field label="Imagem" value={theme.imageUrl||""} onChange={v=>setThemes(themes.map((t,i)=>i===index?{...t,imageUrl:v}:t))}/><Field label="Conteúdo" value={theme.content||""} onChange={v=>setThemes(themes.map((t,i)=>i===index?{...t,content:v}:t))} multiline/></div>)}<SaveButton onClick={save}/></div></AdminModal>}

function IbrAdmin(){const items=useAdminCollection("ibr_courses");const[editing,setEditing]=useState<AnyDoc|null>(null);return <div className="admin-section"><SectionHeader title="Instituto Bíblico Rhema" subtitle="Cursos, módulos, aulas e conteúdo." onAdd={()=>setEditing({id:createAdminDocumentId("ibr_courses"),chapters:[]})} addLabel="Novo curso"/><AdminRows items={items} title={i=>i.title||"Curso IBR"} subtitle={i=>`${i.theme||"IBR"} · ${Array.isArray(i.chapters)?i.chapters.length:0} aula(s)`} onEdit={setEditing} onDelete={i=>remove("ibr_courses",i)}/>{editing&&<IbrForm item={editing} onClose={()=>setEditing(null)}/>}</div>}
function IbrForm({item,onClose}:{item:AnyDoc;onClose:()=>void}){const[d,setD]=useState({title:item.title||"",theme:item.theme||"",description:item.description||"",imageUrl:item.imageUrl||""});const[chapters,setChapters]=useState<Chapter[]>(Array.isArray(item.chapters)?item.chapters:[]);const add=()=>setChapters([...chapters,{id:crypto.randomUUID(),title:"",description:"",durationMinutes:0,type:"VIDEO",videoUrl:"",audioUrl:"",textContent:""}]);const patchChapter=(index:number,patch:Partial<Chapter>)=>setChapters(chapters.map((c,i)=>i===index?{...c,...patch}:c));const save=async()=>{if(!d.title.trim())return toast.error("Informe o título do curso.");await replaceAdminDocument("ibr_courses",item.id,{...d,chapters});toast.success("Curso IBR sincronizado.");onClose();};return <AdminModal title="Curso IBR" onClose={onClose}><div className="admin-form"><Field label="Título" value={d.title} onChange={v=>setD({...d,title:v})}/><Field label="Tema" value={d.theme} onChange={v=>setD({...d,theme:v})}/><Field label="Descrição" value={d.description} onChange={v=>setD({...d,description:v})} multiline/><Field label="Imagem" value={d.imageUrl} onChange={v=>setD({...d,imageUrl:v})}/><div className="admin-nested-header"><strong>Aulas</strong><button onClick={add}><Plus size={16}/>Adicionar aula</button></div>{chapters.map((c,index)=><div className="admin-nested" key={c.id||index}><button className="nested-delete" onClick={()=>setChapters(chapters.filter((_,i)=>i!==index))}><Trash2 size={16}/></button><Field label="Título da aula" value={c.title||""} onChange={v=>patchChapter(index,{title:v})}/><Field label="Descrição" value={c.description||""} onChange={v=>patchChapter(index,{description:v})}/><div className="admin-form-grid"><label className="admin-field"><span>Tipo</span><select value={c.type||"VIDEO"} onChange={e=>patchChapter(index,{type:e.target.value as Chapter["type"]})}><option value="VIDEO">Vídeo</option><option value="AUDIO">Áudio</option><option value="TEXT">Texto</option></select></label><Field label="Duração (min)" value={c.durationMinutes||0} onChange={v=>patchChapter(index,{durationMinutes:Number(v)||0})} type="number"/></div>{c.type==="VIDEO"&&<Field label="URL do vídeo" value={c.videoUrl||""} onChange={v=>patchChapter(index,{videoUrl:v})}/>} {c.type==="AUDIO"&&<Field label="URL do áudio" value={c.audioUrl||""} onChange={v=>patchChapter(index,{audioUrl:v})}/>} {c.type==="TEXT"&&<Field label="Conteúdo da aula" value={c.textContent||""} onChange={v=>patchChapter(index,{textContent:v})} multiline/>}</div>)}<SaveButton onClick={save}/></div></AdminModal>}

function TabsAdmin(){const items=useAdminCollection("app_tabs").sort((a,b)=>Number(a.order||0)-Number(b.order||0));const[editing,setEditing]=useState<AnyDoc|null>(null);return <div className="admin-section"><SectionHeader title="Abas do Aplicativo" subtitle="Ordem, visibilidade e posição dos atalhos."/><AdminRows items={items} title={i=>i.title||i.name||i.id} subtitle={i=>`Ordem ${i.order??0} · ${i.isVisible===false?"Oculta":"Visível"}${i.showInBottomBar?" · Barra inferior":""}`} onEdit={setEditing}/>{editing&&<TabForm item={editing} onClose={()=>setEditing(null)}/>}</div>}
function TabForm({item,onClose}:{item:AnyDoc;onClose:()=>void}){const[d,setD]=useState({title:item.title||item.name||"",order:String(item.order||0),isVisible:item.isVisible!==false,showInBottomBar:item.showInBottomBar===true});const save=async()=>{await saveAdminDocument("app_tabs",item.id,{...item,...d,order:Number(d.order)||0});toast.success("Aba sincronizada.");onClose();};return <AdminModal title="Aba do Aplicativo" onClose={onClose}><div className="admin-form"><Field label="Título" value={d.title} onChange={v=>setD({...d,title:v})}/><Field label="Ordem" value={d.order} onChange={v=>setD({...d,order:v})} type="number"/><Check label="Visível" checked={d.isVisible} onChange={v=>setD({...d,isVisible:v})}/><Check label="Mostrar na barra inferior" checked={d.showInBottomBar} onChange={v=>setD({...d,showInBottomBar:v})}/><SaveButton onClick={save}/></div></AdminModal>}

function GlobalSettingsAdmin(){const current=useAdminDocument("settings","app");const[notifications,setNotifications]=useState(true);const[donations,setDonations]=useState(true);const[seconds,setSeconds]=useState(6);useEffect(()=>{setNotifications(current?.notificationsEnabled!==false);setDonations(current?.showDonationsTab!==false);setSeconds(Number(current?.bannerRotationSeconds)||6)},[current]);return <div className="admin-section"><SectionHeader title="Configurações Adicionais" subtitle="Opções sincronizadas para todos os aparelhos."/><div className="admin-form standalone"><Check label="Habilitar notificações" checked={notifications} onChange={setNotifications}/><Check label="Mostrar aba de Doações" checked={donations} onChange={setDonations}/><Field label="Rotação dos banners (segundos)" value={seconds} onChange={v=>setSeconds(Math.max(3,Math.min(12,Number(v)||6)))} type="number"/><SaveButton onClick={async()=>{await saveAdminSetting("app",{notificationsEnabled:notifications,showDonationsTab:donations,bannerRotationSeconds:seconds});toast.success("Configurações sincronizadas.")}}/><button className="admin-secondary" onClick={async()=>{await forceAdminSync();toast.success("Sinal de sincronização enviado.")}}><RefreshCcw size={18}/>Sincronizar Banco de Dados</button></div></div>}

function AboutAdmin(){const current=useAdminDocument("settings","about");const[d,setD]=useState({pastorName:"",pastorTitle:"",missionTagline:"",rhemaMeaning:""});useEffect(()=>setD({pastorName:current?.pastorName||"",pastorTitle:current?.pastorTitle||"",missionTagline:current?.missionTagline||"",rhemaMeaning:current?.rhemaMeaning||""}),[current]);return <div className="admin-section"><SectionHeader title="Gerenciar Sobre" subtitle="Informações institucionais exibidas no aplicativo."/><div className="admin-form standalone"><Field label="Nome do Pastor" value={d.pastorName} onChange={v=>setD({...d,pastorName:v})}/><Field label="Título do Pastor" value={d.pastorTitle} onChange={v=>setD({...d,pastorTitle:v})}/><Field label="Missão" value={d.missionTagline} onChange={v=>setD({...d,missionTagline:v})}/><Field label="Significado de Rhema" value={d.rhemaMeaning} onChange={v=>setD({...d,rhemaMeaning:v})} multiline/><SaveButton onClick={async()=>{await saveAdminSetting("about",d);toast.success("Informações salvas.")}}/></div></div>}

function useAdminDocument(collectionName:string,id:string){const[item,setItem]=useState<AnyDoc|null>(null);useEffect(()=>listenToDocument<AnyDoc>(collectionName,id,setItem,()=>setItem(null)),[collectionName,id]);return item;}

function AdminRows({items,title,subtitle,onEdit,onDelete}:{items:AnyDoc[];title:(item:AnyDoc)=>string;subtitle:(item:AnyDoc)=>string;onEdit:(item:AnyDoc)=>void;onDelete?:(item:AnyDoc)=>void}){return !items.length?<p className="admin-empty">Nenhum registro encontrado.</p>:<div className="admin-rows">{items.map(item=><article key={item.id}><div><strong>{title(item)}</strong><small>{subtitle(item)}</small></div><button onClick={()=>onEdit(item)} aria-label="Editar"><Pencil size={18}/></button>{onDelete&&<button className="delete" onClick={()=>onDelete(item)} aria-label="Excluir"><Trash2 size={18}/></button>}</article>)}</div>}
function SaveButton({onClick}:{onClick:()=>void|Promise<void>}){const[busy,setBusy]=useState(false);return <button className="admin-save" disabled={busy} onClick={async()=>{setBusy(true);try{await onClick()}catch(error){toast.error(error instanceof Error?error.message:"Não foi possível salvar.")}finally{setBusy(false)}}}><Save size={18}/>{busy?"Salvando…":"Salvar"}</button>}
async function remove(collectionName:string,item:AnyDoc){if(!window.confirm(`Excluir “${item.title||item.name||item.id}”?`))return;try{await deleteAdminDocument(collectionName,item.id);toast.success("Registro excluído.")}catch(error){toast.error(error instanceof Error?error.message:"Não foi possível excluir.")}}
