import { useEffect, useMemo, useRef, useState } from "react";
import { BookOpen, ChevronLeft, ChevronRight, Heart, Search, X } from "lucide-react";
import { toast } from "sonner";
import { bibleBookChapters, bibleBooks } from "@/lib/pwa-data";
import { normalizeSearch } from "@/lib/parity-utils";
import "./AndroidParityViews.css";

type Verse={verse:number;text:string};
type SearchResult={book:string;chapter:number;verse:number;text:string};
type Translation="ARA"|"NVI"|"NTLH"|"NAA"|"ARC"|"ACF"|"NVT"|"NBV"|"KJA";
const translations:Translation[]=["ARA","NVI","NTLH","NAA","ARC","ACF","NVT","NBV","KJA"];
const aliases:Record<string,string[]>={"Cânticos":["Cantares","Cantares de Salomão"],"Apocalipse":["Revelação"],"Filemom":["Filemon"]};

function editDistance(a:string,b:string){const dp=Array.from({length:a.length+1},()=>Array(b.length+1).fill(0));for(let i=0;i<=a.length;i++)dp[i][0]=i;for(let j=0;j<=b.length;j++)dp[0][j]=j;for(let i=1;i<=a.length;i++)for(let j=1;j<=b.length;j++)dp[i][j]=Math.min(dp[i-1][j]+1,dp[i][j-1]+1,dp[i-1][j-1]+(a[i-1]===b[j-1]?0:1));return dp[a.length][b.length]}
function keys(book:string){const all=[book,...(aliases[book]||[])].flatMap(v=>{const n=normalizeSearch(v);return[n,n.replace(/ /g,""),n.replace(/^[123] /,"")]});return [...new Set(all.filter(Boolean))]}
function searchBooks(raw:string){const q=normalizeSearch(raw);if(!q)return bibleBooks;const compact=q.replace(/ /g,"");const direct=bibleBooks.map((book,index)=>{let score=0;for(const key of keys(book)){if(key===q||key===compact)score=Math.max(score,100);else if(key.startsWith(q)||key.startsWith(compact))score=Math.max(score,80);else if(key.includes(q)||key.includes(compact))score=Math.max(score,60)}return{book,index,score}}).filter(x=>x.score>0).sort((a,b)=>b.score-a.score||a.index-b.index);if(direct.length)return direct.map(x=>x.book);if(q.length<3)return[];const max=q.length<=4?1:q.length<=7?2:q.length<=11?3:4;return bibleBooks.map((book,index)=>({book,index,distance:Math.min(...keys(book).map(key=>editDistance(compact,key.replace(/ /g,"")) ))})).filter(x=>x.distance<=max).sort((a,b)=>a.distance-b.distance||a.index-b.index).slice(0,6).map(x=>x.book)}
function cleanHtml(value:string){const doc=new DOMParser().parseFromString(value,"text/html");return(doc.body.textContent||"").replace(/\s+/g," ").trim()}
function parseReference(query:string){const normalized=normalizeSearch(query);const compact=normalized.replace(/ /g,"");const candidates=bibleBooks.map(book=>{const norm=normalizeSearch(book);const c=norm.replace(/ /g,"");if(normalized.startsWith(`${norm} `))return{book,rest:normalized.slice(norm.length).trim(),len:norm.length};if(compact.startsWith(c))return{book,rest:compact.slice(c.length),len:c.length};return null}).filter(Boolean).sort((a,b)=>b!.len-a!.len) as {book:string;rest:string;len:number}[];const first=candidates[0];if(!first)return null;const match=first.rest.match(/^(\d+)(?:[: ]?(\d+))?$/);if(!match)return null;const chapter=Number(match[1]);const verse=match[2]?Number(match[2]):undefined;const max=bibleBookChapters[first.book as keyof typeof bibleBookChapters];return chapter>=1&&chapter<=max?{book:first.book,chapter,verse}:null}
async function fetchChapter(book:string,chapter:number,translation:Translation,signal?:AbortSignal){const id=bibleBooks.indexOf(book)+1;const response=await fetch(`https://bolls.life/get-text/${translation}/${id}/${chapter}/`,{signal,headers:{Accept:"application/json"}});if(!response.ok)throw new Error("Não foi possível carregar este capítulo.");const payload=await response.json() as Array<{verse?:unknown;text?:unknown}>;return payload.map(item=>({verse:Number(item.verse),text:cleanHtml(String(item.text||""))})).filter(v=>v.verse>0&&v.text) as Verse[]}
async function deepSearch(query:string,translation:Translation,signal?:AbortSignal):Promise<SearchResult[]>{const ref=parseReference(query);if(ref){const verses=await fetchChapter(ref.book,ref.chapter,translation,signal);const list=ref.verse?verses.filter(v=>v.verse===ref.verse):verses.slice(0,1);return list.map(v=>({book:ref.book,chapter:ref.chapter,verse:v.verse,text:v.text}))}const response=await fetch(`https://bolls.life/v2/find/${translation}?search=${encodeURIComponent(query)}&limit=24&page=1`,{signal,headers:{Accept:"application/json"}});if(!response.ok)throw new Error("Pesquisa bíblica indisponível.");const payload=await response.json() as {results?:Array<{book?:number;chapter?:number;verse?:number;text?:string}>};return(payload.results||[]).map(item=>({book:bibleBooks[Number(item.book)-1],chapter:Number(item.chapter),verse:Number(item.verse),text:cleanHtml(item.text||"")})).filter(item=>item.book&&item.chapter>0&&item.verse>0)}

export function BibleParityViewV2(){
  const target=useMemo(()=>{try{return JSON.parse(localStorage.getItem("micrhema:pwa:bible-target")||"null") as {book?:string;chapter?:number;verse?:number}|null}catch{return null}},[]);
  const[translation,setTranslation]=useState<Translation>(()=>(localStorage.getItem("micrhema:pwa:bible-version") as Translation)||"ARA");const[book,setBook]=useState(target?.book&&bibleBooks.includes(target.book)?target.book:"Gênesis");const[chapter,setChapter]=useState(target?.chapter||1);const[focusVerse,setFocusVerse]=useState(target?.verse||0);const[verses,setVerses]=useState<Verse[]>([]);const[loading,setLoading]=useState(true);const[error,setError]=useState("");const[bookQuery,setBookQuery]=useState("");const[deepQuery,setDeepQuery]=useState("");const[deepResults,setDeepResults]=useState<SearchResult[]>([]);const[deepBusy,setDeepBusy]=useState(false);const[deepError,setDeepError]=useState("");const verseRefs=useRef<Record<number,HTMLParagraphElement|null>>({});
  const max=bibleBookChapters[book as keyof typeof bibleBookChapters];
  useEffect(()=>{localStorage.setItem("micrhema:pwa:bible-version",translation);const c=new AbortController();setLoading(true);setError("");fetchChapter(book,chapter,translation,c.signal).then(setVerses).catch(e=>{if(e?.name!=="AbortError")setError(e.message||"Falha ao carregar.")}).finally(()=>{if(!c.signal.aborted)setLoading(false)});localStorage.setItem("micrhema:pwa:last-reading",JSON.stringify({book,chapter,translation}));return()=>c.abort()},[book,chapter,translation]);
  useEffect(()=>{if(focusVerse&&verses.length){window.setTimeout(()=>verseRefs.current[focusVerse]?.scrollIntoView({behavior:"smooth",block:"center"}),100);localStorage.removeItem("micrhema:pwa:bible-target")}},[focusVerse,verses]);
  useEffect(()=>{if(deepQuery.trim().length<2){setDeepResults([]);setDeepError("");return}const c=new AbortController();const timer=window.setTimeout(()=>{setDeepBusy(true);setDeepError("");deepSearch(deepQuery.trim(),translation,c.signal).then(setDeepResults).catch(e=>{if(e?.name!=="AbortError")setDeepError("Não foi possível pesquisar agora. Verifique sua conexão.")}).finally(()=>{if(!c.signal.aborted)setDeepBusy(false)})},450);return()=>{clearTimeout(timer);c.abort()}},[deepQuery,translation]);
  const next=(direction:-1|1)=>{let index=bibleBooks.indexOf(book);if(direction<0){if(chapter>1)setChapter(chapter-1);else if(index>0){index--;const previous=bibleBooks[index];setBook(previous);setChapter(bibleBookChapters[previous as keyof typeof bibleBookChapters])}}else{if(chapter<max)setChapter(chapter+1);else if(index<bibleBooks.length-1){index++;setBook(bibleBooks[index]);setChapter(1)}}setFocusVerse(0);window.scrollTo({top:0})};
  const openResult=(r:SearchResult)=>{setBook(r.book);setChapter(r.chapter);setFocusVerse(r.verse);setDeepQuery("");setDeepResults([])};
  const visibleBooks=useMemo(()=>searchBooks(bookQuery),[bookQuery]);
  return <section className="parity-page bible-v2"><div className="parity-title"><div><p>BÍBLIA SAGRADA</p><h1>{book} {chapter}</h1><span>Escolha um livro e um capítulo.</span></div><select value={translation} onChange={e=>setTranslation(e.target.value as Translation)}>{translations.map(v=><option key={v}>{v}</option>)}</select></div>
    <label style={{display:"flex",alignItems:"center",gap:8,border:"1px solid #aaa",borderRadius:18,padding:"0 12px",minHeight:48}}><Search size={18}/><input value={bookQuery} onChange={e=>setBookQuery(e.target.value)} placeholder="Pesquisar livro — ex.: genesis, joao" style={{flex:1,border:0,outline:0,background:"transparent",color:"inherit"}}/>{bookQuery&&<button onClick={()=>setBookQuery("")} style={{border:0,background:"transparent",color:"inherit"}}><X size={18}/></button>}</label>{bookQuery&&visibleBooks[0]&&<small style={{display:"block",margin:"7px 2px 12px"}}>Entendi: <b>{visibleBooks[0]}</b></small>}
    <div className="book-rail">{visibleBooks.map(name=><button key={name} className={book===name?"chosen":""} onClick={()=>{setBook(name);setChapter(1);setBookQuery("");setFocusVerse(0)}}>{name}</button>)}</div><div className="chapter-strip">{Array.from({length:max},(_,i)=>i+1).map(n=><button key={n} className={chapter===n?"current":""} onClick={()=>{setChapter(n);setFocusVerse(0)}}>{n}</button>)}</div>
    <article className="parity-reader"><p style={{fontWeight:800}}>{book.toUpperCase()} · CAPÍTULO {chapter}</p>{loading&&<p>Carregando os versículos…</p>}{error&&<p>{error}</p>}{!loading&&!error&&verses.map(v=><p key={v.verse} ref={el=>{verseRefs.current[v.verse]=el}} style={focusVerse===v.verse?{outline:"2px solid var(--pwa-primary,#8a6500)",borderRadius:10,padding:8}:undefined}><sup>{v.verse}</sup>{v.text}</p>)}</article>
    <div className="parity-bottom-actions"><button onClick={()=>next(-1)} disabled={book===bibleBooks[0]&&chapter===1}><ChevronLeft size={17}/>Anterior</button><button onClick={()=>{const key=`${translation}:${book}:${chapter}`;const current=JSON.parse(localStorage.getItem("micrhema:pwa:bible-favorites")||"[]") as string[];const exists=current.includes(key);localStorage.setItem("micrhema:pwa:bible-favorites",JSON.stringify(exists?current.filter(x=>x!==key):[...current,key]));toast.success(exists?"Removido dos favoritos.":"Capítulo salvo.")}}><Heart size={17}/>Salvar</button><button onClick={()=>next(1)} disabled={book===bibleBooks.at(-1)&&chapter===max}>Próximo<ChevronRight size={17}/></button></div>
    <section style={{marginTop:26,borderTop:"1px solid rgba(127,127,127,.25)",paddingTop:18}}><h2>Pesquisa profunda</h2><p style={{opacity:.75}}>Pesquise nomes, situações, temas, referências ou parte de um versículo. A pesquisa usa a versão bíblica selecionada.</p><label style={{display:"flex",alignItems:"center",gap:8,border:"1px solid #aaa",borderRadius:18,padding:"0 12px",minHeight:50}}><Search size={18}/><input value={deepQuery} onChange={e=>setDeepQuery(e.target.value)} placeholder="Ex.: curado, ansiedade, Davi, João 3:16" style={{flex:1,border:0,outline:0,background:"transparent",color:"inherit"}}/>{deepQuery&&<button onClick={()=>setDeepQuery("")} style={{border:0,background:"transparent",color:"inherit"}}><X size={18}/></button>}</label>{deepBusy&&<p>Procurando referências…</p>}{deepError&&<p style={{color:"#b91c1c"}}>{deepError}</p>}{!deepBusy&&!deepError&&deepQuery.trim().length>=2&&!deepResults.length&&<p>Nenhuma referência encontrada nessa busca.</p>}<div className="android-list-cards" style={{marginTop:10}}>{deepResults.map(r=><button key={`${r.book}-${r.chapter}-${r.verse}`} onClick={()=>openResult(r)}><span><BookOpen size={18}/></span><div><strong>{r.book} {r.chapter}:{r.verse}</strong><small>{r.text}</small></div><ChevronRight size={18}/></button>)}</div></section>
  </section>;
}
