import { useEffect, useMemo, useRef, useState } from "react";
import { BookOpen, ChevronLeft, ChevronRight, Heart, Search, X } from "lucide-react";
import { toast } from "sonner";
import { bibleBookChapters, bibleBooks } from "@/lib/pwa-data";
import { recordPwaActivity } from "@/lib/badge-activity";
import { normalizeSearch } from "@/lib/parity-utils";
import "./AndroidParityViews.css";

type Verse={verse:number;text:string};
type SearchResult={book:string;chapter:number;verse:number;text:string};
type Translation="ARA"|"NVI"|"NTLH"|"NAA"|"ARC"|"ACF"|"NVT"|"NBV"|"KJA";
const translations:Translation[]=["ARA","NVI","NTLH","NAA","ARC","ACF","NVT","NBV","KJA"];
const aliases:Record<string,string[]>={"Cânticos":["Cantares","Cantares de Salomão"],"Apocalipse":["Revelação"],"Filemom":["Filemon"]};

function editDistance(a:string,b:string){const dp=Array.from({length:a.length+1},()=>Array(b.length+1).fill(0));for(let i=0;i<=a.length;i++)dp[i][0]=i;for(let j=0;j<=b.length;j++)dp[0][j]=j;for(let i=1;i<=a.length;i++)for(let j=1;j<=b.length;j++)dp[i][j]=Math.min(dp[i-1][j]+1,dp[i][j-1]+1,dp[i-1][j-1]+(a[i-1]===b[j-1]?0:1));return dp[a.length][b.length]}
function keys(book:string){const all=[book,...(aliases[book]||[])].flatMap(value=>{const normalized=normalizeSearch(value);return[normalized,normalized.replace(/ /g,""),normalized.replace(/^[123] /,"")]});return [...new Set(all.filter(Boolean))]}
function searchBooks(raw:string){const query=normalizeSearch(raw);if(!query)return bibleBooks;const compact=query.replace(/ /g,"");const direct=bibleBooks.map((book,index)=>{let score=0;for(const key of keys(book)){if(key===query||key===compact)score=Math.max(score,100);else if(key.startsWith(query)||key.startsWith(compact))score=Math.max(score,80);else if(key.includes(query)||key.includes(compact))score=Math.max(score,60)}return{book,index,score}}).filter(item=>item.score>0).sort((a,b)=>b.score-a.score||a.index-b.index);if(direct.length)return direct.map(item=>item.book);if(query.length<3)return[];const max=query.length<=4?1:query.length<=7?2:query.length<=11?3:4;return bibleBooks.map((book,index)=>({book,index,distance:Math.min(...keys(book).map(key=>editDistance(compact,key.replace(/ /g,""))))})).filter(item=>item.distance<=max).sort((a,b)=>a.distance-b.distance||a.index-b.index).slice(0,6).map(item=>item.book)}
function cleanHtml(value:string){const doc=new DOMParser().parseFromString(value,"text/html");return(doc.body.textContent||"").replace(/\s+/g," ").trim()}
function parseReference(query:string){const normalized=normalizeSearch(query);const compact=normalized.replace(/ /g,"");const candidates=bibleBooks.map(book=>{const normalizedBook=normalizeSearch(book);const compactBook=normalizedBook.replace(/ /g,"");if(normalized.startsWith(`${normalizedBook} `))return{book,rest:normalized.slice(normalizedBook.length).trim(),len:normalizedBook.length};if(compact.startsWith(compactBook))return{book,rest:compact.slice(compactBook.length),len:compactBook.length};return null}).filter(Boolean).sort((a,b)=>b!.len-a!.len) as {book:string;rest:string;len:number}[];const first=candidates[0];if(!first)return null;const match=first.rest.match(/^(\d+)(?:[: ]?(\d+))?$/);if(!match)return null;const chapter=Number(match[1]);const verse=match[2]?Number(match[2]):undefined;const max=bibleBookChapters[first.book as keyof typeof bibleBookChapters];return chapter>=1&&chapter<=max?{book:first.book,chapter,verse}:null}
async function fetchChapter(book:string,chapter:number,translation:Translation,signal?:AbortSignal){const id=bibleBooks.indexOf(book)+1;const response=await fetch(`https://bolls.life/get-text/${translation}/${id}/${chapter}/`,{signal,headers:{Accept:"application/json"}});if(!response.ok)throw new Error("Não foi possível carregar este capítulo.");const payload=await response.json() as Array<{verse?:unknown;text?:unknown}>;return payload.map(item=>({verse:Number(item.verse),text:cleanHtml(String(item.text||""))})).filter(verse=>verse.verse>0&&verse.text) as Verse[]}
async function deepSearch(query:string,translation:Translation,signal?:AbortSignal):Promise<SearchResult[]>{const reference=parseReference(query);if(reference){const verses=await fetchChapter(reference.book,reference.chapter,translation,signal);const list=reference.verse?verses.filter(verse=>verse.verse===reference.verse):verses.slice(0,1);return list.map(verse=>({book:reference.book,chapter:reference.chapter,verse:verse.verse,text:verse.text}))}const response=await fetch(`https://bolls.life/v2/find/${translation}?search=${encodeURIComponent(query)}&limit=24&page=1`,{signal,headers:{Accept:"application/json"}});if(!response.ok)throw new Error("Pesquisa bíblica indisponível.");const payload=await response.json() as {results?:Array<{book?:number;chapter?:number;verse?:number;text?:string}>};return(payload.results||[]).map(item=>({book:bibleBooks[Number(item.book)-1],chapter:Number(item.chapter),verse:Number(item.verse),text:cleanHtml(item.text||"")})).filter(item=>item.book&&item.chapter>0&&item.verse>0)}

export function BibleParityViewV2(){
  const target=useMemo(()=>{try{return JSON.parse(localStorage.getItem("micrhema:pwa:bible-target")||"null") as {book?:string;chapter?:number;verse?:number}|null}catch{return null}},[]);
  const[translation,setTranslation]=useState<Translation>(()=>(localStorage.getItem("micrhema:pwa:bible-version") as Translation)||"ARA");const[book,setBook]=useState(target?.book&&bibleBooks.includes(target.book)?target.book:"Gênesis");const[chapter,setChapter]=useState(target?.chapter||1);const[focusVerse,setFocusVerse]=useState(target?.verse||0);const[verses,setVerses]=useState<Verse[]>([]);const[loading,setLoading]=useState(true);const[error,setError]=useState("");const[bookQuery,setBookQuery]=useState("");const[deepQuery,setDeepQuery]=useState("");const[deepResults,setDeepResults]=useState<SearchResult[]>([]);const[deepBusy,setDeepBusy]=useState(false);const[deepError,setDeepError]=useState("");const verseRefs=useRef<Record<number,HTMLParagraphElement|null>>({});
  const max=bibleBookChapters[book as keyof typeof bibleBookChapters];
  useEffect(()=>{localStorage.setItem("micrhema:pwa:bible-version",translation);const controller=new AbortController();setLoading(true);setError("");fetchChapter(book,chapter,translation,controller.signal).then(result=>{setVerses(result);void recordPwaActivity("bible_chapters",`${book}:${chapter}`).catch(()=>undefined)}).catch(errorValue=>{if(errorValue?.name!=="AbortError")setError(errorValue.message||"Falha ao carregar.")}).finally(()=>{if(!controller.signal.aborted)setLoading(false)});localStorage.setItem("micrhema:pwa:last-reading",JSON.stringify({book,chapter,translation}));return()=>controller.abort()},[book,chapter,translation]);
  useEffect(()=>{if(focusVerse&&verses.length){window.setTimeout(()=>verseRefs.current[focusVerse]?.scrollIntoView({behavior:"smooth",block:"center"}),100);localStorage.removeItem("micrhema:pwa:bible-target")}},[focusVerse,verses]);
  useEffect(()=>{if(deepQuery.trim().length<2){setDeepResults([]);setDeepError("");return}const controller=new AbortController();const timer=window.setTimeout(()=>{setDeepBusy(true);setDeepError("");deepSearch(deepQuery.trim(),translation,controller.signal).then(setDeepResults).catch(errorValue=>{if(errorValue?.name!=="AbortError")setDeepError("Não foi possível pesquisar agora. Verifique sua conexão.")}).finally(()=>{if(!controller.signal.aborted)setDeepBusy(false)})},450);return()=>{clearTimeout(timer);controller.abort()}},[deepQuery,translation]);
  const next=(direction:-1|1)=>{let index=bibleBooks.indexOf(book);if(direction<0){if(chapter>1)setChapter(chapter-1);else if(index>0){index--;const previous=bibleBooks[index];setBook(previous);setChapter(bibleBookChapters[previous as keyof typeof bibleBookChapters])}}else{if(chapter<max)setChapter(chapter+1);else if(index<bibleBooks.length-1){index++;setBook(bibleBooks[index]);setChapter(1)}}setFocusVerse(0);window.scrollTo({top:0})};
  const openResult=(result:SearchResult)=>{setBook(result.book);setChapter(result.chapter);setFocusVerse(result.verse);setDeepQuery("");setDeepResults([])};
  const visibleBooks=useMemo(()=>searchBooks(bookQuery),[bookQuery]);
  return <section className="parity-page bible-v2"><div className="parity-title"><div><p>BÍBLIA SAGRADA</p><h1>{book} {chapter}</h1><span>Escolha um livro e um capítulo.</span></div><select value={translation} onChange={event=>setTranslation(event.target.value as Translation)}>{translations.map(version=><option key={version}>{version}</option>)}</select></div>
    <label style={{display:"flex",alignItems:"center",gap:8,border:"1px solid #aaa",borderRadius:18,padding:"0 12px",minHeight:48}}><Search size={18}/><input value={bookQuery} onChange={event=>setBookQuery(event.target.value)} placeholder="Pesquisar livro — ex.: genesis, joao" style={{flex:1,border:0,outline:0,background:"transparent",color:"inherit"}}/>{bookQuery&&<button onClick={()=>setBookQuery("")} style={{border:0,background:"transparent",color:"inherit"}}><X size={18}/></button>}</label>{bookQuery&&visibleBooks[0]&&<small style={{display:"block",margin:"7px 2px 12px"}}>Entendi: <b>{visibleBooks[0]}</b></small>}
    <div className="book-rail">{visibleBooks.map(name=><button key={name} className={book===name?"chosen":""} onClick={()=>{setBook(name);setChapter(1);setBookQuery("");setFocusVerse(0)}}>{name}</button>)}</div><div className="chapter-strip">{Array.from({length:max},(_,index)=>index+1).map(number=><button key={number} className={chapter===number?"current":""} onClick={()=>{setChapter(number);setFocusVerse(0)}}>{number}</button>)}</div>
    <article className="parity-reader"><p style={{fontWeight:800}}>{book.toUpperCase()} · CAPÍTULO {chapter}</p>{loading&&<p>Carregando os versículos…</p>}{error&&<p>{error}</p>}{!loading&&!error&&verses.map(verse=><p key={verse.verse} ref={element=>{verseRefs.current[verse.verse]=element}} style={focusVerse===verse.verse?{outline:"2px solid var(--pwa-primary,#8a6500)",borderRadius:10,padding:8}:undefined}><sup>{verse.verse}</sup>{verse.text}</p>)}</article>
    <div className="parity-bottom-actions"><button onClick={()=>next(-1)} disabled={book===bibleBooks[0]&&chapter===1}><ChevronLeft size={17}/>Anterior</button><button onClick={()=>{const key=`${translation}:${book}:${chapter}`;const current=JSON.parse(localStorage.getItem("micrhema:pwa:bible-favorites")||"[]") as string[];const exists=current.includes(key);localStorage.setItem("micrhema:pwa:bible-favorites",JSON.stringify(exists?current.filter(item=>item!==key):[...current,key]));toast.success(exists?"Removido dos favoritos.":"Capítulo salvo.")}}><Heart size={17}/>Salvar</button><button onClick={()=>next(1)} disabled={book===bibleBooks.at(-1)&&chapter===max}>Próximo<ChevronRight size={17}/></button></div>
    <section style={{marginTop:26,borderTop:"1px solid rgba(127,127,127,.25)",paddingTop:18}}><h2>Pesquisa profunda</h2><p style={{opacity:.75}}>Pesquise nomes, situações, temas, referências ou parte de um versículo. A pesquisa usa a versão bíblica selecionada.</p><label style={{display:"flex",alignItems:"center",gap:8,border:"1px solid #aaa",borderRadius:18,padding:"0 12px",minHeight:50}}><Search size={18}/><input value={deepQuery} onChange={event=>setDeepQuery(event.target.value)} placeholder="Ex.: curado, ansiedade, Davi, João 3:16" style={{flex:1,border:0,outline:0,background:"transparent",color:"inherit"}}/>{deepQuery&&<button onClick={()=>setDeepQuery("")} style={{border:0,background:"transparent",color:"inherit"}}><X size={18}/></button>}</label>{deepBusy&&<p>Procurando referências…</p>}{deepError&&<p style={{color:"#b91c1c"}}>{deepError}</p>}{!deepBusy&&!deepError&&deepQuery.trim().length>=2&&!deepResults.length&&<p>Nenhuma referência encontrada nessa busca.</p>}<div className="android-list-cards" style={{marginTop:10}}>{deepResults.map(result=><button key={`${result.book}-${result.chapter}-${result.verse}`} onClick={()=>openResult(result)}><span><BookOpen size={18}/></span><div><strong>{result.book} {result.chapter}:{result.verse}</strong><small>{result.text}</small></div><ChevronRight size={18}/></button>)}</div></section>
  </section>;
}
