import { useEffect, useMemo, useState } from "react";
import { CalendarDays, ChevronLeft, ChevronRight, Clock, MapPin } from "lucide-react";
import { listenToCollection } from "@/lib/firebase";
import { parseAppDate } from "@/lib/parity-utils";
import "./AndroidParityViews.css";

type Service={id:string;title?:string;day?:string;dayShort?:string;time?:string;date?:string;description?:string;location?:string;approved?:boolean;isApproved?:boolean};
const dayIndex:Record<string,number>={domingo:0,segunda:1,"segunda-feira":1,terça:2,"terça-feira":2,quarta:3,"quarta-feira":3,quinta:4,"quinta-feira":4,sexta:5,"sexta-feira":5,sábado:6,sabado:6};
function approved(item:Service){return item.approved!==false&&item.isApproved!==false}
function parseTime(value?:string){const parts=String(value||"23:59").replace(/h/i,":").replace(/[^0-9:]/g,"").split(":");return{h:Number(parts[0])||23,m:Number(parts[1])||0}}
function nextOccurrence(service:Service,now=new Date()){const {h,m}=parseTime(service.time);const exact=parseAppDate(service.date);if(exact){exact.setHours(h,m,0,0);return exact}const target=dayIndex[String(service.day||"").toLowerCase()]??0;const date=new Date(now);date.setHours(h,m,0,0);let diff=target-now.getDay();if(diff<0||(diff===0&&date.getTime()<now.getTime()))diff+=7;date.setDate(now.getDate()+diff);return date}
export function CultosParityView(){
 const[services,setServices]=useState<Service[]>([]);const[selected,setSelected]=useState<Service|null>(null);useEffect(()=>listenToCollection<Service>("cultos_agenda",setServices,()=>setServices([])),[]);const visible=useMemo(()=>services.filter(approved).filter(item=>{const exact=parseAppDate(item.date);return !exact||nextOccurrence(item).getTime()>=Date.now()-24*60*60*1000}).sort((a,b)=>nextOccurrence(a).getTime()-nextOccurrence(b).getTime()),[services]);
 if(selected){const date=nextOccurrence(selected);return <section className="parity-page"><button className="back-link" onClick={()=>setSelected(null)}><ChevronLeft size={18}/> Voltar aos cultos</button><div className="parity-title"><div><p>AGENDA DA IGREJA</p><h1>{selected.title||"Culto"}</h1><span>{date.toLocaleDateString("pt-BR",{weekday:"long",day:"2-digit",month:"long"})}</span></div><CalendarDays size={30}/></div><article className="android-module-card" style={{display:"grid",gap:12,padding:18}}><div style={{display:"flex",gap:10,alignItems:"center"}}><Clock size={20}/><strong>{selected.time||"Horário a confirmar"}</strong></div>{selected.location&&<div style={{display:"flex",gap:10,alignItems:"center"}}><MapPin size={20}/><span>{selected.location}</span></div>}<p style={{margin:0}}>{selected.description||"Programação da MIC Rhema."}</p></article></section>}
 return <section className="parity-page"><div className="parity-title"><div><p>CULTOS</p><h1>Próximos Cultos</h1><span>Agenda sincronizada com a programação oficial.</span></div><CalendarDays size={30}/></div>{!visible.length?<p className="parity-status">Nenhum culto agendado.</p>:<div className="android-list-cards">{visible.map(item=>{const date=nextOccurrence(item);return <button key={item.id} onClick={()=>setSelected(item)}><span><strong>{item.dayShort||date.toLocaleDateString("pt-BR",{weekday:"short"}).replace(".","").toUpperCase()}</strong></span><div><strong>{item.title||"Culto"}</strong><small>{date.toLocaleDateString("pt-BR")} · {item.time||"Horário a confirmar"}</small></div><ChevronRight size={19}/></button>})}</div>}</section>
}
