import { useNotificationItem } from "@/lib/notification-target";
import { useEffect, useMemo, useState } from "react";
import { BookHeart, ChevronLeft, ChevronRight, Download, FileText } from "lucide-react";
import { listenToCollection } from "@/lib/firebase";
import { safeFilename } from "@/lib/parity-utils";
import "./AndroidParityViews.css";
import { RichDocumentReader } from "./RichDocumentReader";

type Pdf={id:string;title?:string;subtitle?:string;description?:string;category?:string;fileUrl?:string;fileType?:string;storagePath?:string;order?:number;isPublished?:boolean;createdAt?:number};
export function DiscipuladoParityViewV2(){
 const[items,setItems]=useState<Pdf[]>([]);const[selected,setSelected]=useState<Pdf|null>(null);useEffect(()=>listenToCollection<Pdf>("discipulado_pdfs",setItems,()=>setItems([])),[]);const published=useMemo(()=>items.filter(i=>i.isPublished!==false).sort((a,b)=>Number(a.order||0)-Number(b.order||0)||Number(b.createdAt||0)-Number(a.createdAt||0)),[items]);
 useNotificationItem(published,setSelected);
 useEffect(()=>{setSelected(current=>current?published.find(item=>item.id===current.id)||null:null)},[published]);
 if(selected){const url=selected.fileUrl||"";const driveId=url.match(/\/d\/([^/?]+)/)?.[1]||url.match(/[?&]id=([^&]+)/)?.[1];const preview=driveId?`https://drive.google.com/file/d/${encodeURIComponent(driveId)}/preview`:selected.fileType==="word"?`https://docs.google.com/gview?embedded=1&url=${encodeURIComponent(url)}`:url;const isDocx=selected.fileType==="word"&&(/\.docx(?:[?#]|$)/i.test(url)||/\.docx(?:[?#]|$)/i.test(selected.storagePath||""));if(isDocx&&url)return <RichDocumentReader sourceUrl={url} type="docx" title={selected.title||"Estudo bíblico"} onClose={()=>setSelected(null)}/>;const download=()=>{if(!url)return;const a=document.createElement("a");a.href=driveId?`https://drive.google.com/uc?export=download&id=${encodeURIComponent(driveId)}`:url;a.target="_blank";a.rel="noopener noreferrer";a.download=safeFilename(selected.title||"discipulado-mic-rhema");a.click()};return <section className="parity-page"><button className="back-link" onClick={()=>setSelected(null)}><ChevronLeft size={18}/> Voltar ao discipulado</button><div className="parity-title"><div><p>{selected.category||"DISCIPULADO"}</p><h1>{selected.title||"Estudo bíblico"}</h1><span>{selected.subtitle||selected.description||"Material de estudo"}</span></div><FileText size={30}/></div>{selected.description&&<p>{selected.description}</p>}{url?<><iframe className="parity-document" src={preview} title={selected.title||"Estudo de discipulado"}/><button className="parity-primary" onClick={download}><Download size={18}/> Baixar estudo</button></>:<p className="parity-status">O arquivo deste estudo ainda não está disponível.</p>}</section>}
 return <section className="parity-page"><div className="parity-title"><div><p>DISCIPULADO</p><h1>Discipulado</h1></div><BookHeart size={30}/></div><article className="discipulado-hero"><div><small>ESTUDO ABERTO</small><h2>Cresça na Palavra</h2><p>Materiais para fortalecer sua caminhada cristã, estudar em casa e compartilhar com a família.</p></div><BookHeart size={64}/></article><h2>Biblioteca de estudos</h2><p>Leia os materiais e avance no seu estudo da Palavra.</p>{!published.length?<p className="parity-status">Nenhum estudo publicado ainda.</p>:<div className="android-list-cards">{published.map((item,index)=><button key={item.id} onClick={()=>setSelected(item)}><span>{String(index+1).padStart(2,"0")}</span><div><strong>{item.title||"Estudo bíblico"}</strong><small>{[item.category,item.subtitle,item.description].filter(Boolean).join(" · ")||"Estudo de discipulado"}</small></div><ChevronRight size={19}/></button>)}</div>}</section>
}
