import { useEffect, useMemo, useState } from "react";
import { BookOpen, CalendarDays, ChevronRight, FileText, Headphones, Heart, Pause, Play, Users, Video, X } from "lucide-react";
import { listenToCollection, listenToDocument } from "@/lib/firebase";
import type { PwaSessionLike } from "./AndroidParityViews";
import type { AppView } from "./PwaShell";
import "./HomeParityView.css";

type Banner={id:string;imageUrl?:string;title?:string;description?:string;tag?:string;eventDate?:string;eventInfo?:string};
type AppSettings={bannerRotationSeconds?:number};
type Devotional={id:string;title?:string;date?:string;content?:string;verseReference?:string;timestamp?:number;approved?:boolean;isApproved?:boolean};
type News={id:string;title?:string;imageUrl?:string;category?:string;book?:string;chapter?:number;verse?:string|number;publishedAt?:number;featured?:boolean};
type Service={id:string;title?:string;day?:string;dayShort?:string;time?:string;date?:string;description?:string;approved?:boolean;isApproved?:boolean};
type Media={id:string;title?:string;description?:string;imageUrl?:string;thumbnailUrl?:string;coverUrl?:string;videoUrl?:string;audioUrl?:string;bookUrl?:string;mediaUrl?:string;artist?:string;author?:string;approved?:boolean;isApproved?:boolean;kind?:"Vídeo"|"Áudio"|"Livro"};

type Mood={title:string;emoji:string;plan:string};
const moods:Mood[]=[
  {title:"Feliz",emoji:"😊",plan:"Alegria"},{title:"Ansioso",emoji:"😟",plan:"Ansiedade"},{title:"Triste",emoji:"😔",plan:"Esperança"},{title:"Com medo",emoji:"😨",plan:"Medo"},
  {title:"Irritado",emoji:"😤",plan:"Raiva"},{title:"Desanimado",emoji:"😞",plan:"Esperança"},{title:"Em paz",emoji:"😌",plan:"Paz"},{title:"Preciso de esperança",emoji:"🙏",plan:"Esperança"},
];
const dayIndex:Record<string,number>={domingo:0,segunda:1,"segunda-feira":1,terça:2,"terça-feira":2,quarta:3,"quarta-feira":3,quinta:4,"quinta-feira":4,sexta:5,"sexta-feira":5,sábado:6,sabado:6};

function approved(item:{approved?:boolean;isApproved?:boolean}){return item.approved!==false&&item.isApproved!==false}
function parseTime(value?:string){const parts=(value||"23:59").replace(/h/i,":").replace(/[^0-9:]/g,"").split(":");return {h:Number(parts[0])||23,m:Number(parts[1])||0}}
function schedule(service:Service){const now=new Date();const {h,m}=parseTime(service.time);if(/^\d{4}-\d{2}-\d{2}$/.test(service.date||"")){const d=new Date(`${service.date}T${String(h).padStart(2,"0")}:${String(m).padStart(2,"0")}:00`);if(!Number.isNaN(d.getTime()))return d;}const target=dayIndex[(service.day||"domingo").toLowerCase()]??0;const d=new Date(now);d.setHours(h,m,0,0);let diff=target-now.getDay();if(diff<0||(diff===0&&d.getTime()<now.getTime()))diff+=7;d.setDate(now.getDate()+diff);return d}
function youtubeId(value?:string){if(!value)return"";try{const u=new URL(value);const h=u.hostname.replace(/^www\./,"");const id=h==="youtu.be"?u.pathname.split("/")[1]:u.searchParams.get("v")||u.pathname.match(/^\/(?:embed|shorts|live)\/([^/?]+)/)?.[1]||"";return /^[\w-]{11}$/.test(id)?id:""}catch{return""}}
function mediaUrl(item:Media){return item.videoUrl||item.audioUrl||item.bookUrl||item.mediaUrl||""}
function mediaImage(item:Media){const id=youtubeId(item.videoUrl||item.mediaUrl);return item.imageUrl||item.thumbnailUrl||item.coverUrl||(id?`https://i.ytimg.com/vi/${id}/hqdefault.jpg`:"")}

function MediaModal({item,onClose}:{item:Media;onClose:()=>void}){const url=mediaUrl(item);const yid=youtubeId(url);return <div className="home-v2-backdrop" onMouseDown={onClose}><section className="home-v2-media-modal" onMouseDown={e=>e.stopPropagation()}><button className="home-v2-close" onClick={onClose}><X size={20}/></button><p>{item.kind}</p><h2>{item.title||"Mídia"}</h2>{item.kind==="Vídeo"?(yid?<iframe src={`https://www.youtube-nocookie.com/embed/${yid}?rel=0`} allow="accelerometer; autoplay; encrypted-media; picture-in-picture" allowFullScreen title={item.title||"Vídeo"}/>:<video controls playsInline src={url}/>):item.kind==="Áudio"?<audio controls src={url}/>:<iframe src={url} title={item.title||"Livro"}/>} {item.description&&<span>{item.description}</span>}</section></div>}
function ServiceModal({item,onClose}:{item:Service;onClose:()=>void}){return <div className="home-v2-backdrop" onMouseDown={onClose}><section className="home-v2-info-modal" onMouseDown={e=>e.stopPropagation()}><button className="home-v2-close" onClick={onClose}><X size={20}/></button><p>CULTO</p><h2>{item.title||"Culto"}</h2><strong>{item.day} às {item.time}</strong><span>{item.description||"A descrição deste culto ainda não foi cadastrada."}</span></section></div>}

export function HomeParityView({session,onNavigate}:{session:PwaSessionLike;onNavigate:(view:AppView)=>void}){
  const[banners,setBanners]=useState<Banner[]>([]);const[settings,setSettings]=useState<(AppSettings&{id:string})|null>(null);const[devotionals,setDevotionals]=useState<Devotional[]>([]);const[news,setNews]=useState<News[]>([]);const[services,setServices]=useState<Service[]>([]);const[videos,setVideos]=useState<Media[]>([]);const[audios,setAudios]=useState<Media[]>([]);const[books,setBooks]=useState<Media[]>([]);
  const[bannerIndex,setBannerIndex]=useState(0);const[moodOpen,setMoodOpen]=useState(false);const[eventInfo,setEventInfo]=useState("");const[selectedService,setSelectedService]=useState<Service|null>(null);const[selectedMedia,setSelectedMedia]=useState<Media|null>(null);const[devotionalOpen,setDevotionalOpen]=useState(false);
  const todayKey=new Date().toISOString().slice(0,10);const[savedMood,setSavedMood]=useState<Mood|null>(()=>{try{const p=JSON.parse(localStorage.getItem("micrhema:pwa:mood")||"null");return p?.date===new Date().toISOString().slice(0,10)?p.mood:null}catch{return null}});
  useEffect(()=>listenToCollection<Banner>("carousel_items",setBanners,()=>setBanners([])),[]);useEffect(()=>listenToDocument<AppSettings>("settings","app",setSettings,()=>setSettings(null)),[]);useEffect(()=>listenToCollection<Devotional>("devocionais",setDevotionals,()=>setDevotionals([])),[]);useEffect(()=>listenToCollection<News>("bible_news",setNews,()=>setNews([])),[]);useEffect(()=>listenToCollection<Service>("cultos_agenda",setServices,()=>setServices([])),[]);useEffect(()=>listenToCollection<Media>("conteudos_videos",setVideos,()=>setVideos([])),[]);useEffect(()=>listenToCollection<Media>("conteudos_audios",setAudios,()=>setAudios([])),[]);useEffect(()=>listenToCollection<Media>("conteudos_books",setBooks,()=>setBooks([])),[]);
  const activeBanners=useMemo(()=>banners.filter(b=>b.imageUrl&&(!b.eventDate||b.eventDate>=todayKey)),[banners,todayKey]);const rotation=Math.max(3,Math.min(12,Number(settings?.bannerRotationSeconds)||6))*1000;useEffect(()=>{if(activeBanners.length<2)return;const id=window.setInterval(()=>setBannerIndex(i=>(i+1)%activeBanners.length),rotation);return()=>clearInterval(id)},[activeBanners.length,rotation]);useEffect(()=>setBannerIndex(i=>activeBanners.length?i%activeBanners.length:0),[activeBanners.length]);
  const devotional=useMemo(()=>{const items=devotionals.filter(approved).sort((a,b)=>(b.timestamp||0)-(a.timestamp||0));const d=new Date();const pt=`${String(d.getDate()).padStart(2,"0")}/${String(d.getMonth()+1).padStart(2,"0")}/${d.getFullYear()}`;return items.find(i=>i.date===pt)||items[0]},[devotionals]);
  const latestNews=useMemo(()=>{const featured=news.filter(n=>n.featured);return(featured.length?featured:news).slice().sort((a,b)=>(b.publishedAt||0)-(a.publishedAt||0)).slice(0,5)},[news]);const upcoming=useMemo(()=>services.filter(approved).slice().sort((a,b)=>schedule(a).getTime()-schedule(b).getTime()).slice(0,3),[services]);
  const todayServices=useMemo(()=>{const now=new Date();return services.filter(approved).filter(s=>(dayIndex[(s.day||"").toLowerCase()]??-1)===now.getDay()).map(s=>({s,t:parseTime(s.time)})).sort((a,b)=>a.t.h*60+a.t.m-(b.t.h*60+b.t.m))},[services]);const contextual=useMemo(()=>{if(!todayServices.length)return null;const now=new Date();const mins=now.getHours()*60+now.getMinutes();const future=todayServices.find(x=>x.t.h*60+x.t.m>=mins);return future?{service:future.s,future:true}:{service:todayServices[todayServices.length-1].s,future:false}},[todayServices]);
  const media=useMemo(()=>[...videos.filter(approved).slice().sort((a,b)=>Number(b.id)-Number(a.id)).slice(0,3).map(i=>({...i,kind:"Vídeo" as const})),...audios.filter(approved).slice().sort((a,b)=>Number(b.id)-Number(a.id)).slice(0,3).map(i=>({...i,kind:"Áudio" as const})),...books.filter(approved).slice().sort((a,b)=>Number(b.id)-Number(a.id)).slice(0,3).map(i=>({...i,kind:"Livro" as const}))],[videos,audios,books]);const banner=activeBanners[bannerIndex];const firstName=session?.name?.trim().split(/\s+/)[0];
  const chooseMood=(mood:Mood)=>{setSavedMood(mood);localStorage.setItem("micrhema:pwa:mood",JSON.stringify({date:todayKey,mood}));setMoodOpen(false);localStorage.setItem("micrhema:pwa:selected-plan-theme",mood.plan);onNavigate("plans")};
  return <section className="home-v2-root">
    <header className="home-v2-greeting"><h1>{firstName?`Olá, ${firstName} 👋`:"Seja bem-vindo à Rhema"}</h1><p>Que a paz do Senhor esteja com você</p></header>
    {contextual&&<button className="home-v2-today" onClick={()=>setSelectedService(contextual.service)}><CalendarDays size={31}/><span><strong>{contextual.future?"Hoje tem":"Hoje teve"} {contextual.service.title}</strong><small>Às {contextual.service.time}</small></span></button>}
    {banner&&<section className="home-v2-banners"><button className="home-v2-banner" onClick={()=>banner.eventInfo&&setEventInfo(banner.eventInfo)} disabled={!banner.eventInfo}><img src={banner.imageUrl} alt={banner.title||"Destaque MIC Rhema"}/>{(banner.tag||banner.title||banner.description)&&<span>{banner.tag&&<small>{banner.tag}</small>}{banner.title&&<strong>{banner.title}</strong>}{banner.description&&<em>{banner.description}</em>}</span>}</button>{activeBanners.length>1&&<div>{activeBanners.map((b,i)=><button key={b.id} className={i===bannerIndex?"active":""} onClick={()=>setBannerIndex(i)} aria-label={`Destaque ${i+1}`}/>)}</div>}</section>}
    <button className="home-v2-mood" onClick={()=>setMoodOpen(true)}><Heart size={30}/><span><strong>{savedMood?`Hoje você marcou: ${savedMood.title}`:"Como você está se sentindo hoje?"}</strong><small>{savedMood?`Plano sugerido: ${savedMood.plan} · toque para alterar`:"Toque para escolher"}</small></span><ChevronRight size={20}/></button>
    <section className="home-v2-shortcuts"><button onClick={()=>onNavigate("bible")}><BookOpen/><span>Bíblia</span></button><button onClick={()=>onNavigate("prayer")}><Heart/><span>Pedidos</span></button><button onClick={()=>onNavigate("plans")}><CalendarDays/><span>Planos</span></button><button onClick={()=>onNavigate("members")}><Users/><span>Membros</span></button></section>
    {devotional&&<button className="home-v2-devotional" onClick={()=>setDevotionalOpen(true)}><span><small>DEVOCIONAL DIÁRIO</small><strong>{devotional.title||"Palavra para hoje"}</strong><em>{devotional.content||devotional.verseReference||devotional.date}</em></span><b>Ler <ChevronRight size={16}/></b></button>}
    <HomeSection title="Notícias Bíblicas" action={()=>onNavigate("news")}><div className="home-v2-rail">{latestNews.map(item=><button className="home-v2-news" key={item.id} onClick={()=>onNavigate("news")}><div>{item.imageUrl&&<img src={item.imageUrl} alt=""/>}</div><strong>{item.title}</strong><small>{item.category||"Notícia bíblica"}</small><em>{item.book?`${item.book} ${item.chapter||""}${item.verse?`:${item.verse}`:""}`:""}</em></button>)}</div></HomeSection>
    <HomeSection title="Próximos Cultos" action={()=>onNavigate("cultos")}><div className="home-v2-rail">{upcoming.map(item=>{const date=schedule(item);return <button className="home-v2-service" key={item.id} onClick={()=>setSelectedService(item)}><span><small>{item.dayShort||date.toLocaleDateString("pt-BR",{weekday:"short"}).replace(".","").toUpperCase()}</small><b>🗓</b></span><div><strong>{item.title||"Culto"}</strong><small>{item.time}</small>{item.date&&<em>{date.toLocaleDateString("pt-BR")}</em>}</div></button>})}</div></HomeSection>
    <HomeSection title="Mídia" action={()=>onNavigate("media")}><div className="home-v2-rail">{media.map(item=><button className="home-v2-media" key={`${item.kind}-${item.id}`} onClick={()=>setSelectedMedia(item)}>{mediaImage(item)?<img src={mediaImage(item)} alt=""/>:<div className="home-v2-media-empty"/>}<span>{item.kind==="Vídeo"?<Video/>:item.kind==="Áudio"?<Headphones/>:<FileText/>}{item.kind}</span><strong>{item.title}</strong></button>)}</div></HomeSection>
    {moodOpen&&<div className="home-v2-backdrop" onMouseDown={()=>setMoodOpen(false)}><section className="home-v2-mood-sheet" onMouseDown={e=>e.stopPropagation()}><button className="home-v2-close" onClick={()=>setMoodOpen(false)}><X/></button><h2>Como está seu coração hoje?</h2><div>{moods.map(m=><button key={m.title} onClick={()=>chooseMood(m)}><span>{m.emoji}</span><strong>{m.title}</strong><small>{m.plan}</small></button>)}</div></section></div>}
    {eventInfo&&<div className="home-v2-backdrop" onMouseDown={()=>setEventInfo("")}><section className="home-v2-info-modal" onMouseDown={e=>e.stopPropagation()}><button className="home-v2-close" onClick={()=>setEventInfo("")}><X/></button><p>DESTAQUE DA IGREJA</p><h2>Informações do evento</h2><span>{eventInfo}</span></section></div>}{selectedService&&<ServiceModal item={selectedService} onClose={()=>setSelectedService(null)}/>} {selectedMedia&&<MediaModal item={selectedMedia} onClose={()=>setSelectedMedia(null)}/>} {devotionalOpen&&devotional&&<div className="home-v2-backdrop" onMouseDown={()=>setDevotionalOpen(false)}><section className="home-v2-info-modal home-v2-devotional-modal" onMouseDown={e=>e.stopPropagation()}><button className="home-v2-close" onClick={()=>setDevotionalOpen(false)}><X/></button><p>DEVOCIONAL DIÁRIO</p><h2>{devotional.title}</h2>{devotional.verseReference&&<strong>{devotional.verseReference}</strong>}<span>{devotional.content}</span></section></div>}
  </section>
}
function HomeSection({title,action,children}:{title:string;action:()=>void;children:React.ReactNode}){return <section className="home-v2-section"><header><h2>{title}</h2><button onClick={action}>Ver todas <ChevronRight size={15}/></button></header>{children}</section>}
