import { useEffect, useMemo, useRef, useState } from "react";
import { BookOpen, CalendarDays, ChevronRight, FileText, Headphones, Heart, Users, Video, X } from "lucide-react";
import { listenToCollection, listenToDocument } from "@/lib/firebase";
import { recordPwaActivity } from "@/lib/badge-activity";
import { appDateKey, contentTimestamp, parseAppDate, stableSessionShuffle, todayKey, youtubeThumbnail, youtubeVideoId } from "@/lib/parity-utils";
import { todayOrLatestDevotional } from "./DevotionalsParityView";
import type { PwaSessionLike } from "./AndroidParityViews";
import type { AppView } from "./PwaShell";
import "./HomeParityView.css";

type Banner={id:string;imageUrl?:string;title?:string;description?:string;tag?:string;eventDate?:string;eventInfo?:string};
type AppSettings={bannerRotationSeconds?:number};
type LegacyBanners={urls?:string[]};
type Devotional={id:string;title?:string;date?:string;content?:string;verse?:string;verseReference?:string;timestamp?:number;approved?:boolean;isApproved?:boolean};
type News={id:string;title?:string;imageUrl?:string;category?:string;book?:string;chapter?:number;verse?:string|number;publishedAt?:number;createdAt?:number;timestamp?:number;featured?:boolean;approved?:boolean;isApproved?:boolean};
type Service={id:string;title?:string;day?:string;dayShort?:string;time?:string;date?:string;description?:string;approved?:boolean;isApproved?:boolean};
type Media={id:string;title?:string;description?:string;imageUrl?:string;thumbnailUrl?:string;coverUrl?:string;videoUrl?:string;audioUrl?:string;bookUrl?:string;mediaUrl?:string;artist?:string;author?:string;approved?:boolean;isApproved?:boolean;publishedAt?:number;createdAt?:number;timestamp?:number;updatedAt?:number;kind?:"Vídeo"|"Áudio"|"Livro"};
type Mood={title:string;emoji:string;plan:string};

const moods:Mood[]=[
  {title:"Feliz",emoji:"😊",plan:"Alegria"},{title:"Ansioso",emoji:"😟",plan:"Ansiedade"},{title:"Triste",emoji:"😔",plan:"Esperança"},{title:"Com medo",emoji:"😨",plan:"Medo"},
  {title:"Irritado",emoji:"😤",plan:"Raiva"},{title:"Desanimado",emoji:"😞",plan:"Esperança"},{title:"Em paz",emoji:"😌",plan:"Paz"},{title:"Preciso de esperança",emoji:"🙏",plan:"Esperança"},
];
const dayIndex:Record<string,number>={domingo:0,segunda:1,"segunda-feira":1,terça:2,"terça-feira":2,quarta:3,"quarta-feira":3,quinta:4,"quinta-feira":4,sexta:5,"sexta-feira":5,sábado:6,sabado:6};

function approved(item:{approved?:boolean;isApproved?:boolean}){return item.approved!==false&&item.isApproved!==false}
function parseTime(value?:string){const parts=(value||"23:59").replace(/h/i,":").replace(/[^0-9:]/g,"").split(":");return {h:Number(parts[0])||23,m:Number(parts[1])||0}}
function schedule(service:Service){const now=new Date();const {h,m}=parseTime(service.time);const exact=parseAppDate(service.date);if(exact){const date=new Date(exact);date.setHours(h,m,0,0);return date;}const target=dayIndex[(service.day||"domingo").toLowerCase()]??0;const date=new Date(now);date.setHours(h,m,0,0);let difference=target-now.getDay();if(difference<0||(difference===0&&date.getTime()<now.getTime()))difference+=7;date.setDate(now.getDate()+difference);return date}
function occursToday(service:Service,now=new Date()){const exact=parseAppDate(service.date);if(exact)return todayKey(exact)===todayKey(now);return(dayIndex[(service.day||"").toLowerCase()]??-1)===now.getDay()}
function mediaUrl(item:Media){return item.videoUrl||item.audioUrl||item.bookUrl||item.mediaUrl||""}
function mediaImage(item:Media){if(item.kind==="Vídeo"){const official=youtubeThumbnail(item.videoUrl||item.mediaUrl);if(official)return official;}return item.imageUrl||item.thumbnailUrl||item.coverUrl||""}
function validBannerForToday(banner:Banner,key:string){if(!banner.imageUrl)return false;if(!banner.eventDate?.trim())return true;const parsed=parseAppDate(banner.eventDate);return !parsed||appDateKey(banner.eventDate)>=key}

function MediaModal({item,onClose}:{item:Media;onClose:()=>void}){const url=mediaUrl(item);const yid=youtubeVideoId(url);return <div className="home-v2-backdrop" onMouseDown={onClose}><section className="home-v2-media-modal" onMouseDown={event=>event.stopPropagation()}><button className="home-v2-close" onClick={onClose}><X size={20}/></button><p>{item.kind}</p><h2>{item.title||"Mídia"}</h2>{item.kind==="Vídeo"?(yid?<iframe src={`https://www.youtube-nocookie.com/embed/${yid}?rel=0&playsinline=1`} allow="accelerometer; autoplay; encrypted-media; picture-in-picture" allowFullScreen title={item.title||"Vídeo"}/>:<video controls playsInline src={url}/>):item.kind==="Áudio"?<audio controls src={url}/>:<iframe src={url} title={item.title||"Livro"}/>} {item.description&&<span>{item.description}</span>}</section></div>}
function ServiceModal({item,onClose}:{item:Service;onClose:()=>void}){const date=schedule(item);return <div className="home-v2-backdrop" onMouseDown={onClose}><section className="home-v2-info-modal" onMouseDown={event=>event.stopPropagation()}><button className="home-v2-close" onClick={onClose}><X size={20}/></button><p>CULTO</p><h2>{item.title||"Culto"}</h2><strong>{item.date?date.toLocaleDateString("pt-BR"):item.day} às {item.time||"Horário a confirmar"}</strong><span>{item.description||"A descrição deste culto ainda não foi cadastrada."}</span></section></div>}
function DevotionalModal({item,onClose}:{item:Devotional;onClose:()=>void}){return <div className="home-v2-backdrop" onMouseDown={onClose}><section className="home-v2-info-modal home-v2-devotional-modal" onMouseDown={event=>event.stopPropagation()}><button className="home-v2-close" onClick={onClose}><X size={20}/></button><p>DEVOCIONAL DIÁRIO</p><h2>{item.title||"Palavra para hoje"}</h2>{item.verseReference&&<strong>{item.verseReference}</strong>}{item.verse&&<span>{item.verse}</span>}<span>{item.content||"Conteúdo ainda não cadastrado."}</span></section></div>}
function HomeSection({title,action,children}:{title:string;action:()=>void;children:React.ReactNode}){return <section className="home-v2-section"><header><h2>{title}</h2><button onClick={action}>Ver todos <ChevronRight size={16}/></button></header>{children}</section>}

export function HomeParityView({session,onNavigate}:{session:PwaSessionLike;onNavigate:(view:AppView)=>void}){
  const[banners,setBanners]=useState<Banner[]>([]);const[settings,setSettings]=useState<(AppSettings&{id:string})|null>(null);const[legacyBanners,setLegacyBanners]=useState<(LegacyBanners&{id:string})|null>(null);const[devotionals,setDevotionals]=useState<Devotional[]>([]);const[news,setNews]=useState<News[]>([]);const[services,setServices]=useState<Service[]>([]);const[videos,setVideos]=useState<Media[]>([]);const[audios,setAudios]=useState<Media[]>([]);const[books,setBooks]=useState<Media[]>([]);
  const[bannerIndex,setBannerIndex]=useState(0);const[moodOpen,setMoodOpen]=useState(false);const[eventInfo,setEventInfo]=useState("");const[selectedService,setSelectedService]=useState<Service|null>(null);const[selectedMedia,setSelectedMedia]=useState<Media|null>(null);const[selectedDevotional,setSelectedDevotional]=useState<Devotional|null>(null);const swipeStart=useRef<number|null>(null);const localToday=todayKey();
  const[savedMood,setSavedMood]=useState<Mood|null>(()=>{try{const parsed=JSON.parse(localStorage.getItem("micrhema:pwa:mood")||"null");return parsed?.date===todayKey()?parsed.mood:null}catch{return null}});
  useEffect(()=>listenToCollection<Banner>("carousel_items",setBanners,()=>setBanners([])),[]);useEffect(()=>listenToDocument<AppSettings>("settings","app",setSettings,()=>setSettings(null)),[]);useEffect(()=>listenToDocument<LegacyBanners>("settings","home_banners",setLegacyBanners,()=>setLegacyBanners(null)),[]);useEffect(()=>listenToCollection<Devotional>("devocionais",setDevotionals,()=>setDevotionals([])),[]);useEffect(()=>listenToCollection<News>("bible_news",setNews,()=>setNews([])),[]);useEffect(()=>listenToCollection<Service>("cultos_agenda",setServices,()=>setServices([])),[]);useEffect(()=>listenToCollection<Media>("conteudos_videos",setVideos,()=>setVideos([])),[]);useEffect(()=>listenToCollection<Media>("conteudos_audios",setAudios,()=>setAudios([])),[]);useEffect(()=>listenToCollection<Media>("conteudos_books",setBooks,()=>setBooks([])),[]);
  const activeBanners=useMemo<Banner[]>(()=>{const live=banners.filter(banner=>validBannerForToday(banner,localToday));if(live.length)return live;return(legacyBanners?.urls||[]).filter(Boolean).map((imageUrl,index):Banner=>({id:`legacy-${index}`,imageUrl}))},[banners,legacyBanners?.urls,localToday]);
  const rotation=Math.max(3,Math.min(12,Number(settings?.bannerRotationSeconds)||6))*1000;useEffect(()=>{if(activeBanners.length<2)return;const timer=window.setInterval(()=>setBannerIndex(index=>(index+1)%activeBanners.length),rotation);return()=>window.clearInterval(timer)},[activeBanners.length,rotation]);useEffect(()=>setBannerIndex(index=>activeBanners.length?index%activeBanners.length:0),[activeBanners.length]);
  const devotional=useMemo(()=>todayOrLatestDevotional(devotionals),[devotionals]);
  const latestNews=useMemo(()=>{const publicNews=news.filter(approved);const featured=publicNews.filter(item=>item.featured);const source=(featured.length?featured:publicNews).map(item=>({...item,id:String(item.id)}));return stableSessionShuffle(source,"micrhema:pwa:home-news-session",5)},[news]);
  const upcoming=useMemo(()=>services.filter(approved).slice().sort((left,right)=>schedule(left).getTime()-schedule(right).getTime()).slice(0,3),[services]);
  const todayServices=useMemo(()=>{const now=new Date();return services.filter(approved).filter(service=>occursToday(service,now)).map(service=>({service,time:parseTime(service.time)})).sort((a,b)=>a.time.h*60+a.time.m-(b.time.h*60+b.time.m))},[services]);
  const contextual=useMemo(()=>{if(!todayServices.length)return null;const now=new Date();const minutes=now.getHours()*60+now.getMinutes();const future=todayServices.find(item=>item.time.h*60+item.time.m>=minutes);return future?{service:future.service,future:true}:{service:todayServices[todayServices.length-1].service,future:false}},[todayServices]);
  const media=useMemo(()=>[...videos.filter(approved).slice().sort((a,b)=>contentTimestamp(b as unknown as Record<string,unknown>)-contentTimestamp(a as unknown as Record<string,unknown>)).slice(0,3).map(item=>({...item,kind:"Vídeo" as const})),...audios.filter(approved).slice().sort((a,b)=>contentTimestamp(b as unknown as Record<string,unknown>)-contentTimestamp(a as unknown as Record<string,unknown>)).slice(0,3).map(item=>({...item,kind:"Áudio" as const})),...books.filter(approved).slice().sort((a,b)=>contentTimestamp(b as unknown as Record<string,unknown>)-contentTimestamp(a as unknown as Record<string,unknown>)).slice(0,3).map(item=>({...item,kind:"Livro" as const}))],[videos,audios,books]);
  const banner=activeBanners[bannerIndex];const firstName=session?.name?.trim().split(/\s+/)[0];
  const chooseMood=(mood:Mood)=>{setSavedMood(mood);localStorage.setItem("micrhema:pwa:mood",JSON.stringify({date:localToday,mood}));setMoodOpen(false);localStorage.setItem("micrhema:pwa:selected-plan-theme",mood.plan);onNavigate("plans")};
  const openDevotional=()=>{if(!devotional)return;setSelectedDevotional(devotional);void recordPwaActivity("devotionals",devotional.id).catch(()=>undefined)};
  const openMedia=(item:Media)=>{setSelectedMedia(item);if(item.kind==="Vídeo")void recordPwaActivity("videos",item.id).catch(()=>undefined);if(item.kind==="Áudio")void recordPwaActivity("audios",item.id).catch(()=>undefined);if(item.kind==="Livro")void recordPwaActivity("books",item.id).catch(()=>undefined)};
  const finishSwipe=(clientX:number)=>{const start=swipeStart.current;swipeStart.current=null;if(start==null||activeBanners.length<2)return;const delta=clientX-start;if(Math.abs(delta)<40)return;setBannerIndex(index=>delta<0?(index+1)%activeBanners.length:(index-1+activeBanners.length)%activeBanners.length)};
  return <section className="home-v2-root">
    <header className="home-v2-greeting"><h1>{firstName?`Olá, ${firstName} 👋`:"Seja bem-vindo à Rhema"}</h1><p>Que a paz do Senhor esteja com você</p></header>
    {contextual&&<button className="home-v2-today" onClick={()=>setSelectedService(contextual.service)}><CalendarDays size={31}/><span><strong>{contextual.future?"Hoje tem":"Hoje teve"} {contextual.service.title}</strong><small>Às {contextual.service.time}</small></span></button>}
    {banner&&<section className="home-v2-banners"><button className="home-v2-banner" onClick={()=>banner.eventInfo?.trim()&&setEventInfo(banner.eventInfo.trim())} disabled={!banner.eventInfo?.trim()} onTouchStart={event=>{swipeStart.current=event.touches[0]?.clientX??null}} onTouchEnd={event=>finishSwipe(event.changedTouches[0]?.clientX??0)}><img src={banner.imageUrl} alt={banner.title||"Destaque MIC Rhema"} draggable={false}/>{(banner.tag||banner.title||banner.description)&&<span>{banner.tag&&<small>{banner.tag}</small>}{banner.title&&<strong>{banner.title}</strong>}{banner.description&&<em>{banner.description}</em>}</span>}</button>{activeBanners.length>1&&<div>{activeBanners.map((item,index)=><button key={item.id} className={index===bannerIndex?"active":""} onClick={()=>setBannerIndex(index)} aria-label={`Destaque ${index+1}`}/>)}</div>}</section>}
    <button className="home-v2-mood" onClick={()=>setMoodOpen(true)}><Heart size={30}/><span><strong>{savedMood?`Hoje você marcou: ${savedMood.title}`:"Como você está se sentindo hoje?"}</strong><small>{savedMood?`Plano sugerido: ${savedMood.plan} · toque para alterar`:"Toque para escolher"}</small></span><ChevronRight size={20}/></button>
    <section className="home-v2-shortcuts"><button onClick={()=>onNavigate("bible")}><BookOpen/><span>Bíblia</span></button><button onClick={()=>onNavigate("prayer")}><Heart/><span>Pedidos</span></button><button onClick={()=>onNavigate("plans")}><CalendarDays/><span>Planos</span></button><button onClick={()=>onNavigate("members")}><Users/><span>Membros</span></button></section>
    {devotional&&<button className="home-v2-devotional" onClick={openDevotional}><span><small>DEVOCIONAL DIÁRIO</small><strong>{devotional.title||"Palavra para hoje"}</strong><em>{devotional.content||devotional.verseReference||devotional.date}</em></span><b>Ler <ChevronRight size={16}/></b></button>}
    <HomeSection title="Notícias Bíblicas" action={()=>onNavigate("news")}><div className="home-v2-rail">{latestNews.map(item=><button className="home-v2-news" key={item.id} onClick={()=>onNavigate("news")}><div>{item.imageUrl&&<img src={item.imageUrl} alt=""/>}</div><strong>{item.title}</strong><small>{item.category||"Notícia bíblica"}</small><em>{item.book?`${item.book} ${item.chapter||""}${item.verse?`:${item.verse}`:""}`:""}</em></button>)}</div></HomeSection>
    <HomeSection title="Próximos Cultos" action={()=>onNavigate("cultos")}><div className="home-v2-rail">{upcoming.map(item=>{const date=schedule(item);return <button className="home-v2-service" key={item.id} onClick={()=>setSelectedService(item)}><span><small>{item.dayShort||date.toLocaleDateString("pt-BR",{weekday:"short"}).replace(".","").toUpperCase()}</small><b>🗓</b></span><div><strong>{item.title||"Culto"}</strong><small>{item.time||"Horário a confirmar"}</small>{item.date&&<em>{date.toLocaleDateString("pt-BR")}</em>}</div></button>})}</div></HomeSection>
    <HomeSection title="Mídia" action={()=>onNavigate("media")}><div className="home-v2-rail">{media.map(item=><button className="home-v2-media" key={`${item.kind}-${item.id}`} onClick={()=>openMedia(item)}>{mediaImage(item)?<img src={mediaImage(item)} alt=""/>:<div className="home-v2-media-empty"/>}<span>{item.kind==="Vídeo"?<Video/>:item.kind==="Áudio"?<Headphones/>:<FileText/>}{item.kind}</span><strong>{item.title}</strong></button>)}</div></HomeSection>
    {moodOpen&&<div className="home-v2-backdrop" onMouseDown={()=>setMoodOpen(false)}><section className="home-v2-mood-sheet" onMouseDown={event=>event.stopPropagation()}><button className="home-v2-close" onClick={()=>setMoodOpen(false)}><X/></button><h2>Como está seu coração hoje?</h2><div>{moods.map(mood=><button key={mood.title} onClick={()=>chooseMood(mood)}><span>{mood.emoji}</span><strong>{mood.title}</strong><small>{mood.plan}</small></button>)}</div></section></div>}
    {eventInfo&&<div className="home-v2-backdrop" onMouseDown={()=>setEventInfo("")}><section className="home-v2-info-modal" onMouseDown={event=>event.stopPropagation()}><button className="home-v2-close" onClick={()=>setEventInfo("")}><X/></button><p>DESTAQUE DA IGREJA</p><h2>Informações do evento</h2><span>{eventInfo}</span></section></div>}
    {selectedService&&<ServiceModal item={selectedService} onClose={()=>setSelectedService(null)}/>} {selectedMedia&&<MediaModal item={selectedMedia} onClose={()=>setSelectedMedia(null)}/>} {selectedDevotional&&<DevotionalModal item={selectedDevotional} onClose={()=>setSelectedDevotional(null)}/>} 
  </section>
}
