import { useEffect, useMemo, useRef, useState } from "react";
import { BadgeCheck, BookOpen, ChevronLeft, ChevronRight, Download, ExternalLink, FileText, Headphones, LockKeyhole, Mail, Play, School, Video } from "lucide-react";
import { toast } from "sonner";
import {
  listenToCollection, listenToIbrProgress, loadPwaMemberProfile, saveIbrProgress,
  type PwaMemberProfile,
} from "@/lib/firebase";
import {
  resolveDisplayImageUrl, resolvePdfEmbedUrl, resolvePortableAssetUrl, safeFilename, youtubeVideoId,
} from "@/lib/parity-utils";
import type { PwaSessionLike } from "./AndroidParityViews";
import "./AndroidParityViews.css";

type Chapter = { id:string; title?:string; description?:string; durationMinutes?:number; type?:string; videoUrl?:string; audioUrl?:string; textContent?:string; isYoutube?:boolean; youtube?:boolean; youtubeId?:string; studyPdfUrl?:string };
type Course = { id:string; title?:string; theme?:string; description?:string; imageUrl?:string; chapters?:Chapter[] };
type Progress = { id:string; courseId:string; chapterId:string; lastPositionSeconds?:number; totalDurationSeconds?:number; isCompleted?:boolean };

export function IbrParityView({ session, onLogin }: { session: PwaSessionLike; onLogin: () => void }) {
  const[courses,setCourses]=useState<Course[]>([]);const[progress,setProgress]=useState<Progress[]>([]);const[profile,setProfile]=useState<PwaMemberProfile|null>(null);const[profileError,setProfileError]=useState("");
  const[courseId,setCourseId]=useState<string|null>(null);const[lessonKey,setLessonKey]=useState<{courseId:string;chapterId:string}|null>(null);
  const sessionAccess=Boolean(session&&(session.isIbr||session.isAdmin));
  useEffect(()=>sessionAccess?listenToCollection<Course>("ibr_courses",setCourses,()=>setCourses([])):()=>undefined,[sessionAccess]);
  useEffect(()=>{if(!session)return;let active=true;setProfileError("");loadPwaMemberProfile().then(value=>{if(active)setProfile(value)}).catch(error=>{if(active)setProfileError(error instanceof Error?error.message:"Não foi possível carregar seu perfil IBR.")});return()=>{active=false}},[session?.uid]);
  const memberId=profile?.id||session?.uid||"";const access=Boolean(sessionAccess||(profile&&(profile.isIbr||profile.isAdmin)));
  useEffect(()=>memberId&&access?listenToIbrProgress<Progress>(memberId,setProgress,()=>setProgress([])):()=>undefined,[memberId,access]);
  if(!session)return <section className="parity-page"><div className="parity-empty"><School size={46}/><h1>Instituto Bíblico Rhema</h1><p>Entre para acessar sua matrícula, cursos e progresso.</p><button className="parity-primary" onClick={onLogin}>Entrar para acessar</button></div></section>;
  if(!access)return <section className="parity-page"><div className="parity-empty"><LockKeyhole size={46}/><h1>Instituto Bíblico Rhema</h1><p>Você não está matriculado no IBR. Procure a secretaria para mais informações.</p><button className="parity-primary" onClick={onLogin}>Ver meu perfil</button></div></section>;
  if(profileError&&session.isAdmin&&session.uid==="admin")return <section className="parity-page"><div className="parity-empty"><School size={46}/><h1>Renove a sessão do Administrador</h1><p>O IBR agora usa o mesmo ID do perfil Android. Saia e entre novamente como administrador uma única vez para concluir a vinculação.</p><button className="parity-primary" onClick={onLogin}>Abrir perfil</button></div></section>;

  const ordered=courses.slice().sort((a,b)=>String(a.id).localeCompare(String(b.id),undefined,{numeric:true}));
  const progressFor=(course:string,chapter:string)=>progress.find(item=>item.courseId===course&&item.chapterId===chapter);
  const completeCourse=(course:Course)=>Boolean(course.chapters?.length)&&course.chapters!.every(chapter=>progressFor(course.id,chapter.id)?.isCompleted);
  const courseLocked=(index:number)=>index>0&&!completeCourse(ordered[index-1]);
  const selectedCourse=ordered.find(item=>item.id===courseId)||null;
  const lessonCourse=lessonKey?ordered.find(item=>item.id===lessonKey.courseId)||null:null;
  const lesson=lessonCourse?.chapters?.find(item=>item.id===lessonKey?.chapterId)||null;
  const completedModules=ordered.filter(completeCourse).length;const percent=ordered.length?Math.round(completedModules/ordered.length*100):0;
  const completedMinutes=ordered.reduce((sum,course)=>sum+(course.chapters||[]).filter(chapter=>progressFor(course.id,chapter.id)?.isCompleted).reduce((inner,chapter)=>inner+Number(chapter.durationMinutes||0),0),0);
  const nextLesson=useMemo(()=>{
    for(let index=0;index<ordered.length;index++){
      if(index>0&&!completeCourse(ordered[index-1]))break;
      const course=ordered[index];const started=(course.chapters||[]).find(chapter=>{const item=progressFor(course.id,chapter.id);return item&&Number(item.lastPositionSeconds||0)>0&&!item.isCompleted});
      if(started)return{course,chapter:started};const pending=(course.chapters||[]).find(chapter=>!progressFor(course.id,chapter.id)?.isCompleted);if(pending)return{course,chapter:pending};
    }
    return null;
  },[ordered,progress]);
  const openLesson=async(course:Course,chapter:Chapter)=>{if(!memberId)return;const current=progressFor(course.id,chapter.id);if(!current){await saveIbrProgress(memberId,{courseId:course.id,chapterId:chapter.id,lastPositionSeconds:1,totalDurationSeconds:Number(chapter.durationMinutes||0)*60,isCompleted:false}).catch(()=>undefined);}setLessonKey({courseId:course.id,chapterId:chapter.id})};
  const complete=async()=>{if(!lessonCourse||!lesson||!memberId)return;try{await saveIbrProgress(memberId,{courseId:lessonCourse.id,chapterId:lesson.id,lastPositionSeconds:Number(lesson.durationMinutes||0)*60,totalDurationSeconds:Number(lesson.durationMinutes||0)*60,isCompleted:true});toast.success("Aula concluída e sincronizada com o Android.");}catch(error){toast.error(error instanceof Error?error.message:"Não foi possível salvar o progresso.")}};

  if(lessonCourse&&lesson)return <IbrLesson course={lessonCourse} lesson={lesson} done={Boolean(progressFor(lessonCourse.id,lesson.id)?.isCompleted)} onBack={()=>setLessonKey(null)} onComplete={()=>void complete()}/>;
  if(selectedCourse){const index=ordered.findIndex(item=>item.id===selectedCourse.id);if(courseLocked(index)){setCourseId(null);return null;}return <section className="parity-page"><button className="back-link" onClick={()=>setCourseId(null)}><ChevronLeft size={18}/> Voltar ao IBR</button><div className="parity-title"><div><p>{selectedCourse.theme||"MÓDULO IBR"}</p><h1>{selectedCourse.title||"Curso IBR"}</h1><span>{selectedCourse.description||"Formação bíblica"}</span></div><School size={30}/></div>{resolveDisplayImageUrl(selectedCourse.imageUrl)&&<img src={resolveDisplayImageUrl(selectedCourse.imageUrl)} alt="" style={{width:"100%",maxHeight:210,objectFit:"cover",borderRadius:18,marginBottom:15}}/>}<div className="android-list-cards">{(selectedCourse.chapters||[]).map((chapter,lessonIndex)=>{const done=Boolean(progressFor(selectedCourse.id,chapter.id)?.isCompleted);const type=(chapter.type||"AULA").toUpperCase();return <button key={chapter.id} onClick={()=>void openLesson(selectedCourse,chapter)}><span>{String(lessonIndex+1).padStart(2,"0")}</span><div><strong>{chapter.title||"Aula IBR"}</strong><small>{type==="VIDEO"?"Vídeo":type==="AUDIO"?"Áudio":type==="TEXT"?"Leitura":"Aula"} · {Number(chapter.durationMinutes||0)} min</small></div>{done?<BadgeCheck size={20}/>:<ChevronRight size={19}/>}</button>})}</div></section>}

  return <section className="parity-page"><div className="parity-title"><div><p>INSTITUTO BÍBLICO RHEMA</p><h1>Plataforma de Ensino IBR</h1><span>Mesmo progresso, cursos e materiais do Android.</span></div><School size={30}/></div>
    <article className="android-module-card" style={{padding:18,display:"grid",gap:11}}><strong>Progresso Geral</strong><div style={{fontSize:"1.8rem",fontWeight:900}}>{percent}% Concluído</div><div style={{height:8,borderRadius:99,overflow:"hidden",background:"rgba(128,128,128,.18)"}}><i style={{display:"block",height:"100%",width:`${percent}%`,background:"var(--pwa-primary,#8a6500)"}}/></div><div style={{display:"flex",justifyContent:"space-between",gap:12}}><small>{completedModules} módulo(s) concluído(s) · {Math.max(0,ordered.length-completedModules)} restante(s)</small><small>{Math.floor(completedMinutes/60)}h {completedMinutes%60}m de estudo concluído</small></div>{percent>=100&&profile?.ibrCertificateUrl?<><a className="parity-primary" href={profile.ibrCertificateUrl} target="_blank" rel="noreferrer"><BadgeCheck size={18}/> Ver Certificado</a>{profile.email&&<a className="back-link" href={`mailto:${encodeURIComponent(profile.email)}?subject=${encodeURIComponent("Certificado IBR MIC Rhema")}&body=${encodeURIComponent(`Meu certificado IBR: ${profile.ibrCertificateUrl}`)}`}><Mail size={17}/> Enviar por e-mail</a>}</>:<button className="back-link" disabled><LockKeyhole size={17}/> {percent>=100?"Certificado em processamento":"Certificado Bloqueado"}</button>}</article>
    {nextLesson&&<button className="android-module-card" style={{width:"100%",display:"flex",alignItems:"center",gap:12,padding:16,textAlign:"left",marginTop:14}} onClick={()=>void openLesson(nextLesson.course,nextLesson.chapter)}><Play size={24}/><div style={{flex:1}}><small>CONTINUAR ESTUDANDO</small><strong style={{display:"block"}}>{nextLesson.course.title}</strong><span>{nextLesson.chapter.title} · {Number(nextLesson.chapter.durationMinutes||0)} min</span></div><ChevronRight size={20}/></button>}
    {!ordered.length?<p className="parity-status">Nenhum módulo disponível.</p>:<div className="android-list-cards" style={{marginTop:16}}>{ordered.map((course,index)=>{const locked=courseLocked(index);const completed=completeCourse(course);const chapters=course.chapters||[];const finished=chapters.filter(ch=>progressFor(course.id,ch.id)?.isCompleted).length;const estimated=chapters.reduce((sum,ch)=>sum+Number(ch.durationMinutes||0),0);const cover=resolveDisplayImageUrl(course.imageUrl);return <button key={course.id} onClick={()=>locked?toast.info("Conclua o módulo anterior para desbloquear este."):setCourseId(course.id)} style={{opacity:locked?.58:1,alignItems:"center"}}>{cover?<img src={cover} alt="" style={{width:72,height:52,objectFit:"cover",borderRadius:10}}/>:<span>{locked?<LockKeyhole size={18}/>:<School size={18}/>}</span>}<div><strong>{course.title||"Curso IBR"}</strong><small>{course.theme||"Módulo"} · {finished}/{chapters.length} aulas · {estimated} min</small></div>{locked?<LockKeyhole size={19}/>:completed?<BadgeCheck size={20}/>:<ChevronRight size={19}/>}</button>})}</div>}
  </section>;
}

function IbrLesson({course,lesson,done,onBack,onComplete}:{course:Course;lesson:Chapter;done:boolean;onBack:()=>void;onComplete:()=>void}){
  const audioRef=useRef<HTMLAudioElement|null>(null);const type=(lesson.type||(lesson.textContent?"TEXT":lesson.videoUrl?"VIDEO":"AUDIO")).toUpperCase();const videoId=lesson.youtubeId||youtubeVideoId(lesson.videoUrl);const videoUrl=resolvePortableAssetUrl(lesson.videoUrl);const audioUrl=resolvePortableAssetUrl(lesson.audioUrl);const pdf=String(lesson.studyPdfUrl||"").trim();const pdfEmbed=resolvePdfEmbedUrl(pdf);const pdfDownload=resolvePortableAssetUrl(pdf);
  const downloadPdf=()=>{if(!pdfDownload)return;const a=document.createElement("a");a.href=pdfDownload;a.target="_blank";a.rel="noopener noreferrer";a.download=`${safeFilename(lesson.title||"material-ibr")}.pdf`;document.body.appendChild(a);a.click();a.remove()};
  const showManualComplete=type==="TEXT"||(type==="VIDEO"&&Boolean(videoId));
  return <section className="parity-page ibr-lesson-view"><button className="back-link" onClick={onBack}><ChevronLeft size={18}/> Voltar às aulas</button><div className="parity-title"><div><p>{course.title||"CURSO IBR"}</p><h1>{lesson.title||"Aula IBR"}</h1><span>{lesson.description||"Acompanhe a aula até o fim para registrar seu progresso."}</span></div></div>
    {type==="TEXT"?<article className="parity-reader">{String(lesson.textContent||"Nenhum conteúdo adicionado.").split(/\n{2,}/).map((p,i)=><p key={i}>{p}</p>)}</article>:type==="AUDIO"?<div className="audio-reader"><Headphones size={42}/><audio ref={audioRef} controls preload="metadata" src={audioUrl} onEnded={()=>!done&&onComplete()}>Seu navegador não suporta áudio.</audio><small>A aula é concluída ao terminar o áudio.</small></div>:videoId?<iframe className="parity-video" title={lesson.title||"Vídeo IBR"} src={`https://www.youtube-nocookie.com/embed/${videoId}?rel=0&playsinline=1`} allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowFullScreen/>:<video className="parity-video" controls playsInline preload="metadata" src={videoUrl} onEnded={()=>!done&&onComplete()}>Seu navegador não suporta vídeo.</video>}
    <div className="lesson-meta" style={{display:"flex",gap:10,margin:"14px 0"}}><span>{type==="VIDEO"?<Video size={15}/>:type==="AUDIO"?<Headphones size={15}/>:<BookOpen size={15}/>} {type==="VIDEO"?"Vídeo-aula":type==="AUDIO"?"Áudio-aula":"Leitura"}</span><span>{Number(lesson.durationMinutes||0)} min</span>{done&&<span><BadgeCheck size={15}/> Concluída</span>}</div>
    {showManualComplete&&<button className="parity-primary" disabled={done} onClick={onComplete}><BadgeCheck size={18}/>{done?"Aula concluída":type==="TEXT"?"Concluir leitura":"Concluir vídeo"}</button>}
    {pdf&&<section style={{marginTop:22,display:"grid",gap:10}}><p style={{fontWeight:800,margin:0}}>Conteúdos para estudo</p><article className="android-module-card" style={{display:"flex",alignItems:"center",gap:12,padding:16}}><FileText size={28}/><div style={{flex:1}}><strong style={{display:"block"}}>Material complementar em PDF</strong><small>Leia dentro da PWA ou baixe para estudar depois.</small></div><button className="back-link" onClick={downloadPdf}><Download size={18}/> Baixar</button></article>{pdfEmbed&&<iframe className="parity-document" style={{width:"100%",minHeight:"62dvh",border:0,borderRadius:16,background:"#fff"}} src={pdfEmbed} title="Material complementar IBR"/>}</section>}
    {type==="VIDEO"&&lesson.videoUrl&&<a className="back-link" style={{marginTop:14}} href={lesson.videoUrl} target="_blank" rel="noreferrer"><ExternalLink size={17}/> Abrir fonte do vídeo</a>}
  </section>;
}
