import { useEffect, useMemo, useState } from "react";
import { BookOpen, ChevronLeft, ChevronRight, Newspaper, Search, X } from "lucide-react";
import { listenToCollection } from "@/lib/firebase";
import { recordPwaActivity } from "@/lib/badge-activity";
import { contentTimestamp, normalizeSearch } from "@/lib/parity-utils";
import type { AppView } from "./PwaShell";
import "./AndroidParityViews.css";

type News={id:string;title?:string;summary?:string;content?:string;book?:string;chapter?:number;verse?:number|string;imageUrl?:string;category?:string;intensity?:number;tags?:string[];contentWarning?:string;featured?:boolean;publishedAt?:number;createdAt?:number;approved?:boolean;isApproved?:boolean};
function approved(item:News){return item.approved!==false&&item.isApproved!==false}
function generatedImage(item:News){const identity=[item.id,item.book,item.chapter,item.verse,item.title].filter(Boolean).join("-");let hash=0;for(const ch of identity)hash=(hash*31+ch.charCodeAt(0))>>>0;const prompt=`respectful symbolic black and white newspaper illustration, unique composition for ${identity}, biblical setting, non graphic, no violence, no text, editorial photography`;return `https://image.pollinations.ai/prompt/${encodeURIComponent(prompt)}?width=900&height=520&nologo=true&seed=${hash}`}
function imageMap(items:News[]){const used=new Set<string>();return new Map(items.map(item=>{const configured=String(item.imageUrl||"").trim();if(configured&&!used.has(configured)){used.add(configured);return[item.id,configured]}return[item.id,generatedImage(item)]}))}

export function NewsParityView({onNavigate}:{onNavigate:(view:AppView)=>void}){
  const[items,setItems]=useState<News[]>([]);const[query,setQuery]=useState("");const[category,setCategory]=useState("Todas");const[selected,setSelected]=useState<News|null>(null);
  useEffect(()=>listenToCollection<News>("bible_news",setItems,()=>setItems([])),[]);
  const approvedItems=useMemo(()=>items.filter(approved).sort((a,b)=>contentTimestamp(b as unknown as Record<string,unknown>)-contentTimestamp(a as unknown as Record<string,unknown>)),[items]);
  const categories=useMemo(()=>["Todas",...Array.from(new Set(approvedItems.map(item=>item.category).filter(Boolean) as string[])).sort((a,b)=>a.localeCompare(b,"pt-BR"))],[approvedItems]);
  const images=useMemo(()=>imageMap(approvedItems),[approvedItems]);
  const visible=useMemo(()=>approvedItems.filter(item=>category==="Todas"||item.category===category).filter(item=>{if(!query.trim())return true;const q=normalizeSearch(query);return normalizeSearch([item.title,item.summary,item.content,item.book,item.category,(item.tags||[]).join(" ")].filter(Boolean).join(" ")).includes(q)}),[approvedItems,category,query]);
  const openBible=(item:News)=>{if(!item.book||!item.chapter)return;localStorage.setItem("micrhema:pwa:bible-target",JSON.stringify({book:item.book,chapter:Number(item.chapter),verse:Number(item.verse||0)}));onNavigate("bible")};
  const openNews=(item:News)=>{setSelected(item);void recordPwaActivity("bible_news",item.id).catch(()=>undefined);};
  if(selected)return <section className="parity-page"><button className="back-link" onClick={()=>setSelected(null)}><ChevronLeft size={18}/> Voltar às notícias</button>{images.get(selected.id)&&<img src={images.get(selected.id)} alt="" style={{width:"100%",aspectRatio:"16/9",objectFit:"cover",borderRadius:18,filter:"grayscale(1)",marginBottom:16}}/>}<div className="parity-title"><div><p>{selected.category||"NOTÍCIA BÍBLICA"}</p><h1>{selected.title||"Notícia Bíblica"}</h1><span>{selected.book?`${selected.book} ${selected.chapter||""}${selected.verse?`:${selected.verse}`:""}`:""}</span></div><Newspaper size={30}/></div>{selected.contentWarning&&<p className="parity-warning">Atenção: {selected.contentWarning}</p>}<article className="parity-reader">{String(selected.content||selected.summary||"Conteúdo não disponível.").split(/\n{2,}/).map((part,index)=><p key={index}>{part}</p>)}</article>{selected.book&&selected.chapter&&<button className="parity-primary" onClick={()=>openBible(selected)}><BookOpen size={18}/> Ir para a história na Bíblia</button>}</section>;
  return <section className="parity-page"><div className="parity-title"><div><p>NOTÍCIAS BÍBLICAS</p><h1>Notícias Bíblicas</h1><span>Histórias, contexto e aplicações organizadas como no Android.</span></div><Newspaper size={30}/></div><label style={{display:"flex",alignItems:"center",gap:8,border:"1px solid #aaa",borderRadius:18,padding:"0 12px",minHeight:48}}><Search size={18}/><input value={query} onChange={event=>setQuery(event.target.value)} placeholder="Buscar por título, tema, livro ou conteúdo..." style={{flex:1,border:0,outline:0,background:"transparent",color:"inherit"}}/>{query&&<button onClick={()=>setQuery("")} style={{border:0,background:"transparent",color:"inherit"}}><X size={18}/></button>}</label><div className="filter-pills" style={{marginTop:12,overflowX:"auto"}}>{categories.map(value=><button key={value} className={category===value?"selected":""} onClick={()=>setCategory(value)}>{value}</button>)}</div>{!visible.length?<p className="parity-status">Nenhuma notícia encontrada.</p>:<div className="android-list-cards android-news-list" style={{marginTop:14}}>{visible.map(item=><button key={item.id} onClick={()=>openNews(item)}>{images.get(item.id)&&<img src={images.get(item.id)} alt="" style={{width:94,height:72,objectFit:"cover",borderRadius:12,filter:"grayscale(1)"}}/>}<div><strong>{item.title||"Notícia Bíblica"}</strong><small>{item.category||"Para refletir"}{item.book?` · ${item.book} ${item.chapter||""}${item.verse?`:${item.verse}`:""}`:""}</small></div><ChevronRight size={19}/></button>)}</div>}</section>;
}
