import { useEffect, useMemo, useState } from "react";
import { Eye, Pencil, Plus, RefreshCcw, Save, Sparkles, TestTube2, Trash2, X } from "lucide-react";
import { toast } from "sonner";
import { biblicalBadges } from "./BiblicalBadgeCatalog";
import { PwaProfileShowcase } from "./PwaProfileCustomization";
import {
  applyReleaseMode, deleteAdminLightEffect, loadAdminBadges, loadAdminLightEffects, releaseMode, saveAdminLightEffect,
  type AdminCustomBadge, type AdminLightEffect, type ReleaseMode,
} from "@/lib/xp-admin";
import type { PwaLightEffect, PwaProfileSelections } from "@/lib/profile-customization";

const PAGE_SIZE=10;
const EFFECT_TYPES=["orbit","stars","flame","pulse","particles","halo","fire_ring","rays","dust","halo_orbit","electric","aura","violet_flame","rainbow_orbit","spirit_light"];
const emptyEffect=():AdminLightEffect=>({id:"",name:"",description:"",effectType:"orbit",tone:"medio",colorHex:"#FFD54F",purchasable:true,xpCost:400,emblemIds:[],active:true,freeForAll:false});
const slug=(value:string)=>value.normalize("NFD").replace(/[\u0300-\u036f]/g,"").toLowerCase().replace(/[^a-z0-9]+/g,"_").replace(/^_+|_+$/g,"").slice(0,70);
function toPreview(item:AdminLightEffect):PwaLightEffect{return {id:item.id||"preview",name:item.name||"Prévia",description:item.description,effect_type:item.effectType,tone:item.tone,color_hex:item.colorHex,purchasable:item.purchasable,xp_cost:item.xpCost,emblem_ids:item.emblemIds,active:item.active,free_for_all:item.freeForAll}}

function EffectPreview({item,testMode,onClose}:{item:AdminLightEffect;testMode:boolean;onClose:()=>void}){
  const effect=toPreview(item); const selections:PwaProfileSelections={primaryDistinctiveId:"",featuredDistinctiveIds:[],selectedProfileFrameId:"",selectedProfileEffectId:effect.id};
  return <div className="xp-admin-modal-backdrop" onMouseDown={onClose}><article className="xp-admin-modal xp-admin-preview" onMouseDown={(e)=>e.stopPropagation()}><header><div><small>{testMode?"MODO TESTE":"PRÉVIA DO EFEITO"}</small><h2>{item.name||"Novo efeito"}</h2></div><button onClick={onClose}><X size={20}/></button></header><div className="xp-admin-profile-preview"><PwaProfileShowcase avatarId="davi" badgeId="caminhante" size={200} effect={effect} selections={selections}/></div><div className="xp-admin-preview-info"><strong>{item.tone==="forte"?"Luz forte":item.tone==="suave"?"Suave":"Médio"} · {releaseMode(item)==="shop"?`${item.xpCost} XP`:releaseMode(item)==="free"?"Gratuito p/ Todos":"Emblema / ADM"}</strong><p>{item.description}</p>{testMode&&<em>O teste é somente visual. Nada será aplicado no perfil do administrador.</em>}</div><button className="xp-admin-secondary" onClick={onClose}>Fechar</button></article></div>;
}

function EffectEditor({initial,badgeOptions,onClose,onSaved}:{initial:AdminLightEffect|null;badgeOptions:Array<{id:string;name:string}>;onClose:()=>void;onSaved:()=>void}){
  const [draft,setDraft]=useState<AdminLightEffect>(initial?{...initial,emblemIds:[...initial.emblemIds]}:emptyEffect()); const [mode,setMode]=useState<ReleaseMode>(()=>initial?releaseMode(initial):"shop"); const [busy,setBusy]=useState(false); const [previewMode,setPreviewMode]=useState<"preview"|"test"|null>(null);
  const set=<K extends keyof AdminLightEffect>(key:K,value:AdminLightEffect[K])=>setDraft((current)=>({...current,[key]:value})); const toggleEmblem=(id:string)=>setDraft((current)=>({...current,emblemIds:current.emblemIds.includes(id)?current.emblemIds.filter((value)=>value!==id):[...current.emblemIds,id]}));
  const save=async()=>{const id=slug(draft.id||draft.name);if(!id||!draft.name.trim()){toast.error("Informe o nome do efeito.");return;}if(!/^#[0-9A-Fa-f]{6}$/.test(draft.colorHex)){toast.error("Use uma cor no formato #RRGGBB.");return;}const next=applyReleaseMode({...draft,id,name:draft.name.trim(),description:draft.description.trim(),colorHex:draft.colorHex.toUpperCase()},mode);if(mode==="shop"&&next.xpCost<=0){toast.error("Informe um valor em XP maior que zero.");return;}if(mode==="emblem"&&!next.emblemIds.length){toast.error("Escolha ao menos um emblema.");return;}setBusy(true);try{await saveAdminLightEffect(next);toast.success("Efeito de luz salvo e sincronizado.");onSaved();onClose();}catch(error){toast.error(error instanceof Error?error.message:"Não foi possível salvar o efeito.");}finally{setBusy(false)}};
  const previewItem=applyReleaseMode(draft,mode);
  return <><div className="xp-admin-modal-backdrop" onMouseDown={onClose}><article className="xp-admin-modal" onMouseDown={(e)=>e.stopPropagation()}><header><div><small>EFEITOS DE LUZ</small><h2>{initial?"Editar efeito":"Novo efeito"}</h2></div><button onClick={onClose}><X size={20}/></button></header><div className="xp-admin-form-grid"><label>Identificador<input value={draft.id} disabled={Boolean(initial)} placeholder="automático pelo nome" onChange={(e)=>set("id",e.target.value)}/></label><label>Nome<input value={draft.name} onChange={(e)=>set("name",e.target.value)}/></label><label className="wide">Descrição<textarea value={draft.description} onChange={(e)=>set("description",e.target.value)}/></label><label>Tipo do efeito<select value={draft.effectType} onChange={(e)=>set("effectType",e.target.value)}>{EFFECT_TYPES.map((type)=><option key={type} value={type}>{type.replaceAll("_"," ")}</option>)}</select></label><label>Intensidade<select value={draft.tone} onChange={(e)=>set("tone",e.target.value as AdminLightEffect["tone"])}><option value="suave">Suave</option><option value="medio">Médio</option><option value="forte">Luz forte</option></select></label><label>Cor<input type="color" value={draft.colorHex} onChange={(e)=>set("colorHex",e.target.value.toUpperCase())}/></label><label>Hexadecimal<input value={draft.colorHex} maxLength={7} onChange={(e)=>set("colorHex",e.target.value)}/></label></div><div className="xp-admin-release"><strong>Forma de liberação</strong><div>{(["shop","free","emblem"] as ReleaseMode[]).map((value)=><button key={value} className={mode===value?"selected":""} onClick={()=>setMode(value)}>{value==="shop"?"Venda na Loja XP":value==="free"?"Gratuito p/ Todos":"Vinculado a emblema / ADM"}</button>)}</div></div>{mode==="shop"&&<label className="xp-admin-single-field">Valor em XP<input type="number" min="1" value={draft.xpCost} onChange={(e)=>set("xpCost",Math.max(1,Number(e.target.value)||1))}/></label>}{mode==="emblem"&&<div className="xp-admin-emblem-links"><strong>Emblemas que liberam este efeito</strong><div>{badgeOptions.map((badge)=><label key={badge.id}><input type="checkbox" checked={draft.emblemIds.includes(badge.id)} onChange={()=>toggleEmblem(badge.id)}/><span>{badge.name}</span></label>)}</div></div>}<label className="xp-admin-check"><input type="checkbox" checked={draft.active} onChange={(e)=>set("active",e.target.checked)}/> Efeito ativo</label><div className="xp-admin-modal-actions"><button className="xp-admin-secondary" onClick={()=>setPreviewMode("preview")}><Eye size={17}/> Prévia</button><button className="xp-admin-secondary" onClick={()=>setPreviewMode("test")}><TestTube2 size={17}/> Testar</button><button className="parity-primary" disabled={busy} onClick={()=>void save()}><Save size={17}/>{busy?"Salvando…":"Salvar efeito"}</button></div></article></div>{previewMode&&<EffectPreview item={previewItem} testMode={previewMode==="test"} onClose={()=>setPreviewMode(null)}/>}</>;
}

export function PwaXpAdminEffects(){
  const [items,setItems]=useState<AdminLightEffect[]>([]);const [badges,setBadges]=useState<AdminCustomBadge[]>([]);const [loading,setLoading]=useState(true);const [editor,setEditor]=useState<AdminLightEffect|null|undefined>(undefined);const [preview,setPreview]=useState<{item:AdminLightEffect;test:boolean}|null>(null);const [page,setPage]=useState(0);
  const load=async()=>{setLoading(true);try{const [effects,customBadges]=await Promise.all([loadAdminLightEffects(),loadAdminBadges()]);setItems(effects);setBadges(customBadges)}catch(error){toast.error(error instanceof Error?error.message:"Falha ao carregar efeitos de luz.");}finally{setLoading(false)}};useEffect(()=>{void load()},[]);
  const badgeOptions=useMemo(()=>{const map=new Map<string,string>();biblicalBadges.forEach((item)=>map.set(item.id,item.name));badges.forEach((item)=>map.set(item.id,item.name));return [...map].map(([id,name])=>({id,name}))},[badges]);const total=Math.max(1,Math.ceil(items.length/PAGE_SIZE));const safe=Math.min(page,total-1);const visible=items.slice(safe*PAGE_SIZE,(safe+1)*PAGE_SIZE);
  const remove=async(item:AdminLightEffect)=>{if(!window.confirm(`Excluir o efeito ${item.name}? Ele será removido do catálogo e desativado na Loja XP.`))return;try{await deleteAdminLightEffect(item.id);toast.success("Efeito excluído.");await load()}catch(error){toast.error(error instanceof Error?error.message:"Não foi possível excluir.")}};
  return <section className="xp-admin-section"><div className="xp-admin-section-head"><div><h2>Efeitos de Luz</h2><p>Gerencie os mesmos efeitos 360° usados pelo Android, com intensidade e forma de liberação.</p></div><button className="parity-primary" onClick={()=>setEditor(null)}><Plus size={18}/> Novo efeito</button></div>{loading?<p className="parity-status">Carregando efeitos…</p>:<div className="xp-admin-cards">{visible.map((item)=><article key={item.id}><div className="xp-admin-card-main"><div><small>{item.effectType.replaceAll("_"," ")} · {item.tone}</small><strong>{item.name}</strong><p>{item.description}</p></div><span className="xp-admin-effect-swatch" style={{background:item.colorHex,boxShadow:`0 0 18px ${item.colorHex}`}}><Sparkles size={20}/></span></div><div className="xp-admin-card-meta"><span>{releaseMode(item)==="shop"?`${item.xpCost} XP`:releaseMode(item)==="free"?"Gratuito p/ Todos":`${item.emblemIds.length} vínculo(s)`}</span><span>{item.active?"Ativo":"Inativo"}</span></div><div className="xp-admin-card-actions"><button onClick={()=>setPreview({item,test:false})}><Eye size={16}/> Prévia</button><button onClick={()=>setPreview({item,test:true})}><TestTube2 size={16}/> Testar</button><button onClick={()=>setEditor(item)}><Pencil size={16}/> Editar</button><button className="danger" onClick={()=>void remove(item)}><Trash2 size={16}/> Excluir</button></div></article>)}</div>}<div className="xp-admin-pagination"><button disabled={safe===0} onClick={()=>setPage(Math.max(0,safe-1))}>Anterior</button><strong>{safe+1}/{total}</strong><button disabled={safe>=total-1} onClick={()=>setPage(Math.min(total-1,safe+1))}>Próxima</button></div><button className="xp-admin-refresh" onClick={()=>void load()}><RefreshCcw size={16}/> Atualizar</button>{editor!==undefined&&<EffectEditor initial={editor} badgeOptions={badgeOptions} onClose={()=>setEditor(undefined)} onSaved={()=>void load()}/>} {preview&&<EffectPreview item={preview.item} testMode={preview.test} onClose={()=>setPreview(null)}/>}</section>;
}
