import { useEffect, useMemo, useState } from "react";
import { BadgeCheck, Eye, Pencil, Plus, RefreshCcw, Save, ShieldCheck, Sparkles, Star, TestTube2, Upload, X } from "lucide-react";
import { toast } from "sonner";
import { uploadAdminMedia } from "@/lib/admin-storage";
import { resolvePwaXpAssetUrl, type PwaProfileCosmetic, type PwaProfileSelections } from "@/lib/profile-customization";
import {
  applyReleaseMode, buildAdminXpAssetRef, generateAdminBadgeChallenge, isBuiltinCosmeticId,
  loadAdminBadges, loadAdminCosmetics, releaseMode, saveAdminBadge, saveAdminCosmetic,
  type AdminCustomBadge, type AdminProfileCosmetic, type ReleaseMode,
} from "@/lib/xp-admin";
import { biblicalBadges } from "./BiblicalBadgeCatalog";
import { BiblicalBadgeAvatar } from "./BiblicalBadgeAvatar";
import { PwaProfileShowcase } from "./PwaProfileCustomization";

const PAGE_SIZE=10;
const emptyBadge=():AdminCustomBadge=>({id:"",sequenceNo:null,name:"",description:"",challenge:"",imageRef:"",special:false,active:true});
const emptyCosmetic=(kind:"distintivo"|"moldura"):AdminProfileCosmetic=>({id:"",kind,name:"",description:"",challenge:"",imageRef:"",active:true,purchasable:true,xpCost:100,emblemIds:[],freeForAll:false});

function ChallengePicker({value,onChange}:{value:string;onChange:(value:string)=>void}){
  const [difficulty,setDifficulty]=useState<"easy"|"medium"|"hard">("easy"); const [busy,setBusy]=useState(false);
  const generate=async()=>{setBusy(true);try{const result=await generateAdminBadgeChallenge(difficulty,value);onChange(result.text);toast.success("Novo desafio gerado.");}catch(error){toast.error(error instanceof Error?error.message:"Não foi possível gerar o desafio.");}finally{setBusy(false)}};
  return <div className="xp-admin-challenge"><label>Dificuldade<select value={difficulty} onChange={(e)=>setDifficulty(e.target.value as "easy"|"medium"|"hard")}><option value="easy">Fácil</option><option value="medium">Médio</option><option value="hard">Difícil</option></select></label><button className="xp-admin-secondary" disabled={busy} onClick={()=>void generate()}><Sparkles size={16}/>{busy?"Gerando…":"Gerar desafio"}</button>{value&&<p>{value}</p>}</div>;
}

function BadgePreview({item,onClose}:{item:AdminCustomBadge;onClose:()=>void}){
  const url=resolvePwaXpAssetUrl(item.imageRef); const badgeId=item.id||"caminhante";
  return <div className="xp-admin-modal-backdrop" onMouseDown={onClose}><article className="xp-admin-modal xp-admin-preview" onMouseDown={(e)=>e.stopPropagation()}><header><div><small>PRÉVIA DO EMBLEMA</small><h2>{item.name||"Novo emblema"}</h2></div><button onClick={onClose}><X size={20}/></button></header><div className="xp-admin-profile-preview">{url?<img src={url} alt={item.name}/>:<BiblicalBadgeAvatar avatarId="davi" badgeId={badgeId} size={190} title={item.name}/>}</div><div className="xp-admin-preview-info"><strong>{item.special?"Especial":item.sequenceNo?`Nível ${item.sequenceNo}`:"Próximo nível"}</strong><p>{item.description}</p>{item.challenge&&<em>Desafio: {item.challenge}</em>}</div><button className="xp-admin-secondary" onClick={onClose}>Fechar</button></article></div>;
}

function BadgeEditor({initial,onClose,onSaved}:{initial:AdminCustomBadge|null;onClose:()=>void;onSaved:()=>void}){
  const [draft,setDraft]=useState<AdminCustomBadge>(initial?{...initial}:emptyBadge()); const [busy,setBusy]=useState(false); const [preview,setPreview]=useState(false);
  const set=<K extends keyof AdminCustomBadge>(key:K,value:AdminCustomBadge[K])=>setDraft((current)=>({...current,[key]:value}));
  const upload=async(file:File)=>{setBusy(true);try{const result=await uploadAdminMedia(file);set("imageRef",buildAdminXpAssetRef("emblem",result.storagePath));toast.success("PNG do emblema enviado.");}catch(error){toast.error(error instanceof Error?error.message:"Falha no upload.");}finally{setBusy(false)}};
  const save=async()=>{if(!draft.name.trim()){toast.error("Informe o nome do emblema.");return;}if(!draft.challenge.trim()){toast.error("Gere um desafio antes de salvar.");return;}if(!draft.imageRef.trim()){toast.error("Envie o PNG do emblema antes de salvar.");return;}setBusy(true);try{await saveAdminBadge({...draft,name:draft.name.trim(),description:draft.description.trim()});toast.success("Emblema salvo e sincronizado.");onSaved();onClose();}catch(error){toast.error(error instanceof Error?error.message:"Não foi possível salvar o emblema.");}finally{setBusy(false)}};
  return <><div className="xp-admin-modal-backdrop" onMouseDown={onClose}><article className="xp-admin-modal" onMouseDown={(e)=>e.stopPropagation()}><header><div><small>EMBLEMAS</small><h2>{initial?"Editar emblema":"Novo emblema"}</h2></div><button onClick={onClose}><X size={20}/></button></header><div className="xp-admin-form-grid"><label>Identificador<input value={draft.id} disabled={Boolean(initial)} placeholder="automático" onChange={(e)=>set("id",e.target.value)}/></label><label>Nível / ordem<input type="number" min="1" value={draft.sequenceNo??""} placeholder="automático" onChange={(e)=>set("sequenceNo",e.target.value===""?null:Number(e.target.value))}/></label><label>Nome<input value={draft.name} onChange={(e)=>set("name",e.target.value)}/></label><label className="wide">Descrição<textarea value={draft.description} onChange={(e)=>set("description",e.target.value)}/></label></div><ChallengePicker value={draft.challenge} onChange={(value)=>set("challenge",value)}/><div className="xp-admin-upload"><label className="xp-admin-file"><Upload size={18}/><span>{busy?"Enviando…":"Enviar emblema PNG"}</span><input type="file" accept="image/png" disabled={busy} onChange={(e)=>{const file=e.target.files?.[0];if(file)void upload(file);e.currentTarget.value=""}}/></label>{draft.imageRef&&<small>Imagem cadastrada.</small>}</div><div className="xp-admin-inline-checks"><label className="xp-admin-check"><input type="checkbox" checked={draft.special} onChange={(e)=>set("special",e.target.checked)}/> Emblema especial</label><label className="xp-admin-check"><input type="checkbox" checked={draft.active} onChange={(e)=>set("active",e.target.checked)}/> Ativo</label></div><div className="xp-admin-modal-actions"><button className="xp-admin-secondary" onClick={()=>setPreview(true)}><Eye size={17}/> Prévia</button><button className="parity-primary" disabled={busy} onClick={()=>void save()}><Save size={17}/>{busy?"Salvando…":"Salvar"}</button></div></article></div>{preview&&<BadgePreview item={draft} onClose={()=>setPreview(false)}/>}</>;
}

export function PwaXpAdminBadges(){
  const [items,setItems]=useState<AdminCustomBadge[]>([]); const [loading,setLoading]=useState(true); const [editor,setEditor]=useState<AdminCustomBadge|null|undefined>(undefined); const [preview,setPreview]=useState<AdminCustomBadge|null>(null); const [page,setPage]=useState(0);
  const load=async()=>{setLoading(true);try{setItems(await loadAdminBadges())}catch(error){toast.error(error instanceof Error?error.message:"Falha ao carregar emblemas.");}finally{setLoading(false)}}; useEffect(()=>{void load()},[]);
  const total=Math.max(1,Math.ceil(items.length/PAGE_SIZE)); const safe=Math.min(page,total-1); const visible=items.slice(safe*PAGE_SIZE,(safe+1)*PAGE_SIZE);
  return <section className="xp-admin-section"><div className="xp-admin-section-head"><div><h2>Emblemas</h2><p>Cadastre níveis e emblemas especiais com desafio verificável.</p></div><button className="parity-primary" onClick={()=>setEditor(null)}><Plus size={18}/> Novo emblema</button></div>{loading?<p className="parity-status">Carregando emblemas…</p>:<div className="xp-admin-cards">{visible.map((item)=><article key={item.id}><div className="xp-admin-card-main"><div><small>{item.special?"Especial":item.sequenceNo?`Nível ${item.sequenceNo}`:"Emblema"}</small><strong>{item.name}</strong><p>{item.challenge}</p></div><span className="xp-admin-card-icon"><BadgeCheck size={24}/></span></div><div className="xp-admin-card-meta"><span>{item.active?"Ativo":"Inativo"}</span><span>{item.imageRef?"PNG configurado":"Sem imagem"}</span></div><div className="xp-admin-card-actions"><button onClick={()=>setPreview(item)}><Eye size={16}/> Prévia</button><button onClick={()=>setEditor(item)}><Pencil size={16}/> Editar</button></div></article>)}</div>}<div className="xp-admin-pagination"><button disabled={safe===0} onClick={()=>setPage(Math.max(0,safe-1))}>Anterior</button><strong>{safe+1}/{total}</strong><button disabled={safe>=total-1} onClick={()=>setPage(Math.min(total-1,safe+1))}>Próxima</button></div><button className="xp-admin-refresh" onClick={()=>void load()}><RefreshCcw size={16}/> Atualizar</button>{editor!==undefined&&<BadgeEditor initial={editor} onClose={()=>setEditor(undefined)} onSaved={()=>void load()}/>} {preview&&<BadgePreview item={preview} onClose={()=>setPreview(null)}/>}</section>;
}

function toPreviewCosmetic(item:AdminProfileCosmetic):PwaProfileCosmetic{return {id:item.id,kind:item.kind,name:item.name,description:item.description,challenge:item.challenge,image_ref:item.imageRef,active:item.active,purchasable:item.purchasable,xp_cost:item.xpCost,emblem_ids:item.emblemIds,free_for_all:item.freeForAll}}
function CosmeticPreview({item,testMode,onClose}:{item:AdminProfileCosmetic;testMode:boolean;onClose:()=>void}){
  const preview=toPreviewCosmetic(item); const selections:PwaProfileSelections={primaryDistinctiveId:item.kind==="distintivo"?item.id:"",featuredDistinctiveIds:[],selectedProfileFrameId:item.kind==="moldura"?item.id:"",selectedProfileEffectId:""};
  return <div className="xp-admin-modal-backdrop" onMouseDown={onClose}><article className="xp-admin-modal xp-admin-preview" onMouseDown={(e)=>e.stopPropagation()}><header><div><small>{testMode?"MODO TESTE":"PRÉVIA NO PERFIL"}</small><h2>{item.name||"Personalização"}</h2></div><button onClick={onClose}><X size={20}/></button></header><div className="xp-admin-profile-preview"><PwaProfileShowcase avatarId="davi" badgeId="caminhante" size={190} distinctives={item.kind==="distintivo"?[preview]:[]} frame={item.kind==="moldura"?preview:null} selections={selections}/></div><div className="xp-admin-preview-info"><strong>{releaseMode(item)==="shop"?`${item.xpCost} XP`:releaseMode(item)==="free"?"Gratuito p/ Todos":"Vinculado a emblema"}</strong><p>{item.description}</p>{testMode&&<em>Modo teste: esta visualização não libera nem equipa o item para nenhum usuário.</em>}</div><button className="xp-admin-secondary" onClick={onClose}>Fechar</button></article></div>;
}

function CosmeticEditor({kind,initial,badgeOptions,onClose,onSaved}:{kind:"distintivo"|"moldura";initial:AdminProfileCosmetic|null;badgeOptions:Array<{id:string;name:string}>;onClose:()=>void;onSaved:()=>void}){
  const [draft,setDraft]=useState<AdminProfileCosmetic>(initial?{...initial,emblemIds:[...initial.emblemIds]}:emptyCosmetic(kind)); const [mode,setMode]=useState<ReleaseMode>(()=>initial?releaseMode(initial):"shop"); const [busy,setBusy]=useState(false); const [previewMode,setPreviewMode]=useState<"preview"|"test"|null>(null); const builtin=isBuiltinCosmeticId(draft.id);
  const set=<K extends keyof AdminProfileCosmetic>(key:K,value:AdminProfileCosmetic[K])=>setDraft((current)=>({...current,[key]:value})); const effectiveMode=builtin?"shop":mode;
  const upload=async(file:File)=>{setBusy(true);try{const result=await uploadAdminMedia(file);set("imageRef",buildAdminXpAssetRef(kind==="moldura"?"frame":"badge",result.storagePath));toast.success("PNG enviado ao Supabase.");}catch(error){toast.error(error instanceof Error?error.message:"Falha no upload.");}finally{setBusy(false)}};
  const toggleEmblem=(id:string)=>setDraft((current)=>({...current,emblemIds:current.emblemIds.includes(id)?current.emblemIds.filter((value)=>value!==id):[...current.emblemIds,id]}));
  const save=async()=>{if(!draft.name.trim()){toast.error("Informe o nome.");return;}let challenge=draft.challenge;setBusy(true);try{if(!builtin&&!challenge.trim()){const generated=await generateAdminBadgeChallenge("easy");challenge=generated.text;}let next=applyReleaseMode({...draft,challenge},effectiveMode);if(effectiveMode==="shop"&&next.xpCost<=0)throw new Error("Informe um valor em XP maior que zero.");if(effectiveMode==="emblem"&&!next.emblemIds.length)throw new Error("Escolha ao menos um emblema para liberar este item.");if(!builtin&&!next.imageRef.trim())throw new Error("Envie o PNG antes de salvar.");await saveAdminCosmetic(next);toast.success(`${kind==="moldura"?"Moldura":"Distintivo"} salvo e sincronizado.`);onSaved();onClose();}catch(error){toast.error(error instanceof Error?error.message:"Não foi possível salvar.");}finally{setBusy(false)}};
  const previewItem=applyReleaseMode(draft,effectiveMode);
  return <><div className="xp-admin-modal-backdrop" onMouseDown={onClose}><article className="xp-admin-modal" onMouseDown={(e)=>e.stopPropagation()}><header><div><small>{kind==="moldura"?"MOLDURAS":"DISTINTIVOS"}</small><h2>{initial?"Editar":"Adicionar"} {kind}</h2></div><button onClick={onClose}><X size={20}/></button></header><div className="xp-admin-form-grid"><label>Identificador<input value={draft.id} disabled={Boolean(initial)} placeholder="automático" onChange={(e)=>set("id",e.target.value)}/></label><label>Nome<input value={draft.name} onChange={(e)=>set("name",e.target.value)}/></label><label className="wide">Descrição<textarea value={draft.description} onChange={(e)=>set("description",e.target.value)}/></label></div>{!builtin&&<ChallengePicker value={draft.challenge} onChange={(value)=>set("challenge",value)}/>}<div className="xp-admin-upload"><label className="xp-admin-file"><Upload size={18}/><span>{busy?"Enviando…":"Enviar PNG transparente"}</span><input type="file" accept="image/png" disabled={busy} onChange={(e)=>{const file=e.target.files?.[0];if(file)void upload(file);e.currentTarget.value=""}}/></label>{draft.imageRef&&<small>Imagem configurada.</small>}</div><div className="xp-admin-release"><strong>Forma de liberação</strong><div>{(["shop","free","emblem"] as ReleaseMode[]).map((value)=><button key={value} disabled={builtin&&value!=="shop"} className={effectiveMode===value?"selected":""} onClick={()=>setMode(value)}>{value==="shop"?"Venda na Loja XP":value==="free"?"Gratuito p/ Todos":"Vinculado a emblema / ADM"}</button>)}</div></div>{effectiveMode==="shop"&&<label className="xp-admin-single-field">Valor em XP<input type="number" min="1" value={draft.xpCost} onChange={(e)=>set("xpCost",Math.max(1,Number(e.target.value)||1))}/></label>}{effectiveMode==="emblem"&&<div className="xp-admin-emblem-links"><strong>Emblemas que liberam este item</strong><div>{badgeOptions.map((badge)=><label key={badge.id}><input type="checkbox" checked={draft.emblemIds.includes(badge.id)} onChange={()=>toggleEmblem(badge.id)}/><span>{badge.name}</span></label>)}</div></div>}<label className="xp-admin-check"><input type="checkbox" checked={draft.active} onChange={(e)=>set("active",e.target.checked)}/> Item ativo</label><div className="xp-admin-modal-actions"><button className="xp-admin-secondary" onClick={()=>setPreviewMode("preview")}><Eye size={17}/> Prévia</button><button className="xp-admin-secondary" onClick={()=>setPreviewMode("test")}><TestTube2 size={17}/> Testar</button><button className="parity-primary" disabled={busy} onClick={()=>void save()}><Save size={17}/>{busy?"Salvando…":"Salvar"}</button></div></article></div>{previewMode&&<CosmeticPreview item={previewItem} testMode={previewMode==="test"} onClose={()=>setPreviewMode(null)}/>}</>;
}

export function PwaXpAdminCosmetics({kind}:{kind:"distintivo"|"moldura"}){
  const [items,setItems]=useState<AdminProfileCosmetic[]>([]); const [badges,setBadges]=useState<AdminCustomBadge[]>([]); const [loading,setLoading]=useState(true); const [editor,setEditor]=useState<AdminProfileCosmetic|null|undefined>(undefined); const [preview,setPreview]=useState<{item:AdminProfileCosmetic;test:boolean}|null>(null); const [page,setPage]=useState(0);
  const load=async()=>{setLoading(true);try{const [cosmetics,customBadges]=await Promise.all([loadAdminCosmetics(kind),loadAdminBadges()]);setItems(cosmetics);setBadges(customBadges)}catch(error){toast.error(error instanceof Error?error.message:"Falha ao carregar personalizações.");}finally{setLoading(false)}}; useEffect(()=>{void load()},[kind]);
  const badgeOptions=useMemo(()=>{const map=new Map<string,string>();biblicalBadges.forEach((item)=>map.set(item.id,item.name));badges.forEach((item)=>map.set(item.id,item.name));return [...map].map(([id,name])=>({id,name}))},[badges]); const total=Math.max(1,Math.ceil(items.length/PAGE_SIZE));const safe=Math.min(page,total-1);const visible=items.slice(safe*PAGE_SIZE,(safe+1)*PAGE_SIZE);
  const title=kind==="moldura"?"Molduras":"Distintivos";
  return <section className="xp-admin-section"><div className="xp-admin-section-head"><div><h2>{title}</h2><p>Controle compra, gratuidade e vínculo por emblema usando a mesma regra do Android.</p></div><button className="parity-primary" onClick={()=>setEditor(null)}><Plus size={18}/> Adicionar</button></div>{loading?<p className="parity-status">Carregando {title.toLowerCase()}…</p>:<div className="xp-admin-cards">{visible.map((item)=><article key={item.id}><div className="xp-admin-card-main"><div><small>{isBuiltinCosmeticId(item.id)?"Item interno":releaseMode(item)==="shop"?"Loja XP":releaseMode(item)==="free"?"Gratuito p/ Todos":"Emblema / ADM"}</small><strong>{item.name}</strong><p>{item.description}</p></div><span className="xp-admin-card-icon">{kind==="distintivo"?<Star size={24}/>:<ShieldCheck size={24}/>}</span></div><div className="xp-admin-card-meta"><span>{item.purchasable?`${item.xpCost} XP`:item.freeForAll?"Livre":`${item.emblemIds.length} vínculo(s)`}</span><span>{item.active?"Ativo":"Inativo"}</span></div><div className="xp-admin-card-actions"><button onClick={()=>setPreview({item,test:false})}><Eye size={16}/> Prévia</button><button onClick={()=>setPreview({item,test:true})}><TestTube2 size={16}/> Testar</button><button onClick={()=>setEditor(item)}><Pencil size={16}/> Editar</button></div></article>)}</div>}<div className="xp-admin-pagination"><button disabled={safe===0} onClick={()=>setPage(Math.max(0,safe-1))}>Anterior</button><strong>{safe+1}/{total}</strong><button disabled={safe>=total-1} onClick={()=>setPage(Math.min(total-1,safe+1))}>Próxima</button></div><button className="xp-admin-refresh" onClick={()=>void load()}><RefreshCcw size={16}/> Atualizar</button>{editor!==undefined&&<CosmeticEditor kind={kind} initial={editor} badgeOptions={badgeOptions} onClose={()=>setEditor(undefined)} onSaved={()=>void load()}/>} {preview&&<CosmeticPreview item={preview.item} testMode={preview.test} onClose={()=>setPreview(null)}/>}</section>;
}
