name: Build Android APK

on:
  push:
    branches:
      - main
  workflow_dispatch: 

jobs:
  build:
    name: Gerar APK
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar o Java JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17' 
          distribution: 'temurin'

      # Esta é a etapa nova que vai consertar o erro do arquivo corrompido
      - name: Corrigir o Gradle Wrapper
        run: gradle wrapper

      - name: Dar permissão de execução ao Gradle
        run: chmod +x ./gradlew

      - name: Construir o APK (Debug)
        run: ./gradlew assembleDebug

      # Modificado para encontrar o APK em qualquer pasta do projeto
      - name: Upload do APK
        uses: actions/upload-artifact@v4
        with:
          name: meu-app-apk
          path: '**/*.apk'
