name: Build Android APK
on:
  push:
    branches:
      - main
  workflow_dispatch: 
jobs:
  build:
    name: Gerar APK
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4
      - name: Configurar o Java JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21' 
          distribution: 'temurin'
      - name: Criar chave de assinatura (debug.keystore)
        run: keytool -genkey -v -keystore debug.keystore -storepass android -alias androiddebugkey -keypass android -keyalg RSA -keysize 2048 -validity 10000 -dname "C=BR, O=Android, CN=Android Debug"
      - name: Construir o APK
        run: gradle assembleDebug
      - name: Upload do APK
        uses: actions/upload-artifact@v4
        with:
          name: aplicativo-pronto
          path: '**/*.apk'
